extends RefCounted
## EBP02: Booster Pack 02 — card data only, split verbatim from card_data.gd.

var CARDS: Array[Dictionary] = [
	{
		"id": "EBP02-001",
		"name": "Giant Unknown Creature",
		"card_type": CardEnums.CardType.MONSTER,
		"rank": 1,
		"colors": [CardEnums.CardColor.RED],
		"traits": [CardEnums.CardTrait.GODZILLA],
		"threat_level": 4000,
		"invasion_icon": 1,
		"description": "<Opponent’s Turn> At the beginning of the counter phase, you may discard 1 strategy card from your hand to increase this card's <Rage> by 1.",
		"effect_script": "res://scripts/effects/ebp02/ebp02_001.gd"
	},
	{
		"id": "EBP02-002",
		"name": "Godzilla(2016) 2nd Form",
		"card_type": CardEnums.CardType.MONSTER,
		"rank": 2,
		"colors": [CardEnums.CardColor.RED],
		"traits": [CardEnums.CardTrait.GODZILLA, CardEnums.CardTrait.SECOND_FORM],
		"threat_level": 11000,
		"invasion_icon": 1,
		"description": "If you have 1 or more strategy cards in play, this card gains +5000 threat level.",
		"effect_script": "res://scripts/effects/ebp02/ebp02_002.gd"
	},
	{
		"id": "EBP02-003",
		"name": "Godzilla(2016) 2nd Form",
		"card_type": CardEnums.CardType.MONSTER,
		"rank": 2,
		"colors": [CardEnums.CardColor.RED],
		"traits": [CardEnums.CardTrait.GODZILLA, CardEnums.CardTrait.SECOND_FORM],
		"threat_level": 12000,
		"invasion_icon": 1,
		"description": "<Burst3> (You can play this card from rank III. If you do, send this card to your discard pile at the beginning of your next end phase.)\n<Enter> If there is a card named “Giant Unknown Creature” under this card, you may discard 1 strategy card from your hand to advance this card by 1 zone.",
		"effect_script": "res://scripts/effects/ebp02/ebp02_003.gd"
	},
	{
		"id": "EBP02-004",
		"name": "Godzilla(2016) 3rd Form",
		"card_type": CardEnums.CardType.MONSTER,
		"rank": 3,
		"colors": [CardEnums.CardColor.RED],
		"traits": [CardEnums.CardTrait.GODZILLA, CardEnums.CardTrait.THIRD_FORM],
		"threat_level": 22000,
		"invasion_icon": 1,
		"description": "<Burst2> (You can play this card from rank II. If you do, send this card to your discard pile at the beginning of your next end phase.)\n<Enter> If there is a <《2nd Form》> card under this card, <Destroy> 1 of your opponent's rank 6 or lower battle cards for each strategy card in your strategy zone.",
		"effect_script": "res://scripts/effects/ebp02/ebp02_004.gd"
	},
	{
		"id": "EBP02-005",
		"name": "Godzilla(2016) 3rd Form",
		"card_type": CardEnums.CardType.MONSTER,
		"rank": 3,
		"colors": [CardEnums.CardColor.RED],
		"traits": [CardEnums.CardTrait.GODZILLA, CardEnums.CardTrait.THIRD_FORM],
		"threat_level": 23000,
		"invasion_icon": 1,
		"description": "<Your Turn> <Awakening6> Whenever this card's <Rage> is increased, if you have a strategy card in play, your opponent discards cards until they have 3 cards remaining in their hand.",
		"effect_script": "res://scripts/effects/ebp02/ebp02_005.gd"
	},
	{
		"id": "EBP02-006",
		"name": "Godzilla(2016) 4th Form",
		"card_type": CardEnums.CardType.MONSTER,
		"rank": 4,
		"colors": [CardEnums.CardColor.RED],
		"traits": [CardEnums.CardTrait.GODZILLA, CardEnums.CardTrait.FOURTH_FORM],
		"threat_level": 33000,
		"invasion_icon": 2,
		"description": "<When Invading> If there is a card with <《3rd Form》> under this card, <Destroy> all of your opponent's rank 6 or lower battle cards.\nIf there is a <《4th Form》> card under this card, this card gains +10,000 threat level for each strategy card in your strategy zone.",
		"effect_script": "res://scripts/effects/ebp02/ebp02_006.gd"
	},
	{
		"id": "EBP02-007",
		"name": "Godzilla(2016) 4th Form",
		"card_type": CardEnums.CardType.MONSTER,
		"rank": 4,
		"colors": [CardEnums.CardColor.RED],
		"traits": [CardEnums.CardTrait.GODZILLA, CardEnums.CardTrait.FOURTH_FORM],
		"threat_level": 36000,
		"invasion_icon": 1,
		"description": "<Burst3> (You can play this card from rank III. If you do, send this card to your discard pile at the beginning of your next end phase.)\n<Enter> You may discard 1 strategy card from your hand. If you do, reveal the top 5 cards of your deck, add 1 monster card from among them to your hand, then send the rest to your discard pile.",
		"effect_script": "res://scripts/effects/ebp02/ebp02_007.gd"
	},
	{
		"id": "EBP02-008",
		"name": "Godzilla(1969)",
		"card_type": CardEnums.CardType.MONSTER,
		"rank": 3,
		"colors": [CardEnums.CardColor.RED],
		"traits": [CardEnums.CardTrait.GODZILLA],
		"threat_level": 24000,
		"invasion_icon": 2,
		"description": "<Burst4> (You can play this card from rank Ⅳ. If you do, send this card to your discard pile at the beginning of your next end phase.)\nWhenever this card's <Rage> is increased, <Destroy> all of your opponent's rank 6 or lower battle cards in the zone with the same number as the zone this card occupies.",
		"effect_script": "res://scripts/effects/ebp02/ebp02_008.gd"
	},
	{
		"id": "EBP02-009",
		"name": "Godzilla(2023)",
		"card_type": CardEnums.CardType.MONSTER,
		"rank": 4,
		"colors": [CardEnums.CardColor.RED],
		"traits": [CardEnums.CardTrait.GODZILLA],
		"threat_level": 35000,
		"invasion_icon": 1,
		"description": "<Burst3> (You can play this card from rank III. If you do, send this card to your discard pile at the beginning of your next end phase.)\nWhen this card is discarded by the effect of Burst, return this card from your discard pile to your hand.\n<When Invading> Your opponent discards cards until they have 3 cards remaining in their hand.",
		"effect_script": "res://scripts/effects/ebp02/ebp02_009.gd"
	},
	{
		"id": "EBP02-010",
		"name": "King Caesar(2004)",
		"card_type": CardEnums.CardType.BATTLE,
		"rank": 2,
		"colors": [CardEnums.CardColor.RED],
		"traits": [CardEnums.CardTrait.KING_CAESAR, CardEnums.CardTrait.FINAL_WARS],
		"counter_power": 1000,
		"invasion_icon": 1,
		"description": "<Enter> Move 1 of your other battle cards in your zones to an unoccupied zone.",
		"effect_script": "res://scripts/effects/ebp02/ebp02_010.gd"
	},
	{
		"id": "EBP02-011",
		"name": "Gabara",
		"card_type": CardEnums.CardType.BATTLE,
		"rank": 3,
		"colors": [CardEnums.CardColor.RED],
		"traits": [CardEnums.CardTrait.GABARA],
		"counter_power": 2000,
		"invasion_icon": 1,
		"description": "If your monster card has 2 or more <Rage> , this card gains +3000 counter power.",
		"effect_script": "res://scripts/effects/ebp02/ebp02_011.gd"
	},
	{
		"id": "EBP02-012",
		"name": "Godzilla(2016) Frozen",
		"card_type": CardEnums.CardType.BATTLE,
		"rank": 4,
		"colors": [CardEnums.CardColor.RED],
		"traits": [CardEnums.CardTrait.GODZILLA, CardEnums.CardTrait.FOURTH_FORM],
		"counter_power": 0,
		"invasion_icon": 1,
		"description": "If this card is in zone 8, whenever your strategy cards would be discarded from the strategy zone, you may place them under this card instead.\n<Awakening4> At the beginning of your main phase, if there are 2 or more cards under this card, counter your opponent's monster card.",
		"effect_script": "res://scripts/effects/ebp02/ebp02_012.gd"
	},
	{
		"id": "EBP02-013",
		"name": "Minilla(1969)",
		"card_type": CardEnums.CardType.BATTLE,
		"rank": 5,
		"colors": [CardEnums.CardColor.RED],
		"traits": [CardEnums.CardTrait.MINILLA],
		"counter_power": 2000,
		"invasion_icon": 2,
		"description": "<Enter> If your monster card has 2 or more <Rage> , advance your monster card to zone 5.",
		"effect_script": "res://scripts/effects/ebp02/ebp02_013.gd"
	},
	{
		"id": "EBP02-014",
		"name": "Cabinet Helicopter",
		"card_type": CardEnums.CardType.BATTLE,
		"rank": 6,
		"colors": [CardEnums.CardColor.RED],
		"traits": [CardEnums.CardTrait.MECH],
		"counter_power": 3000,
		"invasion_icon": 1,
		"description": "<Enter> Send the top card of your deck to your discard pile. If it is a monster card, advance your monster card to zone 6.",
		"effect_script": "res://scripts/effects/ebp02/ebp02_014.gd"
	},
	{
		"id": "EBP02-015",
		"name": "Rodan(2004)",
		"card_type": CardEnums.CardType.BATTLE,
		"rank": 6,
		"colors": [CardEnums.CardColor.RED],
		"traits": [CardEnums.CardTrait.RODAN, CardEnums.CardTrait.FINAL_WARS],
		"counter_power": 4000,
		"invasion_icon": 1,
		"description": "If this card is in a zone with the same number as the zone that your opponent's monster card occupies, this card gains +3000 counter power.",
		"effect_script": "res://scripts/effects/ebp02/ebp02_015.gd"
	},
	{
		"id": "EBP02-016",
		"name": "Anguirus(2004)",
		"card_type": CardEnums.CardType.BATTLE,
		"rank": 7,
		"colors": [CardEnums.CardColor.RED],
		"traits": [CardEnums.CardTrait.ANGUIRUS, CardEnums.CardTrait.FINAL_WARS],
		"counter_power": 7000,
		"invasion_icon": 1,
		"description": "If this card is in the same column as the opponent's monster card, this card gains +5000 counter power.",
		"effect_script": "res://scripts/effects/ebp02/ebp02_016.gd"
	},
	{
		"id": "EBP02-017",
		"name": "Operation Taba",
		"card_type": CardEnums.CardType.STRATEGY,
		"rank": 2,
		"colors": [CardEnums.CardColor.RED],
		"invasion_icon": 1,
		"description": "<Your Turn> If you have 4 or more battle cards in your zones, increase your total counter power by 5000.",
		"effect_script": "res://scripts/effects/ebp02/ebp02_017.gd"
	},
	{
		"id": "EBP02-018",
		"name": "Despair",
		"card_type": CardEnums.CardType.STRATEGY,
		"rank": 3,
		"colors": [CardEnums.CardColor.RED],
		"invasion_icon": 1,
		"description": "If your monster card has 2 or more <Rage> , <Destroy> 1 of your opponent's battle cards that is occupying a zone at or before the zone your monster card currently occupies. (If your monster card is in Zone 4, you can select battle cards in your opponent's zone 1, 2, 3, or 4.)",
		"effect_script": "res://scripts/effects/ebp02/ebp02_018.gd"
	},
	{
		"id": "EBP02-019",
		"name": "There is no danger of the creature coming ashore.",
		"common_names": ["TINDOTCCA"],
		"card_type": CardEnums.CardType.STRATEGY,
		"rank": 4,
		"colors": [CardEnums.CardColor.RED],
		"invasion_icon": 1,
		"description": "Move 1 battle card in your zones to an unoccupied zone. If your monster card invaded this turn, advance your monster card by 1 zone.",
		"effect_script": "res://scripts/effects/ebp02/ebp02_019.gd"
	},
	{
		"id": "EBP02-020",
		"name": "Operation Yashiori -Conductorless train bombers-",
		"card_type": CardEnums.CardType.STRATEGY,
		"rank": 6,
		"colors": [CardEnums.CardColor.RED],
		"invasion_icon": 2,
		"effect_script": "res://scripts/effects/ebp02/ebp02_020.gd",
		"description": "If you have 5 or more strategy cards in your discard pile, create “Conductorless train bombers” tokens in each of your unoccupied zones. (Tokens are prepared separately from your main deck.)"
	},
	{
		"id": "EBP02-021",
		"name": "Godzilla(1993)",
		"card_type": CardEnums.CardType.MONSTER,
		"rank": 3,
		"colors": [CardEnums.CardColor.BLUE],
		"traits": [CardEnums.CardTrait.GODZILLA],
		"threat_level": 25000,
		"invasion_icon": 2,
		"description": "All of your rank 5 or lower battle cards in zones adjacent to this card gain +3000 counter power.",
		"effect_script": "res://scripts/effects/ebp02/ebp02_021.gd"
	},
	{
		"id": "EBP02-022",
		"name": "Godzilla(1994)",
		"card_type": CardEnums.CardType.MONSTER,
		"rank": 4,
		"colors": [CardEnums.CardColor.BLUE],
		"traits": [CardEnums.CardTrait.GODZILLA],
		"threat_level": 36000,
		"invasion_icon": 1,
		"description": "<When Invading> If you discarded a blue battle card for this card's invade action, you may play that battle card from your discard pile.",
		"effect_script": "res://scripts/effects/ebp02/ebp02_022.gd"
	},
	{
		"id": "EBP02-023",
		"name": "Godzilla(1999)",
		"card_type": CardEnums.CardType.MONSTER,
		"rank": 4,
		"colors": [CardEnums.CardColor.BLUE],
		"traits": [CardEnums.CardTrait.GODZILLA],
		"threat_level": 34000,
		"invasion_icon": 1,
		"description": "<Enter> If you have 5 or more monster cards in your discard pile, 1 of your opponent's monster cards with 50,000 or less threat level retreats back by 1 zone.\nIf you have 10 or more monster cards in your discard pile, this card gains +10,000 threat level.",
		"effect_script": "res://scripts/effects/ebp02/ebp02_023.gd"
	},
	{
		"id": "EBP02-024",
		"name": "Biollante Rose Form",
		"card_type": CardEnums.CardType.MONSTER,
		"rank": 1,
		"colors": [CardEnums.CardColor.BLUE],
		"traits": [CardEnums.CardTrait.BIOLLANTE],
		"threat_level": 6000,
		"invasion_icon": 1,
		"start_zone": 5,
		"effect_script": "res://scripts/effects/ebp02/ebp02_024.gd",
		"description": "If this card is in your monster deck, at the start of the game it will be played in Zone 5.\nThis card cannot advance nor invade."
	},
	{
		"id": "EBP02-025",
		"name": "Biollante Rose Form",
		"card_type": CardEnums.CardType.MONSTER,
		"rank": 2,
		"colors": [CardEnums.CardColor.BLUE],
		"traits": [CardEnums.CardTrait.BIOLLANTE],
		"threat_level": 11000,
		"invasion_icon": 1,
		"effect_script": "res://scripts/effects/ebp02/ebp02_025.gd",
		"description": "This card cannot advance nor invade.\n<Enter> Play 1 “Tentacles” token in a zone adjacent to this card. (Tokens are prepared separately from your main deck.)"
	},
	{
		"id": "EBP02-026",
		"name": "Biollante Plant Beast Form",
		"card_type": CardEnums.CardType.MONSTER,
		"rank": 3,
		"colors": [CardEnums.CardColor.BLUE],
		"traits": [CardEnums.CardTrait.BIOLLANTE],
		"threat_level": 22000,
		"invasion_icon": 1,
		"description": "<Enter> If you have a strategy card in play, choose 1 of your opponent's zones. <Destroy> all of your opponent's rank 5 or lower battle cards in that zone and zones adjacent to it.",
		"effect_script": "res://scripts/effects/ebp02/ebp02_026.gd"
	},
	{
		"id": "EBP02-027",
		"name": "Biollante Plant Beast Form",
		"card_type": CardEnums.CardType.MONSTER,
		"rank": 3,
		"colors": [CardEnums.CardColor.BLUE],
		"traits": [CardEnums.CardTrait.BIOLLANTE],
		"threat_level": 23000,
		"invasion_icon": 1,
		"effect_script": "res://scripts/effects/ebp02/ebp02_027.gd",
		"description": "<Opponent’s Turn> <Awakening6> If your opponent has a strategy card in play, this card cannot be countered by 40,000 or lower counter power. Instead, it only moves as though it were countered. (Do not play the next Monster Card from your monster deck.)"
	},
	{
		"id": "EBP02-028",
		"name": "Biollante Plant Beast Form",
		"card_type": CardEnums.CardType.MONSTER,
		"rank": 4,
		"colors": [CardEnums.CardColor.BLUE],
		"traits": [CardEnums.CardTrait.BIOLLANTE],
		"threat_level": 32000,
		"invasion_icon": 2,
		"effect_script": "res://scripts/effects/ebp02/ebp02_028.gd",
		"description": "<Enter> Play as many rank 4 or lower battle cards with <Evolution> from your discard pile to each of this card's adjacent zones. (You must play as many as possible and you may play the battle cards in zones already occupied by other battle cards. Maximum of 3 cards.)"
	},
	{
		"id": "EBP02-029",
		"name": "Biollante Plant Beast Form",
		"card_type": CardEnums.CardType.MONSTER,
		"rank": 4,
		"colors": [CardEnums.CardColor.BLUE],
		"traits": [CardEnums.CardTrait.BIOLLANTE],
		"threat_level": 55000,
		"invasion_icon": 1,
		"effect_script": "res://scripts/effects/ebp02/ebp02_029.gd",
		"description": "<Opponent’s Turn> At the beginning of the counter phase, for the rest of the turn, double the counter power of all of your opponent's battle cards in the same column as this card. (Refer to those battle card's counter power at the ability resolution timing.)"
	},
	{
		"id": "EBP02-030",
		"name": "Baby Godzilla",
		"card_type": CardEnums.CardType.BATTLE,
		"rank": 1,
		"colors": [CardEnums.CardColor.BLUE],
		"traits": [CardEnums.CardTrait.BABY_GODZILLA],
		"counter_power": 0,
		"invasion_icon": 1,
		"description": "<Evolution5> <《Little Godzilla》> (At the beginning of your main phase, you may play a rank 5 or lower <《Little Godzilla》> battle card from your deck by placing it on top of this card.)",
		"evolution_rank": 5,
		"evolution_trait": CardEnums.CardTrait.LITTLE_GODZILLA,
		"effect_script": "res://scripts/effects/ebp02/ebp02_030.gd"
	},
	{
		"id": "EBP02-031",
		"name": "MBT-MB92 modified",
		"card_type": CardEnums.CardType.BATTLE,
		"rank": 4,
		"colors": [CardEnums.CardColor.BLUE],
		"traits": [CardEnums.CardTrait.WEAPON],
		"counter_power": 2000,
		"invasion_icon": 1,
		"unlimited_copies": true,
		"description": "You may have any number of this card in your deck.\nIf the number of other rank 5 or lower battle cards in your zones is 2 or more, this card gains +3000 counter power.",
		"effect_script": "res://scripts/effects/ebp02/ebp02_031.gd"
	},
	{
		"id": "EBP02-032",
		"name": "Biollante Rose Form",
		"card_type": CardEnums.CardType.BATTLE,
		"rank": 4,
		"colors": [CardEnums.CardColor.BLUE],
		"traits": [CardEnums.CardTrait.BIOLLANTE],
		"counter_power": 3000,
		"invasion_icon": 1,
		"description": "<Evolution7> <《Biollante》> (At the beginning of your main phase, you may play a rank 7 or lower <《Biollante》> battle card from your deck by placing it on top of this card.)",
		"evolution_rank": 7,
		"evolution_trait": CardEnums.CardTrait.BIOLLANTE,
		"effect_script": "res://scripts/effects/ebp02/ebp02_032.gd"
	},
	{
		"id": "EBP02-033",
		"name": "Little Godzilla",
		"card_type": CardEnums.CardType.BATTLE,
		"rank": 5,
		"colors": [CardEnums.CardColor.BLUE],
		"traits": [CardEnums.CardTrait.LITTLE_GODZILLA],
		"counter_power": 3000,
		"invasion_icon": 1,
		"description": "<Awakening4> This card gains +3000 counter power. (Active if your monster card is in zone 4 or beyond.)",
		"effect_script": "res://scripts/effects/ebp02/ebp02_033.gd"
	},
	{
		"id": "EBP02-034",
		"name": "Super X3",
		"card_type": CardEnums.CardType.BATTLE,
		"rank": 6,
		"colors": [CardEnums.CardColor.BLUE],
		"traits": [CardEnums.CardTrait.SUPER_X, CardEnums.CardTrait.WEAPON],
		"counter_power": 5000,
		"invasion_icon": 1,
		"description": "If this card is in zone 8, this card gains +3000 counter power.",
		"effect_script": "res://scripts/effects/ebp02/ebp02_034.gd"
	},
	{
		"id": "EBP02-035",
		"name": "Biollante Plant Beast Form",
		"card_type": CardEnums.CardType.BATTLE,
		"rank": 7,
		"colors": [CardEnums.CardColor.BLUE],
		"traits": [CardEnums.CardTrait.BIOLLANTE],
		"counter_power": 5000,
		"invasion_icon": 2,
		"description": "<Enter> If you have 2 or more cards with <《Biollante》> in your discard pile, return all cards in your opponent's discard pile to their deck then shuffle.\n<Enter> Play 2 “Tentacles” tokens in zones adjacent to this card. (Tokens are prepared separately from your main deck.)",
		"effect_script": "res://scripts/effects/ebp02/ebp02_035.gd"
	},
	{
		"id": "EBP02-036",
		"name": "Godzilla(1994)",
		"card_type": CardEnums.CardType.BATTLE,
		"rank": 7,
		"colors": [CardEnums.CardColor.BLUE],
		"traits": [CardEnums.CardTrait.GODZILLA],
		"counter_power": 6000,
		"invasion_icon": 1,
		"description": "At the beginning of your end phase, if this card is in a zone adjacent to your monster card, 1 of your opponent's monster cards with 40,000 or less threat level retreats back by 1 zone.",
		"effect_script": "res://scripts/effects/ebp02/ebp02_036.gd"
	},
	{
		"id": "EBP02-037",
		"name": "Destoroyah Perfect Form",
		"card_type": CardEnums.CardType.BATTLE,
		"rank": 8,
		"colors": [CardEnums.CardColor.BLUE],
		"traits": [CardEnums.CardTrait.DESTOROYAH],
		"counter_power": 9000,
		"invasion_icon": 1,
		"description": "<Enter> Draw 2 cards, then discard 2 cards.",
		"effect_script": "res://scripts/effects/ebp02/ebp02_037.gd"
	},
	{
		"id": "EBP02-038",
		"name": "Godzilla 2000: Millennium",
		"card_type": CardEnums.CardType.STRATEGY,
		"rank": 2,
		"colors": [CardEnums.CardColor.BLUE],
		"invasion_icon": 1,
		"description": "Choose one of the following:\n\n・ <Destroy> 1 of your opponent's rank 5 or lower battle cards.\n・If you have 10 or more monster cards in your discard pile, <Destroy> 1 of your opponent's battle cards in zone 8.",
		"effect_script": "res://scripts/effects/ebp02/ebp02_038.gd"
	},
	{
		"id": "EBP02-039",
		"name": "Lake Ashi Monster",
		"card_type": CardEnums.CardType.STRATEGY,
		"rank": 5,
		"colors": [CardEnums.CardColor.BLUE],
		"invasion_icon": 1,
		"description": "<Your Turn> You can play battle cards with <《Biollante》> from your hand with their rank reduced by 3. (They return to their original rank after being played.)",
		"effect_script": "res://scripts/effects/ebp02/ebp02_039.gd"
	},
	{
		"id": "EBP02-040",
		"name": "Interception Operation",
		"card_type": CardEnums.CardType.STRATEGY,
		"rank": 7,
		"colors": [CardEnums.CardColor.BLUE],
		"invasion_icon": 2,
		"description": "If you have 5 or more <《Weapon》> battle cards with “MB” in their name in your zones, discard your hand and draw 5 cards.",
		"effect_script": "res://scripts/effects/ebp02/ebp02_040.gd"
	},
	{
		"id": "EBP02-041",
		"name": "Gigan(1972)",
		"card_type": CardEnums.CardType.MONSTER,
		"rank": 1,
		"colors": [CardEnums.CardColor.GREEN],
		"traits": [CardEnums.CardTrait.GIGAN, CardEnums.CardTrait.WEAPON],
		"threat_level": 5000,
		"invasion_icon": 1,
		"description": "Each of your battle cards in zones adjacent to this card gain +1000 counter power.",
		"effect_script": "res://scripts/effects/ebp02/ebp02_041.gd"
	},
	{
		"id": "EBP02-042",
		"name": "Gigan(1972)",
		"card_type": CardEnums.CardType.MONSTER,
		"rank": 2,
		"colors": [CardEnums.CardColor.GREEN],
		"traits": [CardEnums.CardTrait.GIGAN, CardEnums.CardTrait.WEAPON],
		"threat_level": 11000,
		"invasion_icon": 1,
		"description": "<Enter> You may discard a card with <《King Ghidorah》> or <《Megalon》> from your hand to reduce your opponent's <Rage> by 2.\nAt the beginning of your end phase, if your opponent's monster card is in zone 1–5, increase this card's <Rage> by 1.",
		"effect_script": "res://scripts/effects/ebp02/ebp02_042.gd"
	},
	{
		"id": "EBP02-043",
		"name": "Gigan(2004)",
		"card_type": CardEnums.CardType.MONSTER,
		"rank": 3,
		"colors": [CardEnums.CardColor.GREEN],
		"traits": [CardEnums.CardTrait.GIGAN, CardEnums.CardTrait.WEAPON],
		"threat_level": 18000,
		"invasion_icon": 1,
		"description": "Each of your battle cards in zones adjacent to this card gain +1000 counter power for each card under this card.",
		"effect_script": "res://scripts/effects/ebp02/ebp02_043.gd"
	},
	{
		"id": "EBP02-044",
		"name": "Modified Gigan",
		"card_type": CardEnums.CardType.MONSTER,
		"rank": 4,
		"colors": [CardEnums.CardColor.GREEN],
		"traits": [CardEnums.CardTrait.GIGAN, CardEnums.CardTrait.WEAPON],
		"threat_level": 32000,
		"invasion_icon": 2,
		"description": "<When Invading> If your opponent's monster card is in zones 6–8, reduce their <Rage> by 2.\nAt the beginning of your end phase, if your opponent's monster card is in zones 1–5, increase this card's <Rage> by 2.",
		"effect_script": "res://scripts/effects/ebp02/ebp02_044.gd"
	},
	{
		"id": "EBP02-045",
		"name": "King Ghidorah(1964)",
		"card_type": CardEnums.CardType.MONSTER,
		"rank": 2,
		"colors": [CardEnums.CardColor.GREEN],
		"traits": [CardEnums.CardTrait.KING_GHIDORAH],
		"threat_level": 11000,
		"invasion_icon": 1,
		"description": "This card gains +3000 threat level for each rank of your opponent's monster.",
		"effect_script": "res://scripts/effects/ebp02/ebp02_045.gd"
	},
	{
		"id": "EBP02-046",
		"name": "King Ghidorah(1965)",
		"card_type": CardEnums.CardType.MONSTER,
		"rank": 3,
		"colors": [CardEnums.CardColor.GREEN],
		"traits": [CardEnums.CardTrait.KING_GHIDORAH],
		"threat_level": 23000,
		"invasion_icon": 1,
		"description": "<Enter> Place all cards with the same name as this card from your discard pile under this card.\nThis card gains +3000 threat level for each card with the same name under this card.",
		"effect_script": "res://scripts/effects/ebp02/ebp02_046.gd"
	},
	{
		"id": "EBP02-047",
		"name": "King Ghidorah(1991)",
		"card_type": CardEnums.CardType.MONSTER,
		"rank": 1,
		"colors": [CardEnums.CardColor.GREEN],
		"traits": [CardEnums.CardTrait.KING_GHIDORAH],
		"threat_level": 5000,
		"invasion_icon": 1,
		"description": "Whenever this card advances, send the top card of your deck to your discard pile.",
		"effect_script": "res://scripts/effects/ebp02/ebp02_047.gd"
	},
	{
		"id": "EBP02-048",
		"name": "King Ghidorah(1991)",
		"card_type": CardEnums.CardType.MONSTER,
		"rank": 2,
		"colors": [CardEnums.CardColor.GREEN],
		"traits": [CardEnums.CardTrait.KING_GHIDORAH],
		"threat_level": 11000,
		"invasion_icon": 1,
		"description": "<Enter> Send the top 3 cards of your deck to your discard pile.\n<When Invading> <Destroy> 3 of your opponent's rank 4 or lower battle cards.",
		"effect_script": "res://scripts/effects/ebp02/ebp02_048.gd"
	},
	{
		"id": "EBP02-049",
		"name": "King Ghidorah(1991)",
		"card_type": CardEnums.CardType.MONSTER,
		"rank": 3,
		"colors": [CardEnums.CardColor.GREEN],
		"traits": [CardEnums.CardTrait.KING_GHIDORAH],
		"threat_level": 21000,
		"invasion_icon": 1,
		"description": "<Enter> If there are 3 or more cards under this card, choose one of the following:\n・ <Destroy> 3 of your opponent's rank 5 or lower battle cards.\n・Your opponent discards cards until they have 3 cards remaining in their hand.\n・Send the top 3 cards of your deck to your discard pile.",
		"effect_script": "res://scripts/effects/ebp02/ebp02_049.gd"
	},
	{
		"id": "EBP02-050",
		"name": "Mecha-King Ghidorah",
		"card_type": CardEnums.CardType.MONSTER,
		"rank": 4,
		"colors": [CardEnums.CardColor.GREEN],
		"traits": [CardEnums.CardTrait.KING_GHIDORAH, CardEnums.CardTrait.TWENTY_THIRD_CENTURY],
		"threat_level": 34000,
		"invasion_icon": 2,
		"description": "<Enter> If there are 5 or more cards under this card, choose one of the following:\n・ <Destroy> 3 of your opponent's rank 6 or lower battle cards.\n・Your opponent discards cards until they have 2 cards remaining in their hand.\n・Increase this card's <Rage> by 3.",
		"effect_script": "res://scripts/effects/ebp02/ebp02_050.gd"
	},
	{
		"id": "EBP02-051",
		"name": "Mecha-King Ghidorah",
		"card_type": CardEnums.CardType.MONSTER,
		"rank": 4,
		"colors": [CardEnums.CardColor.GREEN],
		"traits": [CardEnums.CardTrait.KING_GHIDORAH, CardEnums.CardTrait.TWENTY_THIRD_CENTURY],
		"threat_level": 37000,
		"invasion_icon": 1,
		"description": "If there are 5 or more cards under this card, this card gains +3000 threat level for each of your opponent's unoccupied zones.",
		"effect_script": "res://scripts/effects/ebp02/ebp02_051.gd"
	},
	{
		"id": "EBP02-052",
		"name": "SpaceGodzilla Flying Form",
		"card_type": CardEnums.CardType.MONSTER,
		"rank": 1,
		"colors": [CardEnums.CardColor.GREEN],
		"traits": [CardEnums.CardTrait.SPACEGODZILLA],
		"threat_level": 5000,
		"invasion_icon": 1,
		"effect_script": "res://scripts/effects/ebp02/ebp02_052.gd",
		"description": "<When Invading> You may discard 1 card from your hand, if you do, play 1 “Crystals” token. (Tokens are prepared separately from your deck.)"
	},
	{
		"id": "EBP02-053",
		"name": "SpaceGodzilla",
		"card_type": CardEnums.CardType.MONSTER,
		"rank": 2,
		"colors": [CardEnums.CardColor.GREEN],
		"traits": [CardEnums.CardTrait.SPACEGODZILLA],
		"threat_level": 12000,
		"invasion_icon": 1,
		"effect_script": "res://scripts/effects/ebp02/ebp02_053.gd",
		"description": "<When Invading> Play 1 “Crystals” token. (Tokens are prepared separately from your deck.)\nIf there is a “Crystals” in your zones, this card gains +5000 threat level."
	},
	{
		"id": "EBP02-054",
		"name": "SpaceGodzilla",
		"card_type": CardEnums.CardType.MONSTER,
		"rank": 3,
		"colors": [CardEnums.CardColor.GREEN],
		"traits": [CardEnums.CardTrait.SPACEGODZILLA],
		"threat_level": 20000,
		"invasion_icon": 1,
		"effect_script": "res://scripts/effects/ebp02/ebp02_054.gd",
		"description": "<Enter> Play 2 “Crystals” tokens. (Tokens are prepared separately from your deck.)\nWhenever this card's <Rage> is increased, <Destroy> 1 of your opponent's rank 5 or lower battle cards for each “Crystals” in your zones."
	},
	{
		"id": "EBP02-055",
		"name": "SpaceGodzilla",
		"card_type": CardEnums.CardType.MONSTER,
		"rank": 3,
		"colors": [CardEnums.CardColor.GREEN],
		"traits": [CardEnums.CardTrait.SPACEGODZILLA],
		"threat_level": 23000,
		"invasion_icon": 1,
		"effect_script": "res://scripts/effects/ebp02/ebp02_055.gd",
		"description": "<Awakening4> If there are 3 or more “Crystals” in your zones, your opponent cannot play battle cards in zones in the same column as this card. (Does not destroy cards already there.)"
	},
	{
		"id": "EBP02-056",
		"name": "SpaceGodzilla",
		"card_type": CardEnums.CardType.MONSTER,
		"rank": 4,
		"colors": [CardEnums.CardColor.GREEN],
		"traits": [CardEnums.CardTrait.SPACEGODZILLA],
		"threat_level": 32000,
		"invasion_icon": 2,
		"effect_script": "res://scripts/effects/ebp02/ebp02_056.gd",
		"description": "If you have 3 or more “Crystals” in your zones, this card gains +20,000 threat level.\n<Your Turn> When this card advances during the end phase, it advances 1 additional zone for each “Crystals” in your zones."
	},
	{
		"id": "EBP02-057",
		"name": "SpaceGodzilla Flying Form",
		"card_type": CardEnums.CardType.MONSTER,
		"rank": 4,
		"colors": [CardEnums.CardColor.GREEN],
		"traits": [CardEnums.CardTrait.SPACEGODZILLA],
		"threat_level": 35000,
		"invasion_icon": 1,
		"description": "<Enter> Move 1 of your opponent's battle cards in the same column as this card to an unoccupied zone.\nWhenever this card's <Rage> is increased, play 2 “Crystals” tokens. (Tokens are prepared separately from your deck.)",
		"effect_script": "res://scripts/effects/ebp02/ebp02_057.gd"
	},
	{
		"id": "EBP02-058",
		"name": "Dorat",
		"card_type": CardEnums.CardType.BATTLE,
		"rank": 2,
		"colors": [CardEnums.CardColor.GREEN],
		"traits": [CardEnums.CardTrait.DORAT],
		"counter_power": 1000,
		"invasion_icon": 1,
		"description": "<Revenge> Return up to 1 <《King Ghidorah》> monster card from your discard pile to your hand. (Activates when destroyed by a card effect or monster card movement.)",
		"effect_script": "res://scripts/effects/ebp02/ebp02_058.gd"
	},
	{
		"id": "EBP02-059",
		"name": "Godzillasaurus",
		"card_type": CardEnums.CardType.BATTLE,
		"rank": 3,
		"colors": [CardEnums.CardColor.GREEN],
		"traits": [CardEnums.CardTrait.GODZILLASAURUS],
		"counter_power": 2000,
		"invasion_icon": 1,
		"description": "<Revenge> You may discard 1 card from your hand, if you do, return 1 battle card named “Godzilla(1991)” from your discard pile to your hand. (Activates when destroyed by a card effect or monster card movement.)",
		"effect_script": "res://scripts/effects/ebp02/ebp02_059.gd"
	},
	{
		"id": "EBP02-060",
		"name": "Gigan(2004)",
		"card_type": CardEnums.CardType.BATTLE,
		"rank": 4,
		"colors": [CardEnums.CardColor.GREEN],
		"traits": [CardEnums.CardTrait.GIGAN, CardEnums.CardTrait.WEAPON, CardEnums.CardTrait.FINAL_WARS],
		"counter_power": 2000,
		"invasion_icon": 1,
		"description": "If this card is in the same column as your opponent's monster card, this card gains +3000 counter power.\n<Revenge> If your opponent's monster card is in zones 1–5, you may return this card from your discard pile to your hand. (Activates when destroyed by a card effect or monster card movement.)",
		"effect_script": "res://scripts/effects/ebp02/ebp02_060.gd"
	},
	{
		"id": "EBP02-061",
		"name": "Godzilla(1972)",
		"card_type": CardEnums.CardType.BATTLE,
		"rank": 4,
		"colors": [CardEnums.CardColor.GREEN],
		"traits": [CardEnums.CardTrait.GODZILLA],
		"counter_power": 4000,
		"invasion_icon": 2,
		"description": "If this card is in zone 8, this card gains +3000 counter power.",
		"effect_script": "res://scripts/effects/ebp02/ebp02_061.gd"
	},
	{
		"id": "EBP02-062",
		"name": "SpaceGodzilla",
		"card_type": CardEnums.CardType.BATTLE,
		"rank": 5,
		"colors": [CardEnums.CardColor.GREEN],
		"traits": [CardEnums.CardTrait.SPACEGODZILLA],
		"counter_power": 3000,
		"invasion_icon": 1,
		"description": "<Revenge> Return up to 1 <《SpaceGodzilla》> monster card from your discard pile to your hand. (Activates when destroyed by a card effect or monster card movement.)",
		"effect_script": "res://scripts/effects/ebp02/ebp02_062.gd"
	},
	{
		"id": "EBP02-063",
		"name": "Megalon",
		"card_type": CardEnums.CardType.BATTLE,
		"rank": 5,
		"colors": [CardEnums.CardColor.GREEN],
		"traits": [CardEnums.CardTrait.MEGALON],
		"counter_power": 5000,
		"invasion_icon": 1
	},
	{
		"id": "EBP02-064",
		"name": "Gigan(1972)",
		"card_type": CardEnums.CardType.BATTLE,
		"rank": 6,
		"colors": [CardEnums.CardColor.GREEN],
		"traits": [CardEnums.CardTrait.GIGAN, CardEnums.CardTrait.WEAPON],
		"counter_power": 3000,
		"invasion_icon": 1,
		"description": "If there is a card with <《King Ghidorah》> or <《Megalon》> in your zones, this card gains +3000 counter power.\n<Revenge> Return up to 1 <《King Ghidorah》> monster card from your discard pile to your hand. (Activates when destroyed by a card effect or monster movement.)",
		"effect_script": "res://scripts/effects/ebp02/ebp02_064.gd"
	},
	{
		"id": "EBP02-065",
		"name": "Godzilla(1991)",
		"card_type": CardEnums.CardType.BATTLE,
		"rank": 6,
		"colors": [CardEnums.CardColor.GREEN],
		"traits": [CardEnums.CardTrait.GODZILLA],
		"counter_power": 5000,
		"invasion_icon": 2,
		"description": "<Awakening6> If there are 3 or more cards under your monster card, this card gains +5000 counter power. If there are 5 or more, this card gains an additional +5000 counter power.",
		"effect_script": "res://scripts/effects/ebp02/ebp02_065.gd"
	},
	{
		"id": "EBP02-066",
		"name": "King Ghidorah(1964)",
		"card_type": CardEnums.CardType.BATTLE,
		"rank": 7,
		"colors": [CardEnums.CardColor.GREEN],
		"traits": [CardEnums.CardTrait.KING_GHIDORAH],
		"counter_power": 8000,
		"invasion_icon": 2,
		"description": "<Awakening6> This card gains +3000 counter power. (Active if your monster card is in zone 6 or beyond.)",
		"effect_script": "res://scripts/effects/ebp02/ebp02_066.gd"
	},
	{
		"id": "EBP02-067",
		"name": "M.O.G.U.E.R.A.",
		"card_type": CardEnums.CardType.BATTLE,
		"rank": 8,
		"colors": [CardEnums.CardColor.GREEN],
		"traits": [CardEnums.CardTrait.MOGUERA, CardEnums.CardTrait.WEAPON],
		"counter_power": 10000,
		"invasion_icon": 2,
		"description": "If your opponent has a <《Godzilla》> card in their zones, this card gains +5000 counter power.",
		"effect_script": "res://scripts/effects/ebp02/ebp02_067.gd"
	},
	{
		"id": "EBP02-068",
		"name": "Mecha-King Ghidorah",
		"card_type": CardEnums.CardType.BATTLE,
		"rank": 23,
		"colors": [CardEnums.CardColor.GREEN],
		"traits": [CardEnums.CardTrait.KING_GHIDORAH, CardEnums.CardTrait.TWENTY_THIRD_CENTURY],
		"counter_power": 7000,
		"invasion_icon": 1,
		"description": "You can play this card from your hand with its rank reduced by 2 for each non-rank 23 <《King Ghidorah》> card in your discard pile. (This card's rank returns to 23 after being played.)\nIf this card is in the same column as your opponent's monster card, they cannot invade, and this card gains +3000 counter power.",
		"effect_script": "res://scripts/effects/ebp02/ebp02_068.gd"
	},
	{
		"id": "EBP02-069",
		"name": "Godzilla vs. SpaceGodzilla",
		"card_type": CardEnums.CardType.STRATEGY,
		"rank": 1,
		"colors": [CardEnums.CardColor.GREEN],
		"invasion_icon": 1,
		"description": "Choose 2 of your opponent's battle cards in their zones and swap their positions.",
		"effect_script": "res://scripts/effects/ebp02/ebp02_069.gd"
	},
	{
		"id": "EBP02-070",
		"name": "Godzilla vs. SpaceGodzilla",
		"card_type": CardEnums.CardType.STRATEGY,
		"rank": 3,
		"colors": [CardEnums.CardColor.GREEN],
		"invasion_icon": 2,
		"effect_script": "res://scripts/effects/ebp02/ebp02_070.gd",
		"description": "<Opponent’s Turn> Your opponent cannot play strategy cards. (Does not destroy cards already in play.)\n<Opponent’s Turn> At the beginning of the main phase, your opponent may discard cards until they have 5 cards remaining in their hand. If they discard at least 1 card, <Destroy> this card."
	},
	{
		"id": "EBP02-071",
		"name": "Godzilla vs. King Ghidorah",
		"card_type": CardEnums.CardType.STRATEGY,
		"rank": 4,
		"colors": [CardEnums.CardColor.GREEN],
		"invasion_icon": 1,
		"description": "Choose one of the following:\n・ <Destroy> 3 of your opponent's rank 4 or lower battle cards.\n・ <Awakening6> <Destroy> 2 of your opponent's rank 6 or lower battle cards.\n・ <Awakening8> <Destroy> 1 of your opponent's battle cards.",
		"effect_script": "res://scripts/effects/ebp02/ebp02_071.gd"
	},
	{
		"id": "EBP02-072",
		"name": "God of Destruction's Counterattack",
		"card_type": CardEnums.CardType.STRATEGY,
		"rank": 5,
		"colors": [CardEnums.CardColor.GREEN],
		"invasion_icon": 1,
		"effect_script": "res://scripts/effects/ebp02/ebp02_072.gd",
		"description": "<Your Turn> If you have 3 or more “Crystals” in your zones, your total counter power is increased by 20,000."
	},
	{
		"id": "EBP02-073",
		"name": "Bloody Chainsaw",
		"card_type": CardEnums.CardType.STRATEGY,
		"rank": 6,
		"colors": [CardEnums.CardColor.GREEN],
		"invasion_icon": 1,
		"description": "<Your Turn> Whenever you play a battle card, <Destroy> all of your opponent's rank 6 or lower battle cards in the same column as that battle card.",
		"effect_script": "res://scripts/effects/ebp02/ebp02_073.gd"
	},
	{
		"id": "EBP02-074",
		"name": "Bite Attack",
		"card_type": CardEnums.CardType.STRATEGY,
		"rank": 7,
		"colors": [CardEnums.CardColor.GREEN],
		"invasion_icon": 1,
		"description": "Increase your monster card's <Rage> by 1 for each rank of your opponent's monster.",
		"effect_script": "res://scripts/effects/ebp02/ebp02_074.gd"
	},
	{
		"id": "EBP02-075",
		"name": "Chibi Mothra",
		"card_type": CardEnums.CardType.BATTLE,
		"rank": 3,
		"colors": [CardEnums.CardColor.WHITE],
		"traits": [CardEnums.CardTrait.CHIBI_GODZILLA_RAIDS_AGAIN, CardEnums.CardTrait.MOTHRA],
		"counter_power": 3000,
		"invasion_icon": 2,
		"description": "<Enter> If a card named “Chibi Mechagodzilla” is in your zones, reduce your opponent's <Rage> by 1.",
		"effect_script": "res://scripts/effects/ebp02/ebp02_075.gd"
	},
	{
		"id": "EBP02-076",
		"name": "Chibi Mechagodzilla",
		"card_type": CardEnums.CardType.BATTLE,
		"rank": 5,
		"colors": [CardEnums.CardColor.WHITE],
		"traits": [CardEnums.CardTrait.CHIBI_GODZILLA_RAIDS_AGAIN, CardEnums.CardTrait.MECHAGODZILLA, CardEnums.CardTrait.WEAPON],
		"counter_power": 3000,
		"invasion_icon": 1,
		"description": "If this card is in a zone adjacent to your monster card, this card gains +3000 counter power.",
		"effect_script": "res://scripts/effects/ebp02/ebp02_076.gd"
	},
	{
		"id": "EBP02-077",
		"name": "Chibi Godzilla",
		"card_type": CardEnums.CardType.BATTLE,
		"rank": 6,
		"colors": [CardEnums.CardColor.WHITE],
		"traits": [CardEnums.CardTrait.CHIBI_GODZILLA_RAIDS_AGAIN, CardEnums.CardTrait.GODZILLA],
		"counter_power": 5000,
		"invasion_icon": 1,
		"effect_script": "res://scripts/effects/ebp02/ebp02_077.gd",
		"description": "At the beginning of your main phase, send the top 2 cards of your deck to your discard pile.\nIf a <《Godzilla》> card was sent to your discard pile this way, <Destroy> this card and play a “Chibi Godzilla 2nd Form” token. (Tokens are prepared separately from your deck.)"
	},
	{
		"id": "EBP02-078",
		"name": "Mothra(imago)(2003)",
		"card_type": CardEnums.CardType.BATTLE,
		"rank": 7,
		"colors": [CardEnums.CardColor.WHITE],
		"traits": [CardEnums.CardTrait.MOTHRA],
		"counter_power": 7000,
		"invasion_icon": 1,
		"description": "<Enter> If this card is in the same column as your opponent's monster card, reveal the top 2 cards of your deck. Add all rank 5 or lower battle cards among them to your hand and send the rest into your discard pile.",
		"effect_script": "res://scripts/effects/ebp02/ebp02_078.gd"
	},
	{
		"id": "EBP02-079",
		"name": "Destructive Impulse",
		"card_type": CardEnums.CardType.STRATEGY,
		"rank": 4,
		"colors": [CardEnums.CardColor.WHITE],
		"invasion_icon": 1,
		"description": "Perform the following action based on how many zones your monster card advanced through invasion this turn:\n\n0 - <Destroy> all of your opponent's rank 2 or lower battle cards.\n1 - <Destroy> all of your opponent's rank 4 or lower battle cards.\n2 - <Destroy> all of your opponent's rank 6 or lower battle cards.",
		"effect_script": "res://scripts/effects/ebp02/ebp02_079.gd"
	},
	{
		"id": "EBP02-080",
		"name": "Joint Struggle",
		"card_type": CardEnums.CardType.STRATEGY,
		"rank": 6,
		"colors": [CardEnums.CardColor.WHITE],
		"invasion_icon": 1,
		"description": "Reveal the top 2 cards of your deck. If they differ in at least 1 trait, add them to your hand; otherwise, send them to the discard pile. (Example if one is <《Mech》> and the other is <《Mechagodzilla》> and <《Mech》> , you may add them to your hand.)",
		"effect_script": "res://scripts/effects/ebp02/ebp02_080.gd"
	},
	{
		"id": "EBP02-T01",
		"name": "Conductorless Train Bombers",
		"card_type": CardEnums.CardType.BATTLE,
		"rank": 2,
		"colors": [CardEnums.CardColor.RED],
		"traits": [CardEnums.CardTrait.TOKEN, CardEnums.CardTrait.WEAPON],
		"counter_power": 2000,
		"invasion_icon": 1,
		"effect_script": "res://scripts/effects/ebp02/ebp02_t01.gd",
		"description": "<Enter> Reduce your opponent's <Rage> by 1.\n(Tokens cannot be added to the deck. They are banished when removed from zones.)"
	},
	{
		"id": "EBP02-T02",
		"name": "Tentacles",
		"card_type": CardEnums.CardType.BATTLE,
		"rank": 2,
		"colors": [CardEnums.CardColor.BLUE],
		"traits": [CardEnums.CardTrait.TOKEN, CardEnums.CardTrait.BIOLLANTE],
		"counter_power": 3000,
		"invasion_icon": 1,
		"description": "(Tokens cannot be added to the deck. They are banished when removed from zones.)"
	},
	{
		"id": "EBP02-T03",
		"name": "Crystals",
		"card_type": CardEnums.CardType.BATTLE,
		"rank": 1,
		"colors": [CardEnums.CardColor.GREEN],
		"traits": [CardEnums.CardTrait.TOKEN, CardEnums.CardTrait.CRYSTAL],
		"counter_power": 0,
		"invasion_icon": 1,
		"effect_script": "res://scripts/effects/ebp02/ebp02_t03.gd",
		"description": "All of your <《SpaceGodzilla》> monster cards in your zones gain +1000 threat level.\n(Tokens cannot be added to the deck. They are banished when removed from zones.)"
	},
	{
		"id": "EBP02-T04",
		"name": "Chibi Godzilla 2nd Form",
		"card_type": CardEnums.CardType.BATTLE,
		"rank": 8,
		"colors": [CardEnums.CardColor.WHITE],
		"traits": [CardEnums.CardTrait.TOKEN, CardEnums.CardTrait.CHIBI_GODZILLA_RAIDS_AGAIN, CardEnums.CardTrait.GODZILLA],
		"counter_power": 10000,
		"invasion_icon": 1,
		"effect_script": "res://scripts/effects/ebp02/ebp02_t04.gd",
		"description": "At the beginning of your end phase, <Destroy> this card and play 1 battle card named “Chibi Godzilla” from your discard pile.\n(Tokens cannot be added to the deck. They are banished when removed from zones.)"
	},
]
