extends RefCounted
## EBP04: Booster Pack 04 — card data only, split verbatim from card_data.gd.

var CARDS: Array[Dictionary] = [
	{
		"id": "EBP04-001",
		"name": "Godzilla(2004)",
		"card_type": CardEnums.CardType.MONSTER,
		"rank": 1,
		"colors": [CardEnums.CardColor.RED],
		"traits": [CardEnums.CardTrait.GODZILLA],
		"threat_level": 4000,
		"invasion_icon": 1,
		"effect_script": "res://scripts/effects/ebp04/ebp04_001.gd",
		"description": "<Opponent’s Turn> At the beginning of the counter phase, if your opponent has no battle cards in the same column as this card, increase this card’s <Rage> by 1."
	},
	{
		"id": "EBP04-002",
		"name": "Godzilla(2004)",
		"card_type": CardEnums.CardType.MONSTER,
		"rank": 2,
		"colors": [CardEnums.CardColor.RED],
		"traits": [CardEnums.CardTrait.GODZILLA],
		"threat_level": 12000,
		"invasion_icon": 2,
		"effect_script": "res://scripts/effects/ebp04/ebp04_002.gd",
		"description": "Whenever an opponent’s battle card in the same column as this card is <Destroy>, if you have a rank 1 strategy card in play, your opponent discards cards until they have 2 cards remaining in their hand."
	},
	{
		"id": "EBP04-003",
		"name": "Godzilla(2004)",
		"card_type": CardEnums.CardType.MONSTER,
		"rank": 3,
		"colors": [CardEnums.CardColor.RED],
		"traits": [CardEnums.CardTrait.GODZILLA],
		"threat_level": 22000,
		"invasion_icon": 1,
		"effect_script": "res://scripts/effects/ebp04/ebp04_003.gd",
		"description": "<Burst 2> (You can play this card from rank II. If you do, send this card to your discard pile at the beginning of that turn’s end phase.)\n<Enter> If you have a rank 1 strategy card in play, <Destroy> 1 of your opponent’s rank 6 or lower battle cards."
	},
	{
		"id": "EBP04-004",
		"name": "Godzilla(2004)",
		"card_type": CardEnums.CardType.MONSTER,
		"rank": 3,
		"colors": [CardEnums.CardColor.RED],
		"traits": [CardEnums.CardTrait.GODZILLA],
		"threat_level": 23000,
		"invasion_icon": 1,
		"effect_script": "res://scripts/effects/ebp04/ebp04_004.gd",
		"description": "<Enter> If you have a rank 1 strategy card in play, increase this card’s <Rage> by 2."
	},
	{
		"id": "EBP04-005",
		"name": "Godzilla(2004)",
		"card_type": CardEnums.CardType.MONSTER,
		"rank": 4,
		"colors": [CardEnums.CardColor.RED],
		"traits": [CardEnums.CardTrait.GODZILLA],
		"threat_level": 33000,
		"invasion_icon": 2,
		"effect_script": "res://scripts/effects/ebp04/ebp04_005.gd",
		"description": "<Enter> If you have 1 or fewer strategy cards in play, search your deck for up to 1 rank 1 strategy card, put it into play, shuffle your deck, then activate it.\nWhenever an opponent’s battle card in the same column as this card is <Destroy>, if you have 3 or more rank 1 strategy cards in your discard pile, <Destroy> all of your opponent’s battle cards with rank equal to or lower than the rank of the card that was <Destroy> in the same column as this card."
	},
	{
		"id": "EBP04-006",
		"name": "Godzilla(2004)",
		"card_type": CardEnums.CardType.MONSTER,
		"rank": 4,
		"colors": [CardEnums.CardColor.RED],
		"traits": [CardEnums.CardTrait.GODZILLA],
		"threat_level": 38000,
		"invasion_icon": 1,
		"effect_script": "res://scripts/effects/ebp04/ebp04_006.gd",
		"description": "<Opponent’s Turn> If you have 3 or more rank 1 strategy cards in your discard pile, all of your opponent’s rank 5 or lower battle cards cannot engage with this card. (Their counter power is not included in the total during the counter phase.)"
	},
	{
		"id": "EBP04-007",
		"name": "Godzilla(1962)",
		"card_type": CardEnums.CardType.MONSTER,
		"rank": 4,
		"colors": [CardEnums.CardColor.RED],
		"traits": [CardEnums.CardTrait.GODZILLA],
		"threat_level": 37000,
		"invasion_icon": 1,
		"effect_script": "res://scripts/effects/ebp04/ebp04_007.gd",
		"description": "<Burst 3> (You can play this card from rank III. If you do, send this card to your discard pile at the beginning of that turn’s end phase.)\nWhen this card invades with <Step 1>, it advances 2 zones."
	},
	{
		"id": "EBP04-008",
		"name": "Godzilla(2001)",
		"card_type": CardEnums.CardType.MONSTER,
		"rank": 3,
		"colors": [CardEnums.CardColor.RED],
		"traits": [CardEnums.CardTrait.GODZILLA],
		"threat_level": 23000,
		"invasion_icon": 1,
		"effect_script": "res://scripts/effects/ebp04/ebp04_008.gd",
		"description": "<Burst 2> (You can play this card from rank II. If you do, send this card to your discard pile at the beginning of that turn’s end phase.)\n<Awakening 8> At the beginning of your counter phase, your opponent discards cards until they have 3 cards remaining in their hand. (Active if this card is in zone 8.)"
	},
	{
		"id": "EBP04-009",
		"name": "Godzilla(2016) 3rd Form",
		"card_type": CardEnums.CardType.MONSTER,
		"rank": 3,
		"colors": [CardEnums.CardColor.RED],
		"traits": [CardEnums.CardTrait.GODZILLA, CardEnums.CardTrait.THIRD_FORM],
		"threat_level": 25000,
		"invasion_icon": 2,
		"effect_script": "res://scripts/effects/ebp04/ebp04_009.gd",
		"description": "<Opponent’s Turn> At the beginning of the counter phase, you may discard 1 strategy card from your hand. If you do, <Destroy> all of your opponent’s rank 6 or lower battle cards in the same column as this card."
	},
	{
		"id": "EBP04-010",
		"name": "Godzilla(2023)",
		"card_type": CardEnums.CardType.MONSTER,
		"rank": 2,
		"colors": [CardEnums.CardColor.RED],
		"traits": [CardEnums.CardTrait.GODZILLA],
		"threat_level": 13000,
		"invasion_icon": 1,
		"effect_script": "res://scripts/effects/ebp04/ebp04_010.gd",
		"description": "When you would set this card’s <Rage> to 0 during your start phase, if this card has 2 or more <Rage>, you may discard 2 cards from your hand. If you do, set this card’s <Rage> to 2 instead."
	},
	{
		"id": "EBP04-011",
		"name": "Multi-purpose Fighting System-3",
		"card_type": CardEnums.CardType.MONSTER,
		"rank": 4,
		"colors": [CardEnums.CardColor.RED, CardEnums.CardColor.BLUE],
		"traits": [CardEnums.CardTrait.MECHAGODZILLA, CardEnums.CardTrait.WEAPON],
		"threat_level": 37000,
		"invasion_icon": 1,
		"effect_script": "res://scripts/effects/ebp04/ebp04_011.gd",
		"description": "If you have at least 1 red battle card and at least 1 blue battle card in your zones, this card gains +10,000 threat level."
	},
	{
		"id": "EBP04-012",
		"name": "Biollante Plant Beast Form",
		"card_type": CardEnums.CardType.MONSTER,
		"rank": 3,
		"colors": [CardEnums.CardColor.BLUE],
		"traits": [CardEnums.CardTrait.BIOLLANTE],
		"threat_level": 17000,
		"invasion_icon": 1,
		"effect_script": "res://scripts/effects/ebp04/ebp04_012.gd",
		"description": "You may play this card from your hand by placing 1 rank III card from your monster deck under one of your rank II  《Biollante》 monster cards. (You may play this card from rank II.)\n<Enter> Play “Tentacles” tokens in all zones adjacent to this card. (Tokens are prepared separately from your deck and must be played as many as possible. Maximum of 3.)"
	},
	{
		"id": "EBP04-013",
		"name": "Godzilla(2000)",
		"card_type": CardEnums.CardType.MONSTER,
		"rank": 3,
		"colors": [CardEnums.CardColor.BLUE],
		"traits": [CardEnums.CardTrait.GODZILLA],
		"threat_level": 24000,
		"invasion_icon": 2,
		"effect_script": "res://scripts/effects/ebp04/ebp04_013.gd",
		"description": "<Enter> If you have 5 or more monster cards in your discard pile, reveal the top 3 cards of your deck and send them to your discard pile. <Destroy> all battle cards in your opponent’s zones with numbers matching the ranks of the revealed cards, and retreat your opponent’s monster card in those zones backward by 1 zone."
	},
	{
		"id": "EBP04-014",
		"name": "Godzilla(2002)",
		"card_type": CardEnums.CardType.MONSTER,
		"rank": 2,
		"colors": [CardEnums.CardColor.BLUE],
		"traits": [CardEnums.CardTrait.GODZILLA],
		"threat_level": 10000,
		"invasion_icon": 1,
		"effect_script": "res://scripts/effects/ebp04/ebp04_014.gd",
		"description": "Whenever you discard a battle card from your hand, if your opponent’s <Rage> is 0, <Destroy> 1 of your opponent’s rank 4 or lower battle cards.\n<Opponent’s Turn> <Awakening 6> At the beginning of the counter phase, if you have 2 or more battle cards in your zones, you may discard 1 battle card from your hand. If you do, this card cannot be countered by 30,000 or lower counter power this turn. (It will not retreat.)"
	},
	{
		"id": "EBP04-015",
		"name": "Godzilla(2003)",
		"card_type": CardEnums.CardType.MONSTER,
		"rank": 4,
		"colors": [CardEnums.CardColor.BLUE],
		"traits": [CardEnums.CardTrait.GODZILLA],
		"threat_level": 36000,
		"invasion_icon": 1,
		"effect_script": "res://scripts/effects/ebp04/ebp04_015.gd",
		"description": "Whenever you discard a battle card from your hand, if your opponent’s <Rage> is 0, <Destroy> 1 of your opponent’s rank 6 or lower battle cards."
	},
	{
		"id": "EBP04-016",
		"name": "Godzilla(Fest GodzillaⅡ)",
		"card_type": CardEnums.CardType.MONSTER,
		"rank": 1,
		"colors": [CardEnums.CardColor.BLUE],
		"traits": [CardEnums.CardTrait.GODZILLA, CardEnums.CardTrait.FEST],
		"threat_level": 5000,
		"invasion_icon": 1,
		"effect_script": "res://scripts/effects/ebp04/ebp04_016.gd",
		"description": "If the number of the zone this card is in is equal to or greater than the number of the zone the opponent’s monster card is in, this card gains +3000 threat level."
	},
	{
		"id": "EBP04-017",
		"name": "Godzilla(Fest GodzillaⅡ)",
		"card_type": CardEnums.CardType.MONSTER,
		"rank": 2,
		"colors": [CardEnums.CardColor.BLUE],
		"traits": [CardEnums.CardTrait.GODZILLA, CardEnums.CardTrait.FEST],
		"threat_level": 13000,
		"invasion_icon": 1,
		"effect_script": "res://scripts/effects/ebp04/ebp04_017.gd",
		"description": "If the number of the zone this card is in is equal to or greater than the number of the zone the opponent’s monster card is in, increase your total counter power by +5000."
	},
	{
		"id": "EBP04-018",
		"name": "Godzilla(Fest GodzillaⅡ)",
		"card_type": CardEnums.CardType.MONSTER,
		"rank": 3,
		"colors": [CardEnums.CardColor.BLUE],
		"traits": [CardEnums.CardTrait.GODZILLA, CardEnums.CardTrait.FEST],
		"threat_level": 20000,
		"invasion_icon": 1,
		"effect_script": "res://scripts/effects/ebp04/ebp04_018.gd",
		"description": "<Enter> If you have 5 or more monster cards in your discard pile, <Destroy> 1 of your opponent’s rank 6 or lower battle cards.\nIf the number of the zone this card occupies is greater than or equal to the number of the zone the opponent’s monster card occupies, this card gains +10,000 threat level."
	},
	{
		"id": "EBP04-019",
		"name": "Godzilla(Fest GodzillaⅡ)",
		"card_type": CardEnums.CardType.MONSTER,
		"rank": 4,
		"colors": [CardEnums.CardColor.BLUE],
		"traits": [CardEnums.CardTrait.GODZILLA, CardEnums.CardTrait.FEST],
		"threat_level": 34000,
		"invasion_icon": 1,
		"effect_script": "res://scripts/effects/ebp04/ebp04_019.gd",
		"description": "If the number of the zone this card occupies is greater than or equal to the number of the zone the opponent’s monster card occupies, and you have 5 or more monster cards in your discard pile, this card gains +10,000 threat level, and your total counter power is increased by +10,000."
	},
	{
		"id": "EBP04-020",
		"name": "Aqua Mothra",
		"card_type": CardEnums.CardType.MONSTER,
		"rank": 4,
		"colors": [CardEnums.CardColor.BLUE, CardEnums.CardColor.GREEN],
		"traits": [CardEnums.CardTrait.MOTHRA],
		"threat_level": 38000,
		"invasion_icon": 2,
		"effect_script": "res://scripts/effects/ebp04/ebp04_020.gd",
		"description": "<Enter> If you have a <Base> in play, <Destroy> all of your opponent’s battle cards in zones adjacent to your opponent’s monster card."
	},
	{
		"id": "EBP04-021",
		"name": "Godzilla Aquatilis",
		"card_type": CardEnums.CardType.MONSTER,
		"rank": 1,
		"colors": [CardEnums.CardColor.GREEN],
		"traits": [CardEnums.CardTrait.GODZILLA],
		"threat_level": 5000,
		"invasion_icon": 1,
		"effect_script": "res://scripts/effects/ebp04/ebp04_021.gd",
		"description": "At the beginning of your counter phase, send the top card of your deck to your discard pile. If it is a green battle card, your opponent discards cards until they have 4 cards remaining in their hand."
	},
	{
		"id": "EBP04-022",
		"name": "Godzilla Amphibia",
		"card_type": CardEnums.CardType.MONSTER,
		"rank": 2,
		"colors": [CardEnums.CardColor.GREEN],
		"traits": [CardEnums.CardTrait.GODZILLA],
		"threat_level": 12000,
		"invasion_icon": 2,
		"effect_script": "res://scripts/effects/ebp04/ebp04_022.gd",
		"description": "When this card is countered, reveal the top 5 cards of your deck and send them to your discard pile. For each green battle card revealed this way, <Destroy> 1 of your opponent’s battle cards with 6000 or lower counter power in zones 1–5."
	},
	{
		"id": "EBP04-023",
		"name": "Godzilla Terrestris",
		"card_type": CardEnums.CardType.MONSTER,
		"rank": 3,
		"colors": [CardEnums.CardColor.GREEN],
		"traits": [CardEnums.CardTrait.GODZILLA],
		"threat_level": 17000,
		"invasion_icon": 1,
		"effect_script": "res://scripts/effects/ebp04/ebp04_023.gd",
		"description": "This card gains +10,000 threat level for each battle card your opponent has in the same column as this card."
	},
	{
		"id": "EBP04-024",
		"name": "Godzilla Ultima",
		"card_type": CardEnums.CardType.MONSTER,
		"rank": 4,
		"colors": [CardEnums.CardColor.GREEN],
		"traits": [CardEnums.CardTrait.GODZILLA],
		"threat_level": 26000,
		"invasion_icon": 1,
		"effect_script": "res://scripts/effects/ebp04/ebp04_024.gd",
		"description": "<Enter> If you have 10 or more green battle cards in your discard pile, you may <Destroy> any number of your opponent’s battle cards whose total ranks add up to 7 or less.\nThis card gains +1000 threat level for each green battle card in your discard pile."
	},
	{
		"id": "EBP04-025",
		"name": "Godzilla Ultima",
		"card_type": CardEnums.CardType.MONSTER,
		"rank": 4,
		"colors": [CardEnums.CardColor.GREEN],
		"traits": [CardEnums.CardTrait.GODZILLA],
		"threat_level": 37000,
		"invasion_icon": 1,
		"effect_script": "res://scripts/effects/ebp04/ebp04_025.gd",
		"description": "<Enter> <Destroy> 1 of your opponent’s strategy cards.\n<When Invading> If you have 10 or more green battle cards in your discard pile, your opponent discards cards until they have 3 cards remaining in their hand."
	},
	{
		"id": "EBP04-026",
		"name": "SpaceGodzilla",
		"card_type": CardEnums.CardType.MONSTER,
		"rank": 4,
		"colors": [CardEnums.CardColor.GREEN],
		"traits": [CardEnums.CardTrait.SPACEGODZILLA],
		"threat_level": 31000,
		"invasion_icon": 1,
		"effect_script": "res://scripts/effects/ebp04/ebp04_026.gd",
		"description": "<When Invading> Play 3 “Crystals” tokens. (Tokens are prepared separately from your deck.)\n<Awakening 6> If there are 3 or more “Crystals” in your zones, increase your total counter power by +10,000. (Active if this card is in zone 6 or beyond.)"
	},
	{
		"id": "EBP04-027",
		"name": "Gigan(2004)",
		"card_type": CardEnums.CardType.MONSTER,
		"rank": 1,
		"colors": [CardEnums.CardColor.GREEN],
		"traits": [CardEnums.CardTrait.GIGAN, CardEnums.CardTrait.WEAPON],
		"threat_level": 1,
		"invasion_icon": 1,
		"effect_script": "res://scripts/effects/ebp04/ebp04_027.gd",
		"description": "This card cannot advance nor invade.\n<Your Turn> At the beginning of your main phase, you may discard 1 card with <Step 2> from your hand. If you do, counter this card.\n<Opponent’s Turn> At the beginning of the main phase, your opponent may discard 1 card with <Step 2> from their hand. If they do, counter this card."
	},
	{
		"id": "EBP04-028",
		"name": "Gigan(2004)",
		"card_type": CardEnums.CardType.MONSTER,
		"rank": 2,
		"colors": [CardEnums.CardColor.GREEN],
		"traits": [CardEnums.CardTrait.GIGAN, CardEnums.CardTrait.WEAPON],
		"threat_level": 13000,
		"invasion_icon": 1,
		"effect_script": "res://scripts/effects/ebp04/ebp04_028.gd",
		"description": "<Opponent’s Turn> All strategy cards in your opponent’s hand gain +3 rank. (They return to their original rank after being played.)\n<Opponent’s Turn> Whenever your opponent plays a battle card from their deck, your opponent discards 1 card from their hand."
	},
	{
		"id": "EBP04-029",
		"name": "Gigan(2004)",
		"card_type": CardEnums.CardType.MONSTER,
		"rank": 3,
		"colors": [CardEnums.CardColor.GREEN],
		"traits": [CardEnums.CardTrait.GIGAN, CardEnums.CardTrait.WEAPON],
		"threat_level": 22000,
		"invasion_icon": 1,
		"effect_script": "res://scripts/effects/ebp04/ebp04_029.gd",
		"description": "Your opponent cannot discard cards with <Step 1> from their hand for invade actions.\n<Enter> If your opponent’s monster card is in zones 1–5, you may return up to 1 《Gigan》 monster card from your discard pile to your hand."
	},
	{
		"id": "EBP04-030",
		"name": "Modified Gigan",
		"card_type": CardEnums.CardType.MONSTER,
		"rank": 4,
		"colors": [CardEnums.CardColor.GREEN],
		"traits": [CardEnums.CardTrait.GIGAN, CardEnums.CardTrait.WEAPON],
		"threat_level": 33000,
		"invasion_icon": 1,
		"effect_script": "res://scripts/effects/ebp04/ebp04_030.gd",
		"description": "<Opponent’s Turn> During the end phase, your opponent cannot draw cards.\n<Enter> <Destroy> 1 of your opponent’s battle cards in zones 1–5."
	},
	{
		"id": "EBP04-031",
		"name": "Monster X",
		"card_type": CardEnums.CardType.MONSTER,
		"rank": 1,
		"colors": [CardEnums.CardColor.RED, CardEnums.CardColor.BLUE, CardEnums.CardColor.GREEN],
		"traits": [CardEnums.CardTrait.MONSTER_X, CardEnums.CardTrait.FINAL_WARS],
		"threat_level": 0,
		"invasion_icon": 1,
		"effect_script": "res://scripts/effects/ebp04/ebp04_031.gd",
		"resonance": {
			"main_battle_required_traits": [CardEnums.CardTrait.FINAL_WARS],
		},
		"description": "This card’s threat level X is equal to 3000 times the number of different colors among battle cards in your zones. If your opponent’s zones have 1 or fewer battle cards, this card cannot be countered.\n<Resonance> Red/Blue/Green\n・Battle cards must be 《Final Wars》 only.\n(Red, blue, green, and white may be mixed, but your monster deck and main deck must be constructed to satisfy the above conditions.)"
	},
	{
		"id": "EBP04-032",
		"name": "Monster X",
		"card_type": CardEnums.CardType.MONSTER,
		"rank": 2,
		"colors": [CardEnums.CardColor.RED, CardEnums.CardColor.BLUE, CardEnums.CardColor.GREEN],
		"traits": [CardEnums.CardTrait.MONSTER_X, CardEnums.CardTrait.FINAL_WARS],
		"threat_level": 0,
		"invasion_icon": 1,
		"effect_script": "res://scripts/effects/ebp04/ebp04_032.gd",
		"resonance": {
			"main_battle_required_traits": [CardEnums.CardTrait.FINAL_WARS],
		},
		"description": "This card’s threat level X is equal to 10,000 times the number of different colors among battle cards in your zones. If your opponent’s zones have 1 or fewer battle cards, this card cannot be countered."
	},
	{
		"id": "EBP04-033",
		"name": "Kaizer Ghidorah",
		"card_type": CardEnums.CardType.MONSTER,
		"rank": 3,
		"colors": [CardEnums.CardColor.RED, CardEnums.CardColor.BLUE, CardEnums.CardColor.GREEN],
		"traits": [CardEnums.CardTrait.KAISER_GHIDORAH],
		"threat_level": 23000,
		"invasion_icon": 1,
		"effect_script": "res://scripts/effects/ebp04/ebp04_033.gd",
		"description": "This card can be played by placing it on top of a monster card with 《Monster X》 in your zones.\n<Enter> If there are 3 or more different colors among battle cards in your discard pile, reduce your opponent’s <Rage> by 1."
	},
	{
		"id": "EBP04-034",
		"name": "Kaizer Ghidorah",
		"card_type": CardEnums.CardType.MONSTER,
		"rank": 3,
		"colors": [CardEnums.CardColor.RED, CardEnums.CardColor.BLUE, CardEnums.CardColor.GREEN],
		"traits": [CardEnums.CardTrait.KAISER_GHIDORAH],
		"threat_level": 24000,
		"invasion_icon": 1,
		"effect_script": "res://scripts/effects/ebp04/ebp04_034.gd",
		"description": "This card can be played by placing it on top of a monster card with 《Monster X》 in your zones.\n<Enter> If there are 3 or more different colors among battle cards in your discard pile, <Destroy> 1 of your opponent’s rank 5 or lower battle cards."
	},
	{
		"id": "EBP04-035",
		"name": "Kaizer Ghidorah",
		"card_type": CardEnums.CardType.MONSTER,
		"rank": 4,
		"colors": [CardEnums.CardColor.RED, CardEnums.CardColor.BLUE, CardEnums.CardColor.GREEN],
		"traits": [CardEnums.CardTrait.KAISER_GHIDORAH],
		"threat_level": 30000,
		"invasion_icon": 1,
		"effect_script": "res://scripts/effects/ebp04/ebp04_035.gd",
		"description": "<Enter> Starting with the battle card in your opponent’s zone with the lowest number, <Destroy> battle cards one by one up to the number of different colors among battle cards in your discard pile."
	},
	{
		"id": "EBP04-036",
		"name": "Kaizer Ghidorah",
		"card_type": CardEnums.CardType.MONSTER,
		"rank": 4,
		"colors": [CardEnums.CardColor.RED, CardEnums.CardColor.BLUE, CardEnums.CardColor.GREEN],
		"traits": [CardEnums.CardTrait.KAISER_GHIDORAH],
		"threat_level": 30000,
		"invasion_icon": 2,
		"effect_script": "res://scripts/effects/ebp04/ebp04_036.gd",
		"description": "For each different color among battle cards in your discard pile, this card gains +5000 threat level."
	},
	{
		"id": "EBP04-037",
		"name": "Minilla(2004)",
		"card_type": CardEnums.CardType.BATTLE,
		"rank": 3,
		"colors": [CardEnums.CardColor.RED],
		"traits": [CardEnums.CardTrait.MINILLA, CardEnums.CardTrait.FINAL_WARS],
		"counter_power": 2000,
		"invasion_icon": 1,
		"effect_script": "res://scripts/effects/ebp04/ebp04_037.gd",
		"description": "If you have a rank 1 strategy card in play, this card gains +3000 counter power."
	},
	{
		"id": "EBP04-038",
		"name": "Kamacuras(2004)",
		"card_type": CardEnums.CardType.BATTLE,
		"rank": 3,
		"colors": [CardEnums.CardColor.RED],
		"traits": [CardEnums.CardTrait.KAMACURAS, CardEnums.CardTrait.FINAL_WARS],
		"counter_power": 2000,
		"invasion_icon": 2,
		"effect_script": "res://scripts/effects/ebp04/ebp04_038.gd",
		"description": "If you have 2 or more other battle cards in your zones, this card gains +3000 counter power."
	},
	{
		"id": "EBP04-039",
		"name": "Zilla",
		"card_type": CardEnums.CardType.BATTLE,
		"rank": 4,
		"colors": [CardEnums.CardColor.RED],
		"traits": [CardEnums.CardTrait.ZILLA, CardEnums.CardTrait.FINAL_WARS],
		"counter_power": 3000,
		"invasion_icon": 1,
		"effect_script": "res://scripts/effects/ebp04/ebp04_039.gd",
		"description": "<Opponent’s Turn> Whenever one of your non-red battle cards is <Destroy>, move this card to a zone adjacent to your monster card."
	},
	{
		"id": "EBP04-040",
		"name": "Anguirus(2004)",
		"card_type": CardEnums.CardType.BATTLE,
		"rank": 5,
		"colors": [CardEnums.CardColor.RED],
		"traits": [CardEnums.CardTrait.ANGUIRUS, CardEnums.CardTrait.FINAL_WARS],
		"counter_power": 3000,
		"invasion_icon": 1,
		"effect_script": "res://scripts/effects/ebp04/ebp04_040.gd",
		"description": "<Awakening 6> <Enter> If you have at least 1 《Rodan》 battle card and at least 1 《King Caesar》 battle card in your zones, increase your monster card’s <Rage> by 3. (Active if your monster card is in zone 6 or beyond.)"
	},
	{
		"id": "EBP04-041",
		"name": "The New Gotengo",
		"card_type": CardEnums.CardType.BATTLE,
		"rank": 5,
		"colors": [CardEnums.CardColor.RED],
		"traits": [CardEnums.CardTrait.WEAPON, CardEnums.CardTrait.FINAL_WARS],
		"counter_power": 4000,
		"invasion_icon": 2,
		"effect_script": "res://scripts/effects/ebp04/ebp04_041.gd",
		"description": "At the beginning of your counter phase, if this card is in zone 8, trigger all <Enter> abilities of your monster card.\n<Awakening 6> This card gains +3000 counter power. (Active if your monster card is in zone 6 or beyond.)"
	},
	{
		"id": "EBP04-042",
		"name": "Mothra(imago)(2004)",
		"card_type": CardEnums.CardType.BATTLE,
		"rank": 7,
		"colors": [CardEnums.CardColor.RED],
		"traits": [CardEnums.CardTrait.MOTHRA, CardEnums.CardTrait.FINAL_WARS],
		"counter_power": 7000,
		"invasion_icon": 1,
		"effect_script": "res://scripts/effects/ebp04/ebp04_042.gd",
		"description": "<Enter> If you have 3 or more rank 1 strategy cards in your discard pile, reduce your opponent’s <Rage> by 1."
	},
	{
		"id": "EBP04-043",
		"name": "Multi-purpose Fighting System-3",
		"card_type": CardEnums.CardType.BATTLE,
		"rank": 7,
		"colors": [CardEnums.CardColor.RED],
		"traits": [CardEnums.CardTrait.MECHAGODZILLA, CardEnums.CardTrait.WEAPON],
		"counter_power": 7000,
		"invasion_icon": 1,
		"effect_script": "res://scripts/effects/ebp04/ebp04_043.gd",
		"description": "At the beginning of your counter phase, you may place a card with 1 <Step 2> from your strategy zone under this card.\nIf there is a card under this card, this card gains +10,000 counter power."
	},
	{
		"id": "EBP04-044",
		"name": "Hedorah(2004)",
		"card_type": CardEnums.CardType.BATTLE,
		"rank": 8,
		"colors": [CardEnums.CardColor.RED],
		"traits": [CardEnums.CardTrait.HEDORAH, CardEnums.CardTrait.FINAL_WARS],
		"counter_power": 7000,
		"invasion_icon": 1,
		"effect_script": "res://scripts/effects/ebp04/ebp04_044.gd",
		"description": "<Awakening 4> You can play this card from your hand with its rank reduced by 2 for each non-red battle card in your zones. (Active if your monster card is in zone 4 or beyond. After being played, this card is rank 8.)"
	},
	{
		"id": "EBP04-045",
		"name": "Manda(2004)",
		"card_type": CardEnums.CardType.BATTLE,
		"rank": 3,
		"colors": [CardEnums.CardColor.BLUE],
		"traits": [CardEnums.CardTrait.MANDA, CardEnums.CardTrait.FINAL_WARS],
		"counter_power": 2000,
		"invasion_icon": 1,
		"effect_script": "res://scripts/effects/ebp04/ebp04_045.gd",
		"description": "When playing this card from your hand, you may discard 1 non-blue battle card from your hand to play this card with its rank reduced by 2. (After being played, this card is rank 3.)"
	},
	{
		"id": "EBP04-046",
		"name": "Rodan(2004)",
		"card_type": CardEnums.CardType.BATTLE,
		"rank": 4,
		"colors": [CardEnums.CardColor.BLUE],
		"traits": [CardEnums.CardTrait.RODAN, CardEnums.CardTrait.FINAL_WARS],
		"counter_power": 2000,
		"invasion_icon": 1,
		"effect_script": "res://scripts/effects/ebp04/ebp04_046.gd",
		"description": "When this card is discarded from your hand by your opponent’s effect, you may play this card.\n<Awakening 6> This card gains +3000 counter power. (Active if your monster card is in zone 6 or beyond.)"
	},
	{
		"id": "EBP04-047",
		"name": "Monster X",
		"card_type": CardEnums.CardType.BATTLE,
		"rank": 5,
		"colors": [CardEnums.CardColor.BLUE],
		"traits": [CardEnums.CardTrait.MONSTER_X, CardEnums.CardTrait.FINAL_WARS],
		"counter_power": 0,
		"invasion_icon": 2,
		"evolution_rank": 8,
		"evolution_trait": CardEnums.CardTrait.KAISER_GHIDORAH,
		"effect_script": "res://scripts/effects/ebp04/ebp04_047.gd",
		"description": "This card’s counter power X is equal to 3000 multiplied by the number of different colors among other battle cards in your zones. (White also counts as a color.)\n<Evolution 8> 《Kaizer Ghidorah》 (At the beginning of your main phase, you may play a rank 8 or lower 《Kaizer Ghidorah》 battle card from your deck by placing it on top of this card.)"
	},
	{
		"id": "EBP04-048",
		"name": "Little Godzilla",
		"card_type": CardEnums.CardType.BATTLE,
		"rank": 5,
		"colors": [CardEnums.CardColor.BLUE],
		"traits": [CardEnums.CardTrait.LITTLE_GODZILLA],
		"counter_power": 4000,
		"invasion_icon": 1,
		"effect_script": "res://scripts/effects/ebp04/ebp04_048.gd",
		"description": "Your strategy cards in play cannot be <Destroy> by your opponent’s effects."
	},
	{
		"id": "EBP04-049",
		"name": "Ebirah(2004)",
		"card_type": CardEnums.CardType.BATTLE,
		"rank": 5,
		"colors": [CardEnums.CardColor.BLUE],
		"traits": [CardEnums.CardTrait.EBIRAH, CardEnums.CardTrait.FINAL_WARS],
		"counter_power": 6000,
		"invasion_icon": 2,
		"effect_script": "res://scripts/effects/ebp04/ebp04_049.gd",
		"description": "At the beginning of your counter phase, if you have a rank 8 or higher battle card in your zones, reveal the top card of your deck and send it to your discard pile. If the revealed card is blue, <Destroy> 1 of your rank 8 or higher battle cards. If it is not blue, reduce your opponent’s <Rage> by 2."
	},
	{
		"id": "EBP04-050",
		"name": "Battra(larva)",
		"card_type": CardEnums.CardType.BATTLE,
		"rank": 6,
		"colors": [CardEnums.CardColor.BLUE],
		"traits": [CardEnums.CardTrait.BATTRA],
		"counter_power": 5000,
		"invasion_icon": 1,
		"effect_script": "res://scripts/effects/ebp04/ebp04_050.gd",
		"description": "Whenever your monster card invades, if this card is in zone 8, choose one:\n・Draw 1 card, then discard 1 card.\n・Discard 1 card from your hand. If you do, reduce your opponent’s <Rage> by 1."
	},
	{
		"id": "EBP04-051",
		"name": "Super Mechagodzilla",
		"card_type": CardEnums.CardType.BATTLE,
		"rank": 6,
		"colors": [CardEnums.CardColor.BLUE],
		"traits": [CardEnums.CardTrait.MECHAGODZILLA, CardEnums.CardTrait.WEAPON],
		"counter_power": 5000,
		"invasion_icon": 1,
		"effect_script": "res://scripts/effects/ebp04/ebp04_051.gd",
		"description": "<Enter> If this card is in the same column as your opponent’s monster card, retreat 1 of your opponent’s monster cards with 30,000 or lower threat level backward by 1 zone."
	},
	{
		"id": "EBP04-052",
		"name": "Mothra(imago)(1992)",
		"card_type": CardEnums.CardType.BATTLE,
		"rank": 7,
		"colors": [CardEnums.CardColor.BLUE],
		"traits": [CardEnums.CardTrait.MOTHRA],
		"counter_power": 4000,
		"invasion_icon": 1,
		"effect_script": "res://scripts/effects/ebp04/ebp04_052.gd",
		"description": "When this card is discarded from your hand by your opponent’s effect, if your opponent’s monster card is in zones 4–8, you may play this card.\nWhenever your opponent’s effect causes you to discard cards from your hand, if this card is in zone 8, increase your monster card’s <Rage> by 2."
	},
	{
		"id": "EBP04-053",
		"name": "M.O.G.U.E.R.A.",
		"card_type": CardEnums.CardType.BATTLE,
		"rank": 7,
		"colors": [CardEnums.CardColor.BLUE],
		"traits": [CardEnums.CardTrait.MOGUERA, CardEnums.CardTrait.WEAPON],
		"counter_power": 7000,
		"invasion_icon": 1,
		"effect_script": "res://scripts/effects/ebp04/ebp04_053.gd",
		"description": "<Enter> Choose 2 battle cards in your zones: you may swap their positions."
	},
	{
		"id": "EBP04-054",
		"name": "Destoroyah Perfect Form",
		"card_type": CardEnums.CardType.BATTLE,
		"rank": 8,
		"colors": [CardEnums.CardColor.BLUE],
		"traits": [CardEnums.CardTrait.DESTOROYAH, CardEnums.CardTrait.FOURTH_FORM],
		"counter_power": 10000,
		"invasion_icon": 1,
		"effect_script": "res://scripts/effects/ebp04/ebp04_054.gd",
		"description": "For each strategy card you have in play, this card gains +5000 counter power.\nFor each strategy card your opponent has in play, this card gets −5000 counter power."
	},
	{
		"id": "EBP04-055",
		"name": "Void Ghidorah",
		"card_type": CardEnums.CardType.BATTLE,
		"rank": 1,
		"colors": [CardEnums.CardColor.GREEN],
		"traits": [CardEnums.CardTrait.GHIDORAH, CardEnums.CardTrait.HIGHER_DIMENSIONAL],
		"counter_power": 15000,
		"invasion_icon": 1,
		"effect_script": "res://scripts/effects/ebp04/ebp04_055.gd",
		"description": "<Enter> You may <Destroy> 4 of your other green battle cards in your zones. If you do not, <Destroy> this card."
	},
	{
		"id": "EBP04-056",
		"name": "Kumonga(2004)",
		"card_type": CardEnums.CardType.BATTLE,
		"rank": 2,
		"colors": [CardEnums.CardColor.GREEN],
		"traits": [CardEnums.CardTrait.KUMONGA, CardEnums.CardTrait.FINAL_WARS],
		"counter_power": 2000,
		"invasion_icon": 2,
		"effect_script": "res://scripts/effects/ebp04/ebp04_056.gd",
		"description": "If this card is in the same column as your opponent’s monster card and your opponent’s <Rage> is 0, your opponent cannot invade."
	},
	{
		"id": "EBP04-057",
		"name": "King Caesar(2004)",
		"card_type": CardEnums.CardType.BATTLE,
		"rank": 3,
		"colors": [CardEnums.CardColor.GREEN],
		"traits": [CardEnums.CardTrait.KING_CAESAR, CardEnums.CardTrait.FINAL_WARS],
		"counter_power": 2000,
		"invasion_icon": 1,
		"effect_script": "res://scripts/effects/ebp04/ebp04_057.gd",
		"description": "If you have any non-green battle cards in your zones, this card gains +3000 counter power."
	},
	{
		"id": "EBP04-058",
		"name": "Servum",
		"card_type": CardEnums.CardType.BATTLE,
		"rank": 3,
		"colors": [CardEnums.CardColor.GREEN],
		"traits": [CardEnums.CardTrait.SERVUM],
		"counter_power": 2000,
		"invasion_icon": 1,
		"effect_script": "res://scripts/effects/ebp04/ebp04_058.gd",
		"description": "<Awakening 4> If this card is in a zone adjacent to your monster card, this card gains +3000 counter power. (Active if your monster card is in zone 4 or beyond.)"
	},
	{
		"id": "EBP04-059",
		"name": "Rodan(2021)",
		"card_type": CardEnums.CardType.BATTLE,
		"rank": 4,
		"colors": [CardEnums.CardColor.GREEN],
		"traits": [CardEnums.CardTrait.RODAN],
		"counter_power": 1000,
		"invasion_icon": 1,
		"unlimited_copies": true,
		"effect_script": "res://scripts/effects/ebp04/ebp04_059.gd",
		"description": "You may have any number of this card in your deck.\n<Revenge> If you have 5 or more green battle cards in your discard pile, you may return up to 1 battle card with 《Rodan》 from your discard pile to your hand. (Activates when destroyed by a card effect or monster card movement. You may target this card to be returned to your hand.)"
	},
	{
		"id": "EBP04-060",
		"name": "Vulture",
		"card_type": CardEnums.CardType.BATTLE,
		"rank": 4,
		"colors": [CardEnums.CardColor.GREEN],
		"traits": [CardEnums.CardTrait.VALKYRIE, CardEnums.CardTrait.WEAPON],
		"counter_power": 3000,
		"invasion_icon": 1,
		"effect_script": "res://scripts/effects/ebp04/ebp04_060.gd",
		"description": "If you have a card named “Mechagodzilla City” in play, this card gains +3000 counter power."
	},
	{
		"id": "EBP04-061",
		"name": "Mechagodzilla(2018)",
		"card_type": CardEnums.CardType.BATTLE,
		"rank": 5,
		"colors": [CardEnums.CardColor.GREEN],
		"traits": [CardEnums.CardTrait.MECHAGODZILLA, CardEnums.CardTrait.WEAPON],
		"counter_power": 3000,
		"invasion_icon": 1,
		"effect_script": "res://scripts/effects/ebp04/ebp04_061.gd",
		"description": "<Enter> If you have 4 or more other green battle cards in your zones, search your deck for up to 1 green card, send it to your discard pile, then shuffle your deck."
	},
	{
		"id": "EBP04-062",
		"name": "Anguirus(2021)",
		"card_type": CardEnums.CardType.BATTLE,
		"rank": 5,
		"colors": [CardEnums.CardColor.GREEN],
		"traits": [CardEnums.CardTrait.ANGUIRUS],
		"counter_power": 4000,
		"invasion_icon": 1,
		"effect_script": "res://scripts/effects/ebp04/ebp04_062.gd",
		"description": "<Revenge> If you have 10 or more green battle cards in your discard pile, increase your monster card’s <Rage> by 1 for each opponent’s battle card in the same column as your monster card."
	},
	{
		"id": "EBP04-063",
		"name": "Godzilla Filius",
		"card_type": CardEnums.CardType.BATTLE,
		"rank": 5,
		"colors": [CardEnums.CardColor.GREEN],
		"traits": [CardEnums.CardTrait.GODZILLA],
		"counter_power": 4000,
		"invasion_icon": 1,
		"effect_script": "res://scripts/effects/ebp04/ebp04_063.gd",
		"description": "<Revenge> Return up to 1 battle card named \"Godzilla Earth\" from your discard pile to your hand. (Activates when destroyed by a card effect or monster card movement.)"
	},
	{
		"id": "EBP04-064",
		"name": "Jet Jaguar(2021)",
		"card_type": CardEnums.CardType.BATTLE,
		"rank": 6,
		"colors": [CardEnums.CardColor.GREEN],
		"traits": [CardEnums.CardTrait.JET_JAGUAR, CardEnums.CardTrait.MECH],
		"counter_power": 5000,
		"invasion_icon": 1,
		"effect_script": "res://scripts/effects/ebp04/ebp04_064.gd",
		"description": "At the beginning of your counter phase, if you have 10 or more green battle cards in your discard pile, you may <Destroy> this card. If you do, reduce your opponent’s <Rage> by 3."
	},
	{
		"id": "EBP04-065",
		"name": "Godzilla Earth",
		"card_type": CardEnums.CardType.BATTLE,
		"rank": 6,
		"colors": [CardEnums.CardColor.GREEN],
		"traits": [CardEnums.CardTrait.GODZILLA, CardEnums.CardTrait.GODZILLA_EARTH],
		"counter_power": 5000,
		"invasion_icon": 1,
		"effect_script": "res://scripts/effects/ebp04/ebp04_065.gd",
		"description": "If this card is in the same column as your opponent’s monster card, this card gains +3000 counter power."
	},
	{
		"id": "EBP04-066",
		"name": "Gigan(2004)",
		"card_type": CardEnums.CardType.BATTLE,
		"rank": 7,
		"colors": [CardEnums.CardColor.GREEN],
		"traits": [CardEnums.CardTrait.GIGAN, CardEnums.CardTrait.WEAPON, CardEnums.CardTrait.FINAL_WARS],
		"counter_power": 5000,
		"invasion_icon": 2,
		"effect_script": "res://scripts/effects/ebp04/ebp04_066.gd",
		"description": "<Opponent’s Turn> If you have any non-green battle cards in your zones, all strategy cards in your opponent’s hand gain +2 rank. (They return to their original rank after being played.)"
	},
	{
		"id": "EBP04-067",
		"name": "Godzilla Earth",
		"card_type": CardEnums.CardType.BATTLE,
		"rank": 7,
		"colors": [CardEnums.CardColor.GREEN],
		"traits": [CardEnums.CardTrait.GODZILLA, CardEnums.CardTrait.GODZILLA_EARTH],
		"counter_power": 9000,
		"invasion_icon": 2,
		"effect_script": "res://scripts/effects/ebp04/ebp04_067.gd",
		"description": "This card can only be played in zone 8.\n<Enter> Play 1 “Godzilla Earth” token in your zone 3.\nIf either this card or that token leave their zone or move, <Destroy> both of them."
	},
	{
		"id": "EBP04-068",
		"name": "Kaizer Ghidorah",
		"card_type": CardEnums.CardType.BATTLE,
		"rank": 8,
		"colors": [CardEnums.CardColor.GREEN],
		"traits": [CardEnums.CardTrait.KAISER_GHIDORAH, CardEnums.CardTrait.FINAL_WARS],
		"counter_power": 11000,
		"invasion_icon": 1,
		"effect_script": "res://scripts/effects/ebp04/ebp04_068.gd",
		"description": "<Your Turn> If you have no strategy cards in play, all strategy cards in your hand gain −1 rank for each different color among battle cards in your discard pile. (They return to their original rank after being played.)"
	},
	{
		"id": "EBP04-069",
		"name": "Gezora",
		"card_type": CardEnums.CardType.BATTLE,
		"rank": 3,
		"colors": [CardEnums.CardColor.WHITE],
		"traits": [CardEnums.CardTrait.GEZORA],
		"counter_power": 2000,
		"invasion_icon": 1,
		"effect_script": "res://scripts/effects/ebp04/ebp04_069.gd",
		"description": "<Awakening 4> If this card is in the same column as your opponent’s blue monster card, this card gains +5000 counter power. (Active if your monster card is in zone 4 or beyond.)"
	},
	{
		"id": "EBP04-070",
		"name": "Ganimes",
		"card_type": CardEnums.CardType.BATTLE,
		"rank": 4,
		"colors": [CardEnums.CardColor.WHITE],
		"traits": [CardEnums.CardTrait.GANIMES],
		"counter_power": 3000,
		"invasion_icon": 1,
		"effect_script": "res://scripts/effects/ebp04/ebp04_070.gd",
		"description": "<Awakening 4> If this card is in the same column as your opponent’s green monster card, this card gains +5000 counter power. (Active if your monster card is in zone 4 or beyond.)"
	},
	{
		"id": "EBP04-071",
		"name": "Kamoebas(1970)",
		"card_type": CardEnums.CardType.BATTLE,
		"rank": 5,
		"colors": [CardEnums.CardColor.WHITE],
		"traits": [CardEnums.CardTrait.KAMOEBAS],
		"counter_power": 4000,
		"invasion_icon": 1,
		"effect_script": "res://scripts/effects/ebp04/ebp04_071.gd",
		"description": "<Awakening 4> If this card is in the same column as your opponent’s red monster card, this card gains +5000 counter power. (Active if your monster card is in zone 4 or beyond.)"
	},
	{
		"id": "EBP04-072",
		"name": "Sanda",
		"card_type": CardEnums.CardType.BATTLE,
		"rank": 5,
		"colors": [CardEnums.CardColor.WHITE],
		"traits": [CardEnums.CardTrait.SANDA],
		"counter_power": 4000,
		"invasion_icon": 1,
		"effect_script": "res://scripts/effects/ebp04/ebp04_072.gd",
		"description": "<Opponent’s Turn> Whenever your opponent plays a battle card from their deck, if this card is in zone 5, you may search your deck for up to 1 card, add it to your hand, then shuffle your deck."
	},
	{
		"id": "EBP04-073",
		"name": "Gaira",
		"card_type": CardEnums.CardType.BATTLE,
		"rank": 5,
		"colors": [CardEnums.CardColor.WHITE],
		"traits": [CardEnums.CardTrait.GAIRA],
		"counter_power": 4000,
		"invasion_icon": 1,
		"effect_script": "res://scripts/effects/ebp04/ebp04_073.gd",
		"description": "<Opponent’s Turn> Whenever your opponent returns a card from their discard pile to their hand, if this card is in zone 1, you may return up to 1 card from your discard pile to your hand."
	},
	{
		"id": "EBP04-074",
		"name": "Rodan(1956)",
		"card_type": CardEnums.CardType.BATTLE,
		"rank": 6,
		"colors": [CardEnums.CardColor.WHITE],
		"traits": [CardEnums.CardTrait.RODAN],
		"counter_power": 5000,
		"invasion_icon": 2,
		"effect_script": "res://scripts/effects/ebp04/ebp04_074.gd",
		"description": "<Enter> <Destroy> 1 of your opponent’s strategy cards."
	},
	{
		"id": "EBP04-075",
		"name": "Spiral heat ray",
		"card_type": CardEnums.CardType.STRATEGY,
		"rank": 1,
		"colors": [CardEnums.CardColor.RED],
		"invasion_icon": 1,
		"effect_script": "res://scripts/effects/ebp04/ebp04_075.gd",
		"description": "<Opponent’s Turn> At the beginning of the counter phase, send the top card of your deck to your discard pile. If it is a monster card, <Destroy> 1 of your opponent’s battle cards in the same column as your monster card."
	},
	{
		"id": "EBP04-076",
		"name": "Godzilla's Dormancy",
		"card_type": CardEnums.CardType.STRATEGY,
		"rank": 2,
		"colors": [CardEnums.CardColor.RED],
		"invasion_icon": 1,
		"is_base": true,
		"effect_script": "res://scripts/effects/ebp04/ebp04_076.gd",
		"description": "<Base>When any monster card invades into zones 6–8,  <Destroy> this card.  (Cards with Base are not sent to the discard pile at the start phase.)\nYour monster card cannot be moved by your opponent’s effects. (It still moves when countered.)"
	},
	{
		"id": "EBP04-077",
		"name": "Akane Yashiro, The MFS-3 Unit",
		"card_type": CardEnums.CardType.STRATEGY,
		"rank": 4,
		"colors": [CardEnums.CardColor.RED],
		"invasion_icon": 2,
		"effect_script": "res://scripts/effects/ebp04/ebp04_077.gd",
		"description": "Reveal the top 3 cards of your deck. Add up to 1 《Mechagodzilla》 battle card from among them to your hand, and send the rest to your discard pile.\nIf you added “Multi-purpose Fighting System-3” or “Godzilla Against Mechagodzilla”, you may play it in zone 8 instead."
	},
	{
		"id": "EBP04-078",
		"name": "The Slithering Disaster",
		"card_type": CardEnums.CardType.STRATEGY,
		"rank": 5,
		"colors": [CardEnums.CardColor.RED],
		"invasion_icon": 1,
		"effect_script": "res://scripts/effects/ebp04/ebp04_078.gd",
		"description": "Move an opponent’s monster card in zones 3–5 vertically. (Move it from zone 3 to zone 8, from zone 4 to zone 7, or from zone 5 to zone 6. Battle cards in zones between them are not <Destroy>.)"
	},
	{
		"id": "EBP04-079",
		"name": "Godzilla Final Wars",
		"card_type": CardEnums.CardType.STRATEGY,
		"rank": 7,
		"colors": [CardEnums.CardColor.RED],
		"invasion_icon": 1,
		"effect_script": "res://scripts/effects/ebp04/ebp04_079.gd",
		"description": "Reveal the top 7 cards of your deck, play all  《Final Wars》 battle cards from among them, then send the rest to your discard pile."
	},
	{
		"id": "EBP04-080",
		"name": "The Bond Between Mothra and its Child",
		"card_type": CardEnums.CardType.STRATEGY,
		"rank": 2,
		"colors": [CardEnums.CardColor.BLUE],
		"invasion_icon": 1,
		"effect_script": "res://scripts/effects/ebp04/ebp04_080.gd",
		"description": "Evolve all of your rank 3 or lower battle cards with <Evolution> in your zones 1–5."
	},
	{
		"id": "EBP04-081",
		"name": "Entangling Fear",
		"card_type": CardEnums.CardType.STRATEGY,
		"rank": 3,
		"colors": [CardEnums.CardColor.BLUE],
		"invasion_icon": 1,
		"effect_script": "res://scripts/effects/ebp04/ebp04_081.gd",
		"description": "<Your Turn> Your monster card cannot advance nor invade."
	},
	{
		"id": "EBP04-082",
		"name": "Xilien Mothership",
		"card_type": CardEnums.CardType.STRATEGY,
		"rank": 5,
		"colors": [CardEnums.CardColor.BLUE],
		"invasion_icon": 2,
		"is_base": true,
		"effect_script": "res://scripts/effects/ebp04/ebp04_082.gd",
		"description": "<Base>When any monster card invades into zones 6–8,  <Destroy> this card.  (Cards with Base are not sent to the discard pile at the start phase.)\n<Your Turn> All of your non-blue battle cards in zones adjacent to your monster card gain +3000 counter power."
	},
	{
		"id": "EBP04-083",
		"name": "Godzilla vs. Destoroyah",
		"card_type": CardEnums.CardType.STRATEGY,
		"rank": 6,
		"colors": [CardEnums.CardColor.BLUE],
		"invasion_icon": 1,
		"effect_script": "res://scripts/effects/ebp04/ebp04_083.gd",
		"description": "<Destroy> all of your opponent’s battle cards in zones 6–8."
	},
	{
		"id": "EBP04-084",
		"name": "Atomic Breath",
		"card_type": CardEnums.CardType.STRATEGY,
		"rank": 1,
		"colors": [CardEnums.CardColor.GREEN],
		"invasion_icon": 1,
		"effect_script": "res://scripts/effects/ebp04/ebp04_084.gd",
		"description": "<Destroy> all of your opponent’s battle cards in the same column as your monster card."
	},
	{
		"id": "EBP04-085",
		"name": "The Golden Demise",
		"card_type": CardEnums.CardType.STRATEGY,
		"rank": 1,
		"colors": [CardEnums.CardColor.GREEN],
		"invasion_icon": 1,
		"effect_script": "res://scripts/effects/ebp04/ebp04_085.gd",
		"description": "When this card is sent from the strategy zone to your discard pile, if you have 2 or more green battle cards in your zones, you may return this card from your discard pile to your hand.\n<Opponent’s Turn> “Void Ghidorah” in your zones 1–5 cannot be <Destroy> by your opponent’s effects."
	},
	{
		"id": "EBP04-086",
		"name": "Mechagodzilla City",
		"card_type": CardEnums.CardType.STRATEGY,
		"rank": 4,
		"colors": [CardEnums.CardColor.GREEN],
		"invasion_icon": 2,
		"is_base": true,
		"effect_script": "res://scripts/effects/ebp04/ebp04_086.gd",
		"description": "<Base>When any monster card invades into zones 6–8,  <Destroy> this card.  (Cards with Base are not sent to the discard pile at the start phase.)\n<Your Turn> At the beginning of your counter phase, for every 5 green battle cards in your discard pile, play 1 “Vulture” from your discard pile."
	},
	{
		"id": "EBP04-087",
		"name": "Together / The Two of the Beginning",
		"card_type": CardEnums.CardType.STRATEGY,
		"rank": 5,
		"colors": [CardEnums.CardColor.GREEN],
		"invasion_icon": 1,
		"effect_script": "res://scripts/effects/ebp04/ebp04_087.gd",
		"description": "<Destroy> up to 1 red, 1 blue, 1 green, and 1 white battle card in your opponent’s zones 1–5."
	},
	{
		"id": "EBP04-088",
		"name": "Abducted Monsters",
		"card_type": CardEnums.CardType.STRATEGY,
		"rank": 8,
		"colors": [CardEnums.CardColor.GREEN],
		"invasion_icon": 1,
		"effect_script": "res://scripts/effects/ebp04/ebp04_088.gd",
		"description": "Return up to 2 non-green battle cards from your discard pile to your hand."
	},
	{
		"id": "EBP04-089",
		"name": "Inherited Life",
		"card_type": CardEnums.CardType.STRATEGY,
		"rank": 1,
		"colors": [CardEnums.CardColor.WHITE],
		"invasion_icon": 2,
		"effect_script": "res://scripts/effects/ebp04/ebp04_089.gd",
		"description": "During your start phase, this card is not sent to the discard pile.\n<Your Turn> Whenever your monster card’s <Rage> is reduced, place that many <Rage> under this card.\nWhen you place the 15th card under this card, <Destroy> all of your opponent’s battle cards.\nWhen you place the 22nd card, your opponent discards their entire hand.\nWhen you place the 30th card, you win the game."
	},
	{
		"id": "EBP04-T01",
		"name": "Godzilla Earth",
		"card_type": CardEnums.CardType.BATTLE,
		"rank": 7,
		"colors": [CardEnums.CardColor.GREEN],
		"traits": [CardEnums.CardTrait.TOKEN, CardEnums.CardTrait.GODZILLA, CardEnums.CardTrait.GODZILLA_EARTH],
		"counter_power": 9000,
		"effect_script": "res://scripts/effects/ebp04/ebp04_T01.gd",
		"description": "(Tokens cannot be added to the deck. They are banished when removed from zones.)"
	},
]
