extends RefCounted
## EBP01: Booster Pack 01 — card data only, split verbatim from card_data.gd.

var CARDS: Array[Dictionary] = [
	{
		"id": "EBP01-001",
		"name": "Godzilla(1954)",
		"card_type": CardEnums.CardType.MONSTER,
		"rank": 1,
		"colors": [CardEnums.CardColor.RED],
		"traits": [CardEnums.CardTrait.GODZILLA],
		"threat_level": 5000,
		"invasion_icon": 1,
		"description": "At the beginning of your counter phase, send the top card of your deck to your discard pile.\nIf it is a monster card, increase this card's <Rage> by 1.",
		"effect_script": "res://scripts/effects/ebp01/ebp01_001.gd"
	},
	{
		"id": "EBP01-002",
		"name": "Godzilla(1954)",
		"card_type": CardEnums.CardType.MONSTER,
		"rank": 2,
		"colors": [CardEnums.CardColor.RED],
		"traits": [CardEnums.CardTrait.GODZILLA],
		"threat_level": 13000,
		"invasion_icon": 1,
		"description": "<Burst1> (You can play this card from rank I. If you do, send this card to your discard pile at the beginning of your next end phase.)\n<When Invading> Send the top card of your deck to your discard pile. If it is a monster card, <Destroy> 1 of your opponent’s rank 5 or lower battle cards.",
		"effect_script": "res://scripts/effects/ebp01/ebp01_002.gd"
	},
	{
		"id": "EBP01-003",
		"name": "Godzilla(1954)",
		"card_type": CardEnums.CardType.MONSTER,
		"rank": 3,
		"colors": [CardEnums.CardColor.RED],
		"traits": [CardEnums.CardTrait.GODZILLA],
		"threat_level": 23000,
		"invasion_icon": 1,
		"description": "Whenever this card's <Rage> is increased, send the top card of your deck to your discard pile. If it is a monster card, <Destroy> 1 of your opponent’s rank 6 or lower battle cards.",
		"effect_script": "res://scripts/effects/ebp01/ebp01_003.gd"
	},
	{
		"id": "EBP01-004",
		"name": "Godzilla(1954)",
		"card_type": CardEnums.CardType.MONSTER,
		"rank": 4,
		"colors": [CardEnums.CardColor.RED],
		"traits": [CardEnums.CardTrait.GODZILLA],
		"threat_level": 34000,
		"invasion_icon": 1,
		"description": "<Burst3> (You can play this card from rank III. If you do, send this card to your discard pile at the beginning of your next end phase.)\nWhen this card reaches zone 8, <Destroy> all battle cards in each player's zones.",
		"effect_script": "res://scripts/effects/ebp01/ebp01_004.gd"
	},
	{
		"id": "EBP01-005",
		"name": "Godzilla(1955)",
		"card_type": CardEnums.CardType.MONSTER,
		"rank": 4,
		"colors": [CardEnums.CardColor.RED],
		"traits": [CardEnums.CardTrait.GODZILLA],
		"threat_level": 37000,
		"invasion_icon": 1,
		"description": "<Burst3> (You can play this card from rank III. If you do, send this card to your discard pile at the beginning of your next end phase.)\n<Enter> Your opponent discards cards until they have 4 cards remaining in their hand.",
		"effect_script": "res://scripts/effects/ebp01/ebp01_005.gd"
	},
	{
		"id": "EBP01-006",
		"name": "Godzilla(1974)",
		"card_type": CardEnums.CardType.MONSTER,
		"rank": 3,
		"colors": [CardEnums.CardColor.RED],
		"traits": [CardEnums.CardTrait.GODZILLA],
		"threat_level": 23000,
		"invasion_icon": 2,
		"description": "<Opponent’s Turn> At the beginning of the counter phase, <Destroy> all of your opponent’s rank 5 or lower battle cards in the same column as this card.",
		"effect_script": "res://scripts/effects/ebp01/ebp01_006.gd"
	},
	{
		"id": "EBP01-007",
		"name": "Godzilla(1975)",
		"card_type": CardEnums.CardType.MONSTER,
		"rank": 4,
		"colors": [CardEnums.CardColor.RED],
		"traits": [CardEnums.CardTrait.GODZILLA],
		"threat_level": 34000,
		"invasion_icon": 1,
		"description": "<Burst3> (You can play this card from rank III. If you do, send this card to your discard pile at the beginning of your next end phase.)\n<When Invading> When this card <Destroy> your battle cards, reduce your opponent's <Rage> by 2.",
		"effect_script": "res://scripts/effects/ebp01/ebp01_007.gd"
	},
	{
		"id": "EBP01-008",
		"name": "Godzilla(2004)",
		"card_type": CardEnums.CardType.MONSTER,
		"rank": 3,
		"colors": [CardEnums.CardColor.RED],
		"traits": [CardEnums.CardTrait.GODZILLA],
		"threat_level": 22000,
		"invasion_icon": 2,
		"description": "<Burst2> (You can play this card from rank II. If you do, send this card to your discard pile at the beginning of your next end phase.)\n<Enter> Advance your opponent’s monster card by 1 zone.",
		"effect_script": "res://scripts/effects/ebp01/ebp01_008.gd"
	},
	{
		"id": "EBP01-009",
		"name": "Godzilla(2023)",
		"card_type": CardEnums.CardType.MONSTER,
		"rank": 3,
		"colors": [CardEnums.CardColor.RED],
		"traits": [CardEnums.CardTrait.GODZILLA],
		"threat_level": 22000,
		"invasion_icon": 1,
		"description": "<Burst2> (You can play this card from rank II. If you do, send this card to your discard pile at the beginning of your next end phase.)\n<When Invading> If this card has 2 or more <Rage> , <Destroy> 1 of your opponent’s rank 6 or lower battle cards.",
		"effect_script": "res://scripts/effects/ebp01/ebp01_009.gd"
	},
	{
		"id": "EBP01-010",
		"name": "Godzilla(2023)",
		"card_type": CardEnums.CardType.MONSTER,
		"rank": 4,
		"colors": [CardEnums.CardColor.RED],
		"traits": [CardEnums.CardTrait.GODZILLA],
		"threat_level": 37000,
		"invasion_icon": 2,
		"description": "Whenever this card's <Rage> is increased, <Destroy> all of your opponent’s battle cards in the same column as this card.\n<Opponent’s Turn> At the beginning of the counter phase, if this card has 3 or more <Rage> , <Destroy> all of your opponent’s battle cards in the same column as this card.",
		"effect_script": "res://scripts/effects/ebp01/ebp01_010.gd"
	},
	{
		"id": "EBP01-011",
		"name": "Godzilla(Fest Godzilla)",
		"card_type": CardEnums.CardType.MONSTER,
		"rank": 1,
		"colors": [CardEnums.CardColor.RED],
		"traits": [CardEnums.CardTrait.GODZILLA, CardEnums.CardTrait.FEST],
		"threat_level": 4000,
		"invasion_icon": 1,
		"description": "When this card advances into the same column as your opponent’s monster card, advance your opponent’s monster card by 1 zone.",
		"effect_script": "res://scripts/effects/ebp01/ebp01_011.gd"
	},
	{
		"id": "EBP01-012",
		"name": "Godzilla(Fest Godzilla)",
		"card_type": CardEnums.CardType.MONSTER,
		"rank": 2,
		"colors": [CardEnums.CardColor.RED],
		"traits": [CardEnums.CardTrait.GODZILLA, CardEnums.CardTrait.FEST],
		"threat_level": 13000,
		"invasion_icon": 1,
		"description": "At the beginning of your end phase, if this card invaded this turn, advance your opponent’s monster card by 1 zone.",
		"effect_script": "res://scripts/effects/ebp01/ebp01_012.gd"
	},
	{
		"id": "EBP01-013",
		"name": "Godzilla(Fest Godzilla)",
		"card_type": CardEnums.CardType.MONSTER,
		"rank": 3,
		"colors": [CardEnums.CardColor.RED],
		"traits": [CardEnums.CardTrait.GODZILLA, CardEnums.CardTrait.FEST],
		"threat_level": 19000,
		"invasion_icon": 1,
		"description": "<Burst2> (You can play this card from rank II. If you do, send this card to your discard pile at the beginning of your next end phase.)\n<Enter> If you have 4 or more battle cards in your zones, reduce your opponent’s <Rage> by 1.",
		"effect_script": "res://scripts/effects/ebp01/ebp01_013.gd"
	},
	{
		"id": "EBP01-014",
		"name": "Godzilla(Fest Godzilla)",
		"card_type": CardEnums.CardType.MONSTER,
		"rank": 4,
		"colors": [CardEnums.CardColor.RED],
		"traits": [CardEnums.CardTrait.GODZILLA, CardEnums.CardTrait.FEST],
		"threat_level": 34000,
		"invasion_icon": 1,
		"description": "<Opponent’s Turn> <Awakening4> If you have 2 or more battle cards in your zones, all of your opponent’s rank 5 or lower battle cards cannot engage with this card. (Their counter power is not included in the total counter power during the counter phase.)",
		"effect_script": "res://scripts/effects/ebp01/ebp01_014.gd"
	},
	{
		"id": "EBP01-015",
		"name": "Godzilla(Fest Godzilla)",
		"card_type": CardEnums.CardType.MONSTER,
		"rank": 4,
		"colors": [CardEnums.CardColor.RED],
		"traits": [CardEnums.CardTrait.GODZILLA, CardEnums.CardTrait.FEST],
		"threat_level": 28000,
		"invasion_icon": 1,
		"description": "<Your Turn> <Enter> Reveal the top 5 cards of your deck and send them to your discard pile. For each monster card revealed this way, increase this card's <Rage> by 1. If a card with <Step2> is revealed this way, this card advances to zone 6.",
		"effect_script": "res://scripts/effects/ebp01/ebp01_015.gd"
	},
	{
		"id": "EBP01-016",
		"name": "Ebirah(2004)",
		"card_type": CardEnums.CardType.BATTLE,
		"rank": 1,
		"colors": [CardEnums.CardColor.RED],
		"traits": [CardEnums.CardTrait.EBIRAH, CardEnums.CardTrait.FINAL_WARS],
		"counter_power": 1000,
		"invasion_icon": 1
	},
	{
		"id": "EBP01-017",
		"name": "Kumonga(2004)",
		"card_type": CardEnums.CardType.BATTLE,
		"rank": 2,
		"colors": [CardEnums.CardColor.RED],
		"traits": [CardEnums.CardTrait.KUMONGA, CardEnums.CardTrait.FINAL_WARS],
		"counter_power": 1000,
		"invasion_icon": 1,
		"description": "If this card is in zone 8, this card gains +3000 counter power.",
		"effect_script": "res://scripts/effects/ebp01/ebp01_017.gd"
	},
	{
		"id": "EBP01-018",
		"name": "Mechagodzilla(1974)",
		"card_type": CardEnums.CardType.BATTLE,
		"rank": 3,
		"colors": [CardEnums.CardColor.RED],
		"traits": [CardEnums.CardTrait.MECHAGODZILLA, CardEnums.CardTrait.WEAPON],
		"counter_power": 1000,
		"invasion_icon": 1,
		"description": "<Awakening4> This card gains +3000 counter power. (Active if your monster card is in zone 4 or beyond.)",
		"effect_script": "res://scripts/effects/ebp01/ebp01_018.gd"
	},
	{
		"id": "EBP01-019",
		"name": "Kamacuras(1967)",
		"card_type": CardEnums.CardType.BATTLE,
		"rank": 3,
		"colors": [CardEnums.CardColor.RED],
		"traits": [CardEnums.CardTrait.KAMACURAS],
		"counter_power": 2000,
		"invasion_icon": 1,
		"description": "<Awakening6> <Enter> If this card was played from your hand, search your deck for up to 2 <《Kamacuras》> battle cards, play them, then shuffle your deck. (Active if your monster card is in zone 6 or beyond.)",
		"effect_script": "res://scripts/effects/ebp01/ebp01_019.gd"
	},
	{
		"id": "EBP01-020",
		"name": "Anguirus(1968)",
		"card_type": CardEnums.CardType.BATTLE,
		"rank": 3,
		"colors": [CardEnums.CardColor.RED],
		"traits": [CardEnums.CardTrait.ANGUIRUS],
		"counter_power": 2000,
		"invasion_icon": 1,
		"description": "If this card is in zone 8, whenever your monster card invades, you may reduce its <Rage> by 1 to search your deck for up to 1 monster card with <Burst> , reveal it, add it to your hand, then shuffle your deck.",
		"effect_script": "res://scripts/effects/ebp01/ebp01_020.gd"
	},
	{
		"id": "EBP01-021",
		"name": "Rodan(1968)",
		"card_type": CardEnums.CardType.BATTLE,
		"rank": 4,
		"colors": [CardEnums.CardColor.RED],
		"traits": [CardEnums.CardTrait.RODAN],
		"counter_power": 3000,
		"invasion_icon": 1,
		"description": "<Enter> If this card is in the same column as your opponent’s monster card, look at the top 2 cards of your deck, put any number on top of your deck in any order, and send the rest to your discard pile.",
		"effect_script": "res://scripts/effects/ebp01/ebp01_021.gd"
	},
	{
		"id": "EBP01-022",
		"name": "Titanosaurus",
		"card_type": CardEnums.CardType.BATTLE,
		"rank": 5,
		"colors": [CardEnums.CardColor.RED],
		"traits": [CardEnums.CardTrait.TITANOSAURUS],
		"counter_power": 4000,
		"invasion_icon": 1,
		"description": "<Your Turn> Whenever your monster card's <Rage> is increased, you may move 1 of your other battle cards in your zones to an unoccupied zone.",
		"effect_script": "res://scripts/effects/ebp01/ebp01_022.gd"
	},
	{
		"id": "EBP01-023",
		"name": "Mechagodzilla(1975)",
		"card_type": CardEnums.CardType.BATTLE,
		"rank": 5,
		"colors": [CardEnums.CardColor.RED],
		"traits": [CardEnums.CardTrait.MECHAGODZILLA, CardEnums.CardTrait.WEAPON],
		"counter_power": 4000,
		"invasion_icon": 1,
		"description": "If your monster card has 2 or more <Rage> , this card gains +3000 counter power.",
		"effect_script": "res://scripts/effects/ebp01/ebp01_023.gd"
	},
	{
		"id": "EBP01-024",
		"name": "Minilla(2004)",
		"card_type": CardEnums.CardType.BATTLE,
		"rank": 6,
		"colors": [CardEnums.CardColor.RED],
		"traits": [CardEnums.CardTrait.MINILLA, CardEnums.CardTrait.FINAL_WARS],
		"counter_power": 2000,
		"invasion_icon": 1,
		"description": "<Enter> Reduce your opponent's <Rage> by 1.",
		"effect_script": "res://scripts/effects/ebp01/ebp01_024.gd"
	},
	{
		"id": "EBP01-025",
		"name": "King Caesar(1974)",
		"card_type": CardEnums.CardType.BATTLE,
		"rank": 6,
		"colors": [CardEnums.CardColor.RED],
		"traits": [CardEnums.CardTrait.KING_CAESAR],
		"counter_power": 4000,
		"invasion_icon": 1,
		"description": "If this card is in a zone adjacent to your monster card, this card gains +3000 counter power.",
		"effect_script": "res://scripts/effects/ebp01/ebp01_025.gd"
	},
	{
		"id": "EBP01-026",
		"name": "Jet Jaguar(2023)",
		"card_type": CardEnums.CardType.BATTLE,
		"rank": 7,
		"colors": [CardEnums.CardColor.RED],
		"traits": [CardEnums.CardTrait.JET_JAGUAR, CardEnums.CardTrait.MECH, CardEnums.CardTrait.FEST],
		"counter_power": 7000,
		"invasion_icon": 2,
		"description": "At the beginning of your counter phase, you may place 1 card with both <《Gigan》> and <《Fest》> from your discard pile under this card.\nIf there is a card under this card, this card gains +5000 counter power.",
		"effect_script": "res://scripts/effects/ebp01/ebp01_026.gd"
	},
	{
		"id": "EBP01-027",
		"name": "Hedorah(1971)",
		"card_type": CardEnums.CardType.BATTLE,
		"rank": 8,
		"colors": [CardEnums.CardColor.RED],
		"traits": [CardEnums.CardTrait.HEDORAH],
		"counter_power": 7000,
		"invasion_icon": 2,
		"description": "When playing this card from your hand, you can reduce its rank by 1 for each battle card in your zones. (After being played this card is rank 8)",
		"effect_script": "res://scripts/effects/ebp01/ebp01_027.gd"
	},
	{
		"id": "EBP01-028",
		"name": "Godzilla vs. Mechagodzilla",
		"card_type": CardEnums.CardType.STRATEGY,
		"rank": 2,
		"colors": [CardEnums.CardColor.RED],
		"invasion_icon": 1,
		"description": "<Opponent’s Turn> All of your opponent’s rank 3 or lower battle cards cannot engage with your monster card. (Their counter power is not included in the total during the counter phase.)",
		"effect_script": "res://scripts/effects/ebp01/ebp01_028.gd"
	},
	{
		"id": "EBP01-029",
		"name": "Unthinkable Destruction",
		"card_type": CardEnums.CardType.STRATEGY,
		"rank": 3,
		"colors": [CardEnums.CardColor.RED],
		"invasion_icon": 1,
		"description": "Choose 1 of your opponent’s zones. <Destroy> all of your opponent’s rank 5 or lower battle cards in that zone and zones adjacent to it.",
		"effect_script": "res://scripts/effects/ebp01/ebp01_029.gd"
	},
	{
		"id": "EBP01-030",
		"name": "Godzilla Landing",
		"card_type": CardEnums.CardType.STRATEGY,
		"rank": 3,
		"colors": [CardEnums.CardColor.RED],
		"invasion_icon": 1,
		"description": "Advance the opponent’s monster card by 1 zone.",
		"effect_script": "res://scripts/effects/ebp01/ebp01_030.gd"
	},
	{
		"id": "EBP01-031",
		"name": "Space Beam",
		"card_type": CardEnums.CardType.STRATEGY,
		"rank": 5,
		"colors": [CardEnums.CardColor.RED],
		"invasion_icon": 2,
		"description": "If your monster card has 2 or more <Rage> , your opponent discards cards until they have 2 cards remaining in their hand.",
		"effect_script": "res://scripts/effects/ebp01/ebp01_031.gd"
	},
	{
		"id": "EBP01-032",
		"name": "Heat Ray Charge",
		"card_type": CardEnums.CardType.STRATEGY,
		"rank": 6,
		"colors": [CardEnums.CardColor.RED],
		"invasion_icon": 2,
		"description": "Draw 2 cards.",
		"effect_script": "res://scripts/effects/ebp01/ebp01_032.gd"
	},
	{
		"id": "EBP01-033",
		"name": "Final Showdown",
		"card_type": CardEnums.CardType.STRATEGY,
		"rank": 8,
		"colors": [CardEnums.CardColor.RED],
		"invasion_icon": 1,
		"description": "You can play this card from your hand with its rank reduced by 1 for each zone your monster card invaded this turn.\n<Destroy> all battle cards of both players.",
		"effect_script": "res://scripts/effects/ebp01/ebp01_033.gd"
	},
	{
		"id": "EBP01-034",
		"name": "Godzilla(1989)",
		"card_type": CardEnums.CardType.MONSTER,
		"rank": 2,
		"colors": [CardEnums.CardColor.BLUE],
		"traits": [CardEnums.CardTrait.GODZILLA],
		"threat_level": 13000,
		"invasion_icon": 1,
		"description": "<Enter> Select 1 rank 4 or lower battle card with <Evolution> from your discard pile and play it in a zone adjacent to this card.",
		"effect_script": "res://scripts/effects/ebp01/ebp01_034.gd"
	},
	{
		"id": "EBP01-035",
		"name": "Godzilla(1989)",
		"card_type": CardEnums.CardType.MONSTER,
		"rank": 3,
		"colors": [CardEnums.CardColor.BLUE],
		"traits": [CardEnums.CardTrait.GODZILLA],
		"threat_level": 23000,
		"invasion_icon": 1,
		"description": "<Enter> Evolve all of your rank 4 or lower battle cards with <Evolution> in zones adjacent to this card.",
		"effect_script": "res://scripts/effects/ebp01/ebp01_035.gd"
	},
	{
		"id": "EBP01-036",
		"name": "Godzilla(1992)",
		"card_type": CardEnums.CardType.MONSTER,
		"rank": 4,
		"colors": [CardEnums.CardColor.BLUE],
		"traits": [CardEnums.CardTrait.GODZILLA],
		"threat_level": 36000,
		"invasion_icon": 1,
		"description": "<Enter> Evolve all of your battle cards with <Evolution> in zones adjacent to this card.",
		"effect_script": "res://scripts/effects/ebp01/ebp01_036.gd"
	},
	{
		"id": "EBP01-037",
		"name": "Godzilla(1995)",
		"card_type": CardEnums.CardType.MONSTER,
		"rank": 3,
		"colors": [CardEnums.CardColor.BLUE],
		"traits": [CardEnums.CardTrait.GODZILLA],
		"threat_level": 22000,
		"invasion_icon": 1,
		"description": "Whenever this card advances, you may discard 1 strategy card from your hand to increase its <Rage> by 1.",
		"effect_script": "res://scripts/effects/ebp01/ebp01_037.gd"
	},
	{
		"id": "EBP01-038",
		"name": "Godzilla(1995)",
		"card_type": CardEnums.CardType.MONSTER,
		"rank": 4,
		"colors": [CardEnums.CardColor.BLUE],
		"traits": [CardEnums.CardTrait.GODZILLA],
		"threat_level": 34000,
		"invasion_icon": 1,
		"description": "<Opponent’s Turn> <Awakening6> This card cannot be countered by 50,000 or lower counter power, instead, it only moves as though it were countered. (Do not play the next monster card from your monster deck.) (Active if this card is in zone 6 or beyond, and the opponent’s total counter power is 50,000 or lower.)",
		"effect_script": "res://scripts/effects/ebp01/ebp01_038.gd"
	},
	{
		"id": "EBP01-039",
		"name": "Godzilla(1999)",
		"card_type": CardEnums.CardType.MONSTER,
		"rank": 2,
		"colors": [CardEnums.CardColor.BLUE],
		"traits": [CardEnums.CardTrait.GODZILLA],
		"threat_level": 15000,
		"invasion_icon": 2,
		"description": "<When Invading> Discard 1 monster card from your hand： <Destroy> all of your opponent’s rank 5 or lower battle cards in zones 1-5.",
		"effect_script": "res://scripts/effects/ebp01/ebp01_039.gd"
	},
	{
		"id": "EBP01-040",
		"name": "Godzilla(1999)",
		"card_type": CardEnums.CardType.MONSTER,
		"rank": 4,
		"colors": [CardEnums.CardColor.BLUE],
		"traits": [CardEnums.CardTrait.GODZILLA],
		"threat_level": 33000,
		"invasion_icon": 2,
		"description": "<Enter> <Destroy> 1 of your opponent’s rank 7 or lower battle cards.\n<When Invading> If you have 5 or more monster cards in your discard pile, increase this card's <Rage> by 1.",
		"effect_script": "res://scripts/effects/ebp01/ebp01_040.gd"
	},
	{
		"id": "EBP01-041",
		"name": "Godzilla(2000)",
		"card_type": CardEnums.CardType.MONSTER,
		"rank": 1,
		"colors": [CardEnums.CardColor.BLUE],
		"traits": [CardEnums.CardTrait.GODZILLA],
		"threat_level": 5000,
		"invasion_icon": 1,
		"description": "<When Invading> <Destroy> 1 of your opponent’s rank 4 or lower battle cards.",
		"effect_script": "res://scripts/effects/ebp01/ebp01_041.gd"
	},
	{
		"id": "EBP01-042",
		"name": "Godzilla(2000)",
		"card_type": CardEnums.CardType.MONSTER,
		"rank": 3,
		"colors": [CardEnums.CardColor.BLUE],
		"traits": [CardEnums.CardTrait.GODZILLA],
		"threat_level": 18000,
		"invasion_icon": 1,
		"description": "<Enter> If you have 5 or more monster cards in your discard pile, you may discard 1 card from your hand to reduce your opponent's <Rage> by 1.\nIf you have 5 or more monster cards in your discard pile, this card gains +10,000 threat level.",
		"effect_script": "res://scripts/effects/ebp01/ebp01_042.gd"
	},
	{
		"id": "EBP01-043",
		"name": "Godzilla(2000)",
		"card_type": CardEnums.CardType.MONSTER,
		"rank": 4,
		"colors": [CardEnums.CardColor.BLUE],
		"traits": [CardEnums.CardTrait.GODZILLA],
		"threat_level": 36000,
		"invasion_icon": 1,
		"description": "<Awakening4> When you successfully counter your opponent’s monster card, if you have 5 or more monster cards in your discard pile, <Destroy> all of your opponent’s rank 6 or lower battle cards. (Active if this card is in zone 4 or beyond.)",
		"effect_script": "res://scripts/effects/ebp01/ebp01_043.gd"
	},
	{
		"id": "EBP01-044",
		"name": "Mothra(egg)(1992)",
		"card_type": CardEnums.CardType.BATTLE,
		"rank": 1,
		"colors": [CardEnums.CardColor.BLUE],
		"traits": [CardEnums.CardTrait.MOTHRA],
		"counter_power": 0,
		"invasion_icon": 1,
		"description": "<Evolution5> <《Mothra》> (At the beginning of your main phase, you may play a rank 5 or lower <《Mothra》> battle card from your deck by placing it on top of this card.)",
		"evolution_rank": 5,
		"evolution_trait": CardEnums.CardTrait.MOTHRA,
		"effect_script": "res://scripts/effects/ebp01/ebp01_044.gd"
	},
	{
		"id": "EBP01-045",
		"name": "Meganula",
		"card_type": CardEnums.CardType.BATTLE,
		"rank": 2,
		"colors": [CardEnums.CardColor.BLUE],
		"traits": [CardEnums.CardTrait.MEGANULA],
		"counter_power": 1000,
		"invasion_icon": 1,
		"description": "<Enter> If this card is in the same column as your opponent’s monster card and you have 2 or more battle cards in your zones, reduce your opponent's <Rage> by 1.",
		"effect_script": "res://scripts/effects/ebp01/ebp01_045.gd"
	},
	{
		"id": "EBP01-046",
		"name": "MBT-MB92",
		"card_type": CardEnums.CardType.BATTLE,
		"rank": 3,
		"colors": [CardEnums.CardColor.BLUE],
		"traits": [CardEnums.CardTrait.WEAPON],
		"counter_power": 1000,
		"invasion_icon": 1,
		"unlimited_copies": true,
		"description": "You may have any number of this card in your deck.\n<Awakening6> This card gains +3000 counter power. (Active if your monster card is in zone 6 or beyond.)",
		"effect_script": "res://scripts/effects/ebp01/ebp01_046.gd"
	},
	{
		"id": "EBP01-047",
		"name": "Orga",
		"card_type": CardEnums.CardType.BATTLE,
		"rank": 3,
		"colors": [CardEnums.CardColor.BLUE],
		"traits": [CardEnums.CardTrait.ORGA],
		"counter_power": 2000,
		"invasion_icon": 1,
		"description": "<Enter> Draw 1 card, then discard 1 card.",
		"effect_script": "res://scripts/effects/ebp01/ebp01_047.gd"
	},
	{
		"id": "EBP01-048",
		"name": "Biollante Rose Form",
		"card_type": CardEnums.CardType.BATTLE,
		"rank": 3,
		"colors": [CardEnums.CardColor.BLUE],
		"traits": [CardEnums.CardTrait.BIOLLANTE],
		"counter_power": 2000,
		"invasion_icon": 1,
		"description": "<Evolution7> <《Biollante》> (At the beginning of your main phase, you may play a rank 7 or lower battle card with <《Biollante》> from your deck by placing it on top of this card.)",
		"evolution_rank": 7,
		"evolution_trait": CardEnums.CardTrait.BIOLLANTE,
		"effect_script": "res://scripts/effects/ebp01/ebp01_048.gd"
	},
	{
		"id": "EBP01-049",
		"name": "Destoroyah Aggregate Form",
		"card_type": CardEnums.CardType.BATTLE,
		"rank": 4,
		"colors": [CardEnums.CardColor.BLUE],
		"traits": [CardEnums.CardTrait.DESTOROYAH],
		"counter_power": 3000,
		"invasion_icon": 1,
		"description": "<Evolution6> <《Destoroyah》> (At the beginning of your main phase, you may play a rank 6 or lower <《Destoroyah》> battle card from your deck by placing it on top of this card.)",
		"evolution_rank": 6,
		"evolution_trait": CardEnums.CardTrait.DESTOROYAH,
		"effect_script": "res://scripts/effects/ebp01/ebp01_049.gd"
	},
	{
		"id": "EBP01-050",
		"name": "Mothra(larva)(1992)",
		"card_type": CardEnums.CardType.BATTLE,
		"rank": 4,
		"colors": [CardEnums.CardColor.BLUE],
		"traits": [CardEnums.CardTrait.MOTHRA],
		"counter_power": 3000,
		"invasion_icon": 1,
		"description": "<Evolution7> <《Mothra》> (At the beginning of your main phase, you may play a rank 7 or lower <《Mothra》> battle card from your deck by placing it on top of this card.)",
		"evolution_rank": 7,
		"evolution_trait": CardEnums.CardTrait.MOTHRA,
		"effect_script": "res://scripts/effects/ebp01/ebp01_050.gd"
	},
	{
		"id": "EBP01-051",
		"name": "Orga Phase II",
		"card_type": CardEnums.CardType.BATTLE,
		"rank": 4,
		"colors": [CardEnums.CardColor.BLUE],
		"traits": [CardEnums.CardTrait.ORGA],
		"counter_power": 3000,
		"invasion_icon": 1,
		"description": "If you have 5 or more monster cards in your discard pile, this card gains +3000 counter power.",
		"effect_script": "res://scripts/effects/ebp01/ebp01_051.gd"
	},
	{
		"id": "EBP01-052",
		"name": "Megaguirus",
		"card_type": CardEnums.CardType.BATTLE,
		"rank": 5,
		"colors": [CardEnums.CardColor.BLUE],
		"traits": [CardEnums.CardTrait.MEGAGUIRUS],
		"counter_power": 3000,
		"invasion_icon": 2,
		"description": "<Awakening4> If this card is in zones 1-5 and you have 5 or more monster cards in your discard pile, this card cannot be <Destroy> by your opponent's effects. (Active if your monster card is in zone 4 or beyond.)",
		"effect_script": "res://scripts/effects/ebp01/ebp01_052.gd"
	},
	{
		"id": "EBP01-053",
		"name": "Rodan(1993)",
		"card_type": CardEnums.CardType.BATTLE,
		"rank": 5,
		"colors": [CardEnums.CardColor.BLUE],
		"traits": [CardEnums.CardTrait.RODAN],
		"counter_power": 5000,
		"invasion_icon": 1
	},
	{
		"id": "EBP01-054",
		"name": "Destoroyah Flying Form",
		"card_type": CardEnums.CardType.BATTLE,
		"rank": 6,
		"colors": [CardEnums.CardColor.BLUE],
		"traits": [CardEnums.CardTrait.DESTOROYAH],
		"counter_power": 4000,
		"invasion_icon": 1,
		"description": "<Evolution8> <《Destoroyah》> (At the beginning of your main phase, you may play a rank 8 or lower <《Destoroyah》> battle card from your deck by placing it on top of this card.)\n<Enter> If this card was played through evolution, draw 2 cards, then discard 2 cards.",
		"evolution_rank": 8,
		"evolution_trait": CardEnums.CardTrait.DESTOROYAH,
		"effect_script": "res://scripts/effects/ebp01/ebp01_054.gd"
	},
	{
		"id": "EBP01-055",
		"name": "Battra(imago)",
		"card_type": CardEnums.CardType.BATTLE,
		"rank": 6,
		"colors": [CardEnums.CardColor.BLUE],
		"traits": [CardEnums.CardTrait.BATTRA],
		"counter_power": 5000,
		"invasion_icon": 1,
		"description": "<Enter> Draw 1 card, then discard 1 card.",
		"effect_script": "res://scripts/effects/ebp01/ebp01_055.gd"
	},
	{
		"id": "EBP01-056",
		"name": "Super X2",
		"card_type": CardEnums.CardType.BATTLE,
		"rank": 6,
		"colors": [CardEnums.CardColor.BLUE],
		"traits": [CardEnums.CardTrait.SUPER_X, CardEnums.CardTrait.WEAPON],
		"counter_power": 5000,
		"invasion_icon": 2,
		"description": "If this card is in the same column as your opponent’s monster card, this card gains +3000 counter power for each of your opponent's <Rage> .",
		"effect_script": "res://scripts/effects/ebp01/ebp01_056.gd"
	},
	{
		"id": "EBP01-057",
		"name": "Mothra(imago)(1992)",
		"card_type": CardEnums.CardType.BATTLE,
		"rank": 7,
		"colors": [CardEnums.CardColor.BLUE],
		"traits": [CardEnums.CardTrait.MOTHRA],
		"counter_power": 5000,
		"invasion_icon": 2,
		"description": "<Enter> Choose 2 battle cards in your zones, you may swap their positions.\nYour rank 5 or lower battle cards in zones adjacent to this card gain +3000 counter power.",
		"effect_script": "res://scripts/effects/ebp01/ebp01_057.gd"
	},
	{
		"id": "EBP01-058",
		"name": "Biollante Plant Beast Form",
		"card_type": CardEnums.CardType.BATTLE,
		"rank": 7,
		"colors": [CardEnums.CardColor.BLUE],
		"traits": [CardEnums.CardTrait.BIOLLANTE],
		"counter_power": 6000,
		"invasion_icon": 1,
		"description": "If you have a <《Biollante》> card with <Evolution> in your discard pile, you can play this from your hand with its rank reduced by 2. (After being played, this card is rank 7.)\n<Enter> Return all cards in your discard pile to your deck then shuffle.",
		"effect_script": "res://scripts/effects/ebp01/ebp01_058.gd"
	},
	{
		"id": "EBP01-059",
		"name": "Fire Rodan",
		"card_type": CardEnums.CardType.BATTLE,
		"rank": 7,
		"colors": [CardEnums.CardColor.BLUE],
		"traits": [CardEnums.CardTrait.RODAN],
		"counter_power": 6000,
		"invasion_icon": 1,
		"description": "When this card is discarded from your hand by your opponent's effect, and their monster card is in zones 4-8, you may play this card. (Regardless of what zone your opponent's monster card is occupying.)\nIf this card is in zone 8, this card gains +3000 counter power.",
		"effect_script": "res://scripts/effects/ebp01/ebp01_059.gd"
	},
	{
		"id": "EBP01-060",
		"name": "Destoroyah Perfect Form",
		"card_type": CardEnums.CardType.BATTLE,
		"rank": 8,
		"colors": [CardEnums.CardColor.BLUE],
		"traits": [CardEnums.CardTrait.DESTOROYAH],
		"counter_power": 10000,
		"invasion_icon": 1,
		"description": "<Enter> If this card was played through evolution, choose up to 1 strategy card named 「Godzilla vs. Destoroyah」in your discard pile.\nIf you have 1 or fewer strategy cards in play, play and activate the chosen card. (Regardless of rank.)",
		"effect_script": "res://scripts/effects/ebp01/ebp01_060.gd"
	},
	{
		"id": "EBP01-061",
		"name": "Scale Attack",
		"card_type": CardEnums.CardType.STRATEGY,
		"rank": 1,
		"colors": [CardEnums.CardColor.BLUE],
		"invasion_icon": 1,
		"description": "If your opponent has 5 or more <Rage> , reduce their <Rage> by 3.",
		"effect_script": "res://scripts/effects/ebp01/ebp01_061.gd"
	},
	{
		"id": "EBP01-062",
		"name": "Godzilla vs. Destoroyah",
		"card_type": CardEnums.CardType.STRATEGY,
		"rank": 3,
		"colors": [CardEnums.CardColor.BLUE],
		"invasion_icon": 2,
		"description": "<Your Turn> If you have a <《Destoroyah》> battle card in your zones, increase your total counter power by +10,000.",
		"effect_script": "res://scripts/effects/ebp01/ebp01_062.gd"
	},
	{
		"id": "EBP01-063",
		"name": "Guardians Awaken",
		"card_type": CardEnums.CardType.STRATEGY,
		"rank": 4,
		"colors": [CardEnums.CardColor.BLUE],
		"invasion_icon": 2,
		"description": "Evolve all of your rank 4 or lower battle cards with <Evolution> .",
		"effect_script": "res://scripts/effects/ebp01/ebp01_063.gd"
	},
	{
		"id": "EBP01-064",
		"name": "Godzilla vs. Megaguirus",
		"card_type": CardEnums.CardType.STRATEGY,
		"rank": 5,
		"colors": [CardEnums.CardColor.BLUE],
		"invasion_icon": 1,
		"description": "Choose one of the following:\n・ <Destroy> 1 of your opponent’s rank 4 or lower battle cards.\n・If you have 4 or more battle cards in your zones, choose 1 of your opponent’s zones and <Destroy> all battle cards in that zone and zones adjacent to it.",
		"effect_script": "res://scripts/effects/ebp01/ebp01_064.gd"
	},
	{
		"id": "EBP01-065",
		"name": "Godzilla vs. Destoroyah",
		"card_type": CardEnums.CardType.STRATEGY,
		"rank": 6,
		"colors": [CardEnums.CardColor.BLUE],
		"invasion_icon": 1,
		"description": "<Destroy> all of your opponent’s battle cards in zones 1-5.",
		"effect_script": "res://scripts/effects/ebp01/ebp01_065.gd"
	},
	{
		"id": "EBP01-066",
		"name": "Godzilla vs. Biollante",
		"card_type": CardEnums.CardType.STRATEGY,
		"rank": 7,
		"colors": [CardEnums.CardColor.BLUE],
		"invasion_icon": 1,
		"description": "When this card is discarded from your hand by your opponent's effect, increase your monster card’s <Rage> by 2.\n<Opponent’s Turn> Your monster card cannot be countered by 40,000 or lower counter power. Instead, it only moves as though it were countered. (Do not play the next monster card from your monster deck.)",
		"effect_script": "res://scripts/effects/ebp01/ebp01_066.gd"
	},
	{
		"id": "EBP01-067",
		"name": "Gorosaurus",
		"card_type": CardEnums.CardType.BATTLE,
		"rank": 2,
		"colors": [CardEnums.CardColor.WHITE],
		"traits": [CardEnums.CardTrait.GOROSAURUS],
		"counter_power": 1000,
		"invasion_icon": 2,
		"description": "<Awakening4> This card gains +3000 counter power. (Active if your monster card is in zone 4 or beyond.)",
		"effect_script": "res://scripts/effects/ebp01/ebp01_067.gd"
	},
	{
		"id": "EBP01-068",
		"name": "Manda(1968)",
		"card_type": CardEnums.CardType.BATTLE,
		"rank": 3,
		"colors": [CardEnums.CardColor.WHITE],
		"traits": [CardEnums.CardTrait.MANDA],
		"counter_power": 1000,
		"invasion_icon": 1,
		"description": "If this card is in a zone adjacent to your monster card, this card gains +3000 counter power.",
		"effect_script": "res://scripts/effects/ebp01/ebp01_068.gd"
	},
	{
		"id": "EBP01-069",
		"name": "Varan",
		"card_type": CardEnums.CardType.BATTLE,
		"rank": 4,
		"colors": [CardEnums.CardColor.WHITE],
		"traits": [CardEnums.CardTrait.VARAN],
		"counter_power": 3000,
		"invasion_icon": 1,
		"description": "<Awakening6> <Enter> Draw 2 cards, then discard 2 cards. (Active if your monster card is in zone 6 or beyond.)",
		"effect_script": "res://scripts/effects/ebp01/ebp01_069.gd"
	},
	{
		"id": "EBP01-070",
		"name": "Baragon(1968)",
		"card_type": CardEnums.CardType.BATTLE,
		"rank": 5,
		"colors": [CardEnums.CardColor.WHITE],
		"traits": [CardEnums.CardTrait.BARAGON],
		"counter_power": 4000,
		"invasion_icon": 1,
		"description": "<Enter> Look at the top card of your deck. You may send it to your discard pile or place it back on top of your deck.",
		"effect_script": "res://scripts/effects/ebp01/ebp01_070.gd"
	},
	{
		"id": "EBP01-071",
		"name": "Giant Condor",
		"card_type": CardEnums.CardType.BATTLE,
		"rank": 5,
		"colors": [CardEnums.CardColor.WHITE],
		"traits": [CardEnums.CardTrait.GIANT_CONDOR],
		"counter_power": 5000,
		"invasion_icon": 1,
		"description": "If this card is in the same column as your opponent’s monster card, this card gains +5000 counter power.\nWhen your opponent's <Rage> is increased, <Destroy> this card.",
		"effect_script": "res://scripts/effects/ebp01/ebp01_071.gd"
	},
	{
		"id": "EBP01-072",
		"name": "Gigan(2022)",
		"card_type": CardEnums.CardType.BATTLE,
		"rank": 6,
		"colors": [CardEnums.CardColor.WHITE],
		"traits": [CardEnums.CardTrait.GIGAN, CardEnums.CardTrait.WEAPON, CardEnums.CardTrait.FEST],
		"counter_power": 5000,
		"invasion_icon": 1,
		"description": "<Enter> If this card is in the same column as your opponent’s monster card, send the top card of your deck to your discard pile. If it is a battle card, move your opponent’s monster card with 50,000 or lower threat level backward by 1 zone.",
		"effect_script": "res://scripts/effects/ebp01/ebp01_072.gd"
	},
	{
		"id": "EBP01-073",
		"name": "Godzilla Against Mechagodzilla",
		"common_names": ["GAM"],
		"card_type": CardEnums.CardType.BATTLE,
		"rank": 7,
		"colors": [CardEnums.CardColor.WHITE],
		"traits": [CardEnums.CardTrait.GODZILLA, CardEnums.CardTrait.MECHAGODZILLA, CardEnums.CardTrait.WEAPON],
		"counter_power": 10000,
		"invasion_icon": 2,
		"description": "This card cannot be played if you have 7 or fewer monster cards in your discard pile.\nWhen your monster card invades, if there are no monster cards under this card, you may place 1 monster card from your discard pile under this card to set your opponent’s <Rage> to 0.",
		"effect_script": "res://scripts/effects/ebp01/ebp01_073.gd"
	},
	{
		"id": "EBP01-074",
		"name": "King Ghidorah(2024)",
		"card_type": CardEnums.CardType.BATTLE,
		"rank": 8,
		"colors": [CardEnums.CardColor.WHITE],
		"traits": [CardEnums.CardTrait.KING_GHIDORAH, CardEnums.CardTrait.FEST],
		"counter_power": 8000,
		"invasion_icon": 1,
		"description": "If you have a card named 「Gravity Beam」 in play, this card gains +20,000 counter power.",
		"effect_script": "res://scripts/effects/ebp01/ebp01_074.gd"
	},
	{
		"id": "EBP01-075",
		"name": "Godzilla, King of the Monsters",
		"common_names": ["KOTM"],
		"card_type": CardEnums.CardType.BATTLE,
		"rank": 8,
		"colors": [CardEnums.CardColor.WHITE],
		"traits": [CardEnums.CardTrait.GODZILLA],
		"counter_power": 5000,
		"invasion_icon": 2,
		"description": "This card gains +3000 counter power for each of your monster card's <Rage> .\nIf your monster card has 3 or more <Rage> , and this card is in zones 1-5, this card cannot be <Destroy> by your opponent’s effects.\n<Awakening8> You can play this card with its rank reduced by 4. (Active if your monster card is in zone 8. After being played, this card is rank 8.)",
		"effect_script": "res://scripts/effects/ebp01/ebp01_075.gd"
	},
	{
		"id": "EBP01-076",
		"name": "Destroy All Monsters",
		"common_names": ["DAM"],
		"card_type": CardEnums.CardType.STRATEGY,
		"rank": 2,
		"colors": [CardEnums.CardColor.WHITE],
		"invasion_icon": 1,
		"description": "When your monster card invades this turn, <Destroy> 1 of your opponent’s battle cards.",
		"effect_script": "res://scripts/effects/ebp01/ebp01_076.gd"
	},
	{
		"id": "EBP01-077",
		"name": "Oxygen Destroyer",
		"common_names": ["OD"],
		"card_type": CardEnums.CardType.STRATEGY,
		"rank": 4,
		"colors": [CardEnums.CardColor.WHITE],
		"invasion_icon": 1,
		"description": "If your opponent has 2 or fewer <Rage> , move your opponent's monster card as though it were countered. (Do not play the next monster card from your monster deck.)",
		"effect_script": "res://scripts/effects/ebp01/ebp01_077.gd"
	},
	{
		"id": "EBP01-078",
		"name": "Godzilla Attacks",
		"card_type": CardEnums.CardType.STRATEGY,
		"rank": 4,
		"colors": [CardEnums.CardColor.WHITE],
		"invasion_icon": 2,
		"description": "Advance your monster card to zone 6.",
		"effect_script": "res://scripts/effects/ebp01/ebp01_078.gd"
	},
	{
		"id": "EBP01-079",
		"name": "Gravity Beam",
		"card_type": CardEnums.CardType.STRATEGY,
		"rank": 5,
		"colors": [CardEnums.CardColor.WHITE],
		"invasion_icon": 2,
		"description": "Your opponent discards cards until they have 3 cards remaining in their hand.",
		"effect_script": "res://scripts/effects/ebp01/ebp01_079.gd"
	},
	{
		"id": "EBP01-080",
		"name": "Godzilla and its son on Monster Island",
		"common_names": ["GAISOMI"],
		"card_type": CardEnums.CardType.STRATEGY,
		"rank": 6,
		"colors": [CardEnums.CardColor.WHITE],
		"invasion_icon": 1,
		"description": "If your opponent has a strategy card in play, you can play this from your hand with its rank reduced by 2.\nWhile this card is in the strategy zone, your rank 5 or lower battle cards in zones 1-5 cannot be <Destroy> by your opponent’s effects.",
		"effect_script": "res://scripts/effects/ebp01/ebp01_080.gd"
	},
]
