extends RefCounted
## EBP03: Booster Pack 03 — card data only, split verbatim from card_data.gd.

var CARDS: Array[Dictionary] = [
	{
		"id": "EBP03-001",
		"name": "Godzilla(2001)",
		"card_type": CardEnums.CardType.MONSTER,
		"rank": 1,
		"colors": [CardEnums.CardColor.RED],
		"traits": [CardEnums.CardTrait.GODZILLA],
		"threat_level": 4000,
		"invasion_icon": 1,
		"effect_script": "res://scripts/effects/ebp03/ebp03_001.gd",
		"description": "<Awakening4> At the beginning of your end phase, you may discard 1 rank 5 or higher battle card from your hand. If you do, this card advances 1 zone.\n<Awakening6> This card gains +5000 threat level."
	},
	{
		"id": "EBP03-002",
		"name": "Godzilla(2001)",
		"card_type": CardEnums.CardType.MONSTER,
		"rank": 2,
		"colors": [CardEnums.CardColor.RED],
		"traits": [CardEnums.CardTrait.GODZILLA],
		"threat_level": 14000,
		"invasion_icon": 2,
		"effect_script": "res://scripts/effects/ebp03/ebp03_002.gd",
		"description": "<Opponent’s Turn> <Awakening4> At the beginning of the counter phase, you may discard 1 rank 5 or higher battle card from your hand. If you do, increase this card’s <Rage> by 1.\n<Awakening8> At the beginning of your counter phase, you may discard 1 rank 5 or higher battle card from your hand. If you do, increase this card’s <Rage> by 2."
	},
	{
		"id": "EBP03-003",
		"name": "Godzilla(2001)",
		"card_type": CardEnums.CardType.MONSTER,
		"rank": 3,
		"colors": [CardEnums.CardColor.RED],
		"traits": [CardEnums.CardTrait.GODZILLA],
		"threat_level": 22000,
		"invasion_icon": 1,
		"effect_script": "res://scripts/effects/ebp03/ebp03_003.gd",
		"description": "<Burst2> (You can play this card from rank II. If you do, send this card to your discard pile at the beginning of your next end phase.)\n<Awakening8> At the beginning of your counter phase, you may discard 1 rank 5 or higher battle card from your hand. If you do, increase this card’s <Rage> by 2, then <Destroy> all of your opponent’s rank 6 or lower battle cards. (Active if this card is in zone 8.)"
	},
	{
		"id": "EBP03-004",
		"name": "Godzilla(2001)",
		"card_type": CardEnums.CardType.MONSTER,
		"rank": 4,
		"colors": [CardEnums.CardColor.RED],
		"traits": [CardEnums.CardTrait.GODZILLA],
		"threat_level": 35000,
		"invasion_icon": 1,
		"description": "When this card invades, you may send the top card of your deck to your discard pile instead of discarding a card from your hand.\n<Opponent’s Turn> <Awakening4> This card’s <Rage> cannot be reduced by your opponent’s effects. (Active if this is in zone 4 or beyond.)",
		"effect_script": "res://scripts/effects/ebp03/ebp03_004.gd"
	},
	{
		"id": "EBP03-005",
		"name": "Godzilla(2001)",
		"card_type": CardEnums.CardType.MONSTER,
		"rank": 4,
		"colors": [CardEnums.CardColor.RED],
		"traits": [CardEnums.CardTrait.GODZILLA],
		"threat_level": 36000,
		"invasion_icon": 1,
		"effect_script": "res://scripts/effects/ebp03/ebp03_005.gd",
		"description": "<Burst3> (You can play this card from rank III. If you do, send this card to your discard pile at the beginning of your next end phase.)\n<Awakening8> At the beginning of your counter phase, you may discard 1 rank 5 or higher battle card from your hand. If you do, increase this card’s <Rage> by 3, then <Destroy> all of your opponent’s rank 7 or lower battle cards. (Active if this card is in zone 8.)"
	},
	{
		"id": "EBP03-006",
		"name": "Multi-purpose Fighting System-3",
		"card_type": CardEnums.CardType.MONSTER,
		"rank": 1,
		"colors": [CardEnums.CardColor.RED, CardEnums.CardColor.BLUE],
		"traits": [CardEnums.CardTrait.MECHAGODZILLA, CardEnums.CardTrait.WEAPON],
		"threat_level": 5000,
		"invasion_icon": 1,
		"resonance": {
			"main_monster_required_traits": [CardEnums.CardTrait.WEAPON, CardEnums.CardTrait.MECH],
			"main_battle_required_traits": [CardEnums.CardTrait.WEAPON, CardEnums.CardTrait.MECH],
		},
		"description": "<Resonance> Red/Blue\n・Monster cards in your deck must have <《Weapon》> or <《Mech》> .\n・Battle cards in your deck must have <《Weapon》> or <《Mech》> .\n(You can mix red, blue, and white, but your monster deck and main deck must satisfy the above.)"
	},
	{
		"id": "EBP03-007",
		"name": "Multi-purpose Fighting System-3",
		"card_type": CardEnums.CardType.MONSTER,
		"rank": 2,
		"colors": [CardEnums.CardColor.RED, CardEnums.CardColor.BLUE],
		"traits": [CardEnums.CardTrait.MECHAGODZILLA, CardEnums.CardTrait.WEAPON],
		"threat_level": 12000,
		"invasion_icon": 2,
		"effect_script": "res://scripts/effects/ebp03/ebp03_007.gd",
		"description": "<When Invading> Reveal from the top of your deck a number of cards equal to the rank of your opponent’s monster card. Add 1 red or blue battle card among them to your hand, then send the rest to your discard pile."
	},
	{
		"id": "EBP03-008",
		"name": "Multi-purpose Fighting System-3",
		"card_type": CardEnums.CardType.MONSTER,
		"rank": 3,
		"colors": [CardEnums.CardColor.RED, CardEnums.CardColor.BLUE],
		"traits": [CardEnums.CardTrait.MECHAGODZILLA, CardEnums.CardTrait.WEAPON],
		"threat_level": 21000,
		"invasion_icon": 1,
		"effect_script": "res://scripts/effects/ebp03/ebp03_008.gd",
		"description": "<Enter> If there is a blue battle card in your zones, <Destroy> 1 of your opponent’s rank 5 or lower battle cards.\n<Opponent’s Turn> At the beginning of the counter phase, if there is a red battle card in your zones, <Destroy> 1 of your opponent’s rank 5 or lower battle cards in the same column as this card."
	},
	{
		"id": "EBP03-009",
		"name": "Multi-purpose Fighting System-3",
		"card_type": CardEnums.CardType.MONSTER,
		"rank": 4,
		"colors": [CardEnums.CardColor.RED, CardEnums.CardColor.BLUE],
		"traits": [CardEnums.CardTrait.MECHAGODZILLA, CardEnums.CardTrait.WEAPON],
		"threat_level": 37000,
		"invasion_icon": 1,
		"effect_script": "res://scripts/effects/ebp03/ebp03_009.gd",
		"description": "<Enter> Choose 1 of your opponent’s zones in the same column as this card, then <Destroy> all of your opponent’s rank 6 or lower battle cards in that zone and zones adjacent to it."
	},
	{
		"id": "EBP03-010",
		"name": "Multi-purpose Fighting System-3",
		"card_type": CardEnums.CardType.MONSTER,
		"rank": 3,
		"colors": [CardEnums.CardColor.RED, CardEnums.CardColor.BLUE],
		"traits": [CardEnums.CardTrait.MECHAGODZILLA, CardEnums.CardTrait.WEAPON],
		"threat_level": 22000,
		"invasion_icon": 1,
		"effect_script": "res://scripts/effects/ebp03/ebp03_010.gd",
		"description": "<Enter> If there are 2 or more battle cards in your zones, your opponent discards cards until they have 4 cards remaining in their hand. If a battle card is discarded this way, increase this card’s <Rage> by 1."
	},
	{
		"id": "EBP03-011",
		"name": "Multi-purpose Fighting System-3",
		"card_type": CardEnums.CardType.MONSTER,
		"rank": 4,
		"colors": [CardEnums.CardColor.RED, CardEnums.CardColor.BLUE],
		"traits": [CardEnums.CardTrait.MECHAGODZILLA, CardEnums.CardTrait.WEAPON],
		"threat_level": 33000,
		"invasion_icon": 1,
		"effect_script": "res://scripts/effects/ebp03/ebp03_011.gd",
		"description": "<Burst3> (You can play this card from rank III. If you do, send this card to your discard pile at the beginning of your next end phase.)\n<Enter> Reveal from the top of your deck a number of cards equal to the rank of your opponent’s monster card. Add up to 1 red battle card and up to 1 blue battle card among them to your hand, then send the rest to your discard pile."
	},
	{
		"id": "EBP03-012",
		"name": "Godzilla(1993)",
		"card_type": CardEnums.CardType.MONSTER,
		"rank": 2,
		"colors": [CardEnums.CardColor.BLUE],
		"traits": [CardEnums.CardTrait.GODZILLA],
		"threat_level": 12000,
		"invasion_icon": 1,
		"effect_script": "res://scripts/effects/ebp03/ebp03_012.gd",
		"description": "<Enter> If you have 1 or fewer strategy cards in play, you may place up to 1 blue rank 6 or lower strategy card from your hand into your strategy zone and activate it."
	},
	{
		"id": "EBP03-013",
		"name": "Godzilla(1995)",
		"card_type": CardEnums.CardType.MONSTER,
		"rank": 4,
		"colors": [CardEnums.CardColor.BLUE],
		"traits": [CardEnums.CardTrait.GODZILLA],
		"threat_level": 50000,
		"invasion_icon": 1,
		"description": "<Enter> For the rest of the game, you have 3 strategy card zones. (It remains 3 even if this leaves play.)\n<Opponent’s Turn> At the beginning of the counter phase, if there are no cards in your strategy zones, you lose the game.",
		"effect_script": "res://scripts/effects/ebp03/ebp03_013.gd"
	},
	{
		"id": "EBP03-014",
		"name": "Godzilla(2002)",
		"card_type": CardEnums.CardType.MONSTER,
		"rank": 1,
		"colors": [CardEnums.CardColor.BLUE],
		"traits": [CardEnums.CardTrait.GODZILLA],
		"threat_level": 5000,
		"invasion_icon": 1,
		"effect_script": "res://scripts/effects/ebp03/ebp03_014.gd",
		"description": "At the beginning of your end phase, you may discard 1 battle card from your hand. If you do, draw 1 card."
	},
	{
		"id": "EBP03-015",
		"name": "Godzilla(2002)",
		"card_type": CardEnums.CardType.MONSTER,
		"rank": 2,
		"colors": [CardEnums.CardColor.BLUE],
		"traits": [CardEnums.CardTrait.GODZILLA],
		"threat_level": 9000,
		"invasion_icon": 1,
		"description": "Whenever you discard a battle card from your hand, reduce your opponent’s <Rage> by 1.",
		"effect_script": "res://scripts/effects/ebp03/ebp03_015.gd"
	},
	{
		"id": "EBP03-016",
		"name": "Godzilla(2003)",
		"card_type": CardEnums.CardType.MONSTER,
		"rank": 3,
		"colors": [CardEnums.CardColor.BLUE],
		"traits": [CardEnums.CardTrait.GODZILLA],
		"threat_level": 17000,
		"invasion_icon": 2,
		"description": "Whenever you discard a battle card from your hand, reduce your opponent’s <Rage> by 1. If your opponent’s <Rage> is 0, increase this card’s <Rage> by 1 instead.",
		"effect_script": "res://scripts/effects/ebp03/ebp03_016.gd"
	},
	{
		"id": "EBP03-017",
		"name": "Godzilla(2003)",
		"card_type": CardEnums.CardType.MONSTER,
		"rank": 4,
		"colors": [CardEnums.CardColor.BLUE],
		"traits": [CardEnums.CardTrait.GODZILLA],
		"threat_level": 29000,
		"invasion_icon": 1,
		"description": "Whenever you discard a battle card from your hand, reduce your opponent’s <Rage> by 1. If your opponent’s <Rage> is 0, increase this card’s <Rage> by 1 instead.\n<Enter> You may discard 1 battle card from your hand. If you do, <Destroy> 1 of your opponent’s rank 6 or lower battle cards.",
		"effect_script": "res://scripts/effects/ebp03/ebp03_017.gd"
	},
	{
		"id": "EBP03-018",
		"name": "Mothra(imago)(1996)",
		"card_type": CardEnums.CardType.MONSTER,
		"rank": 1,
		"colors": [CardEnums.CardColor.BLUE, CardEnums.CardColor.GREEN],
		"traits": [CardEnums.CardTrait.MOTHRA],
		"threat_level": 5000,
		"invasion_icon": 1,
		"resonance": {
			"main_monster_required_traits": [CardEnums.CardTrait.MOTHRA],
			"main_strategy_min_count": 10,
		},
		"description": "<Resonance> Blue/Green\n・Monster cards in your deck must have <《Mothra》> .\n・Your deck must contain at least 10 strategy cards.\n(You can mix blue, green, and white, but your monster deck and main deck must satisfy the above.)"
	},
	{
		"id": "EBP03-019",
		"name": "Mothra(larva)(1996)",
		"card_type": CardEnums.CardType.MONSTER,
		"rank": 2,
		"colors": [CardEnums.CardColor.BLUE, CardEnums.CardColor.GREEN],
		"traits": [CardEnums.CardTrait.MOTHRA],
		"threat_level": 14000,
		"invasion_icon": 2,
		"description": "When you successfully counter your opponent’s monster card, if you have a card with <Base> in play, increase this card’s <Rage> by 2.",
		"effect_script": "res://scripts/effects/ebp03/ebp03_019.gd"
	},
	{
		"id": "EBP03-020",
		"name": "Mothra Leo",
		"card_type": CardEnums.CardType.MONSTER,
		"rank": 3,
		"colors": [CardEnums.CardColor.BLUE, CardEnums.CardColor.GREEN],
		"traits": [CardEnums.CardTrait.MOTHRA],
		"threat_level": 23000,
		"invasion_icon": 1,
		"description": "When you successfully counter your opponent’s monster card, if you have a card with <Base> in play, <Destroy> 1 opponent’s rank 7 or lower battle card.",
		"effect_script": "res://scripts/effects/ebp03/ebp03_020.gd"
	},
	{
		"id": "EBP03-021",
		"name": "Rainbow Mothra",
		"card_type": CardEnums.CardType.MONSTER,
		"rank": 3,
		"colors": [CardEnums.CardColor.BLUE, CardEnums.CardColor.GREEN],
		"traits": [CardEnums.CardTrait.MOTHRA],
		"threat_level": 22000,
		"invasion_icon": 1,
		"effect_script": "res://scripts/effects/ebp03/ebp03_021.gd",
		"description": "<Enter> Return 1 strategy card with <Base> from your discard pile to your hand."
	},
	{
		"id": "EBP03-022",
		"name": "Aqua Mothra",
		"card_type": CardEnums.CardType.MONSTER,
		"rank": 4,
		"colors": [CardEnums.CardColor.BLUE, CardEnums.CardColor.GREEN],
		"traits": [CardEnums.CardTrait.MOTHRA],
		"threat_level": 34000,
		"invasion_icon": 1,
		"effect_script": "res://scripts/effects/ebp03/ebp03_022.gd",
		"description": "If you have a card with <Base> in play, this card gains +10,000 threat level."
	},
	{
		"id": "EBP03-023",
		"name": "Armor Mothra",
		"card_type": CardEnums.CardType.MONSTER,
		"rank": 4,
		"colors": [CardEnums.CardColor.BLUE, CardEnums.CardColor.GREEN],
		"traits": [CardEnums.CardTrait.MOTHRA],
		"threat_level": 31000,
		"invasion_icon": 1,
		"description": "<Enter> Evolve all of your <《Mothra》> battle cards with <Evolution> .\nWhen you successfully counter your opponent’s monster card, if you have a card with <Base> in play, retreat your opponent’s monster card back to zone 1.",
		"effect_script": "res://scripts/effects/ebp03/ebp03_023.gd"
	},
	{
		"id": "EBP03-024",
		"name": "Baragon(2001)",
		"card_type": CardEnums.CardType.MONSTER,
		"rank": 1,
		"colors": [CardEnums.CardColor.GREEN, CardEnums.CardColor.RED],
		"traits": [CardEnums.CardTrait.BARAGON, CardEnums.CardTrait.SACRED_GUARDIAN_BEASTS],
		"threat_level": 5000,
		"invasion_icon": 1,
		"resonance": {
			"main_monster_required_traits": [CardEnums.CardTrait.SACRED_GUARDIAN_BEASTS],
			"main_battle_min_rank": 5,
		},
		"description": "<Resonance> Green/Red\n・Monster cards in your deck must have <《Sacred Guardian Beasts》> .\n・Battle cards in your deck must be Rank 5 or higher.\n(You can mix green, red, and white, but your monster deck and main deck must satisfy the above.)"
	},
	{
		"id": "EBP03-025",
		"name": "Mothra(imago)(2001)",
		"card_type": CardEnums.CardType.MONSTER,
		"rank": 2,
		"colors": [CardEnums.CardColor.GREEN, CardEnums.CardColor.RED],
		"traits": [CardEnums.CardTrait.MOTHRA, CardEnums.CardTrait.SACRED_GUARDIAN_BEASTS],
		"threat_level": 11000,
		"invasion_icon": 1,
		"description": "<Your Turn> Reduce the rank of all battle cards in your opponent’s zones by 1.\n<Enter> You may place 1 monster card from your discard pile under this card. If you do, advance your opponent’s monster card to zone 5.",
		"effect_script": "res://scripts/effects/ebp03/ebp03_025.gd"
	},
	{
		"id": "EBP03-026",
		"name": "Mothra(imago)(2001)",
		"card_type": CardEnums.CardType.MONSTER,
		"rank": 3,
		"colors": [CardEnums.CardColor.GREEN, CardEnums.CardColor.RED],
		"traits": [CardEnums.CardTrait.MOTHRA, CardEnums.CardTrait.SACRED_GUARDIAN_BEASTS],
		"threat_level": 19000,
		"invasion_icon": 1,
		"description": "<Your Turn> If there are 3 or more cards under this card, reduce the rank of all battle cards in your opponent’s zones by 2.\n<Enter> You may place 2 monster cards from your discard pile under this card. If you do, reduce your opponent’s <Rage> by 1.",
		"effect_script": "res://scripts/effects/ebp03/ebp03_026.gd"
	},
	{
		"id": "EBP03-027",
		"name": "Ghidorah(2001)",
		"card_type": CardEnums.CardType.MONSTER,
		"rank": 3,
		"colors": [CardEnums.CardColor.GREEN, CardEnums.CardColor.RED],
		"traits": [CardEnums.CardTrait.GHIDORAH, CardEnums.CardTrait.SACRED_GUARDIAN_BEASTS],
		"threat_level": 23000,
		"invasion_icon": 1,
		"description": "<Your Turn> If there are 3 or more cards under this card, reduce the rank of all battle cards in your opponent’s zones by 2.\n<When Invading> If there are 5 or more cards under this card, your opponent discards cards until they have 4 cards remaining in their hand.",
		"effect_script": "res://scripts/effects/ebp03/ebp03_027.gd"
	},
	{
		"id": "EBP03-028",
		"name": "Thousand-Year Dragon King Ghidorah",
		"card_type": CardEnums.CardType.MONSTER,
		"rank": 4,
		"colors": [CardEnums.CardColor.GREEN, CardEnums.CardColor.RED],
		"traits": [CardEnums.CardTrait.KING_GHIDORAH, CardEnums.CardTrait.SACRED_GUARDIAN_BEASTS],
		"threat_level": 32000,
		"invasion_icon": 2,
		"description": "<Your Turn> If there are 5 or more cards under this card, reduce the rank of all battle cards in your opponent’s zones by 3.\n<Opponent’s Turn> At the beginning of the counter phase, you may place 3 monster cards from your discard pile under this card. If you do, <Destroy> all rank 5 or lower battle cards in your opponent’s zones 1–5.",
		"effect_script": "res://scripts/effects/ebp03/ebp03_028.gd"
	},
	{
		"id": "EBP03-029",
		"name": "Thousand-Year Dragon King Ghidorah",
		"card_type": CardEnums.CardType.MONSTER,
		"rank": 4,
		"colors": [CardEnums.CardColor.GREEN, CardEnums.CardColor.RED],
		"traits": [CardEnums.CardTrait.KING_GHIDORAH, CardEnums.CardTrait.SACRED_GUARDIAN_BEASTS],
		"threat_level": 35000,
		"invasion_icon": 1,
		"description": "<Your Turn> If there are 5 or more cards under this card, reduce the rank of all battle cards in your opponent’s zones by 3.\n<When Invading> If there are 7 or more cards under this card, choose one:\n・ <Destroy> all battle cards of both players.\n・Each player discards cards until they have 2 cards remaining in their hand.\n・Reduce each player’s monster card’s <Rage> by 2.",
		"effect_script": "res://scripts/effects/ebp03/ebp03_029.gd"
	},
	{
		"id": "EBP03-030",
		"name": "SHIRASAGI : AC-3",
		"card_type": CardEnums.CardType.BATTLE,
		"rank": 2,
		"colors": [CardEnums.CardColor.RED],
		"traits": [CardEnums.CardTrait.WEAPON],
		"counter_power": 0,
		"invasion_icon": 1,
		"effect_script": "res://scripts/effects/ebp03/ebp03_030.gd",
		"description": "Your <《Mechagodzilla》> battle cards in your zone 8 gain +3000 counter power.\n<Enter> You may move 1 other battle card in your zones to an unoccupied zone."
	},
	{
		"id": "EBP03-031",
		"name": "MBT-MB90",
		"card_type": CardEnums.CardType.BATTLE,
		"rank": 3,
		"colors": [CardEnums.CardColor.RED],
		"traits": [CardEnums.CardTrait.WEAPON],
		"counter_power": 1000,
		"invasion_icon": 1,
		"unlimited_copies": true,
		"effect_script": "res://scripts/effects/ebp03/ebp03_031.gd",
		"description": "You may have any number of this card in your deck.\n<Enter> Look at the top card of your deck. You may send it to your discard pile or place it back on top of your deck."
	},
	{
		"id": "EBP03-032",
		"name": "Mechagodzilla(1974)",
		"card_type": CardEnums.CardType.BATTLE,
		"rank": 4,
		"colors": [CardEnums.CardColor.RED],
		"traits": [CardEnums.CardTrait.MECHAGODZILLA, CardEnums.CardTrait.WEAPON],
		"counter_power": 3000,
		"invasion_icon": 1,
		"effect_script": "res://scripts/effects/ebp03/ebp03_032.gd",
		"description": "At the beginning of your counter phase, if this card is in a zone adjacent to your monster card, you may discard all the cards in your hand. If you do, for the rest of the turn, this card gains +1000 counter power for each card discarded this way."
	},
	{
		"id": "EBP03-033",
		"name": "Mechagodzilla(1975)",
		"card_type": CardEnums.CardType.BATTLE,
		"rank": 5,
		"colors": [CardEnums.CardColor.RED],
		"traits": [CardEnums.CardTrait.MECHAGODZILLA, CardEnums.CardTrait.WEAPON],
		"counter_power": 2000,
		"invasion_icon": 1,
		"effect_script": "res://scripts/effects/ebp03/ebp03_033.gd",
		"description": "<Enter> You may discard 1 rank 5 or higher battle card from your hand. If you do, search your deck for up to 1 card named “Space Beam”, reveal it, add it to your hand, then shuffle your deck."
	},
	{
		"id": "EBP03-034",
		"name": "Jet Jaguar(1973)",
		"card_type": CardEnums.CardType.BATTLE,
		"rank": 5,
		"colors": [CardEnums.CardColor.RED],
		"traits": [CardEnums.CardTrait.JET_JAGUAR, CardEnums.CardTrait.MECH],
		"counter_power": 4000,
		"invasion_icon": 1,
		"effect_script": "res://scripts/effects/ebp03/ebp03_034.gd",
		"description": "<Enter> You may discard 1 strategy card from your hand. If you do, reduce your opponent’s <Rage> by 1."
	},
	{
		"id": "EBP03-035",
		"name": "Satsuma",
		"card_type": CardEnums.CardType.BATTLE,
		"rank": 5,
		"colors": [CardEnums.CardColor.RED],
		"traits": [CardEnums.CardTrait.WEAPON],
		"counter_power": 5000,
		"invasion_icon": 2,
		"effect_script": "res://scripts/effects/ebp03/ebp03_035.gd",
		"description": "<Enter> If this card is in the same column as your opponent’s monster card, you may discard 1 strategy card from your hand. If you do, advance your monster card to zone 6."
	},
	{
		"id": "EBP03-036",
		"name": "Moguera",
		"card_type": CardEnums.CardType.BATTLE,
		"rank": 6,
		"colors": [CardEnums.CardColor.RED],
		"traits": [CardEnums.CardTrait.MOGUERA, CardEnums.CardTrait.WEAPON],
		"counter_power": 4000,
		"invasion_icon": 2,
		"effect_script": "res://scripts/effects/ebp03/ebp03_036.gd",
		"description": "<Enter> If this card was played from your hand and is in zone 8, search your deck for up to 1 <《Moguera》> battle card, play it, then shuffle your deck."
	},
	{
		"id": "EBP03-037",
		"name": "Godzilla(2001)",
		"card_type": CardEnums.CardType.BATTLE,
		"rank": 6,
		"colors": [CardEnums.CardColor.RED],
		"traits": [CardEnums.CardTrait.GODZILLA],
		"counter_power": 5000,
		"invasion_icon": 1,
		"effect_script": "res://scripts/effects/ebp03/ebp03_037.gd",
		"description": "<Awakening8> <Enter> Increase your monster card’s <Rage> by 1.\n<Awakening8> This card gains +5000 counter power."
	},
	{
		"id": "EBP03-038",
		"name": "Multi-purpose Fighting System-3",
		"card_type": CardEnums.CardType.BATTLE,
		"rank": 6,
		"colors": [CardEnums.CardColor.RED],
		"traits": [CardEnums.CardTrait.MECHAGODZILLA, CardEnums.CardTrait.WEAPON],
		"counter_power": 8000,
		"invasion_icon": 1,
		"effect_script": "res://scripts/effects/ebp03/ebp03_038.gd",
		"description": "At the beginning of your counter phase, if your opponent has 2 or more <Rage> , <Destroy> all of your battle cards in zones adjacent to this card."
	},
	{
		"id": "EBP03-039",
		"name": "Godzilla(2016) 4th Form",
		"card_type": CardEnums.CardType.BATTLE,
		"rank": 7,
		"colors": [CardEnums.CardColor.RED],
		"traits": [CardEnums.CardTrait.GODZILLA, CardEnums.CardTrait.FOURTH_FORM],
		"counter_power": 5000,
		"invasion_icon": 2,
		"description": "Whenever your card is sent from a strategy zone to the discard pile, draw 1 card. (Also triggers when a strategy card is destroyed)\nIf there are 5 or more strategy cards in your discard pile, this card gains +5000 counter power.",
		"effect_script": "res://scripts/effects/ebp03/ebp03_039.gd"
	},
	{
		"id": "EBP03-040",
		"name": "Mechagodzilla(1975)",
		"card_type": CardEnums.CardType.BATTLE,
		"rank": 7,
		"colors": [CardEnums.CardColor.RED],
		"traits": [CardEnums.CardTrait.MECHAGODZILLA, CardEnums.CardTrait.WEAPON],
		"counter_power": 6000,
		"invasion_icon": 1,
		"effect_script": "res://scripts/effects/ebp03/ebp03_040.gd",
		"description": "At the beginning of your counter phase, you may move this card to an unoccupied zone.\nIf this is in the same column as your opponent’s monster card, this card gains +3000 counter power."
	},
	{
		"id": "EBP03-041",
		"name": "Godzilla(2023)",
		"card_type": CardEnums.CardType.BATTLE,
		"rank": 8,
		"colors": [CardEnums.CardColor.RED],
		"traits": [CardEnums.CardTrait.GODZILLA],
		"counter_power": 11000,
		"invasion_icon": 1,
		"description": "<Enter> If this is in the same column as your opponent’s monster card and your monster card has 2 or more <Rage> , reduce your opponent’s <Rage> by 2.\nWhen this card would be <Destroy> , put this card on the bottom of your deck instead.",
		"effect_script": "res://scripts/effects/ebp03/ebp03_041.gd"
	},
	{
		"id": "EBP03-042",
		"name": "Ghogo",
		"card_type": CardEnums.CardType.BATTLE,
		"rank": 2,
		"colors": [CardEnums.CardColor.BLUE],
		"traits": [CardEnums.CardTrait.GHOGO],
		"counter_power": 1000,
		"invasion_icon": 1,
		"description": "When your monster card invades, if this is in zone 8, you may put this card under one of your <《Mothra》> battle cards with <Evolution> . If you do, evolve that <《Mothra》> battle card.",
		"effect_script": "res://scripts/effects/ebp03/ebp03_042.gd"
	},
	{
		"id": "EBP03-043",
		"name": "Star Falcon",
		"card_type": CardEnums.CardType.BATTLE,
		"rank": 3,
		"colors": [CardEnums.CardColor.BLUE],
		"traits": [CardEnums.CardTrait.WEAPON],
		"counter_power": 2000,
		"invasion_icon": 1,
		"description": "<Awakening4> At the beginning of your counter phase, you may place this card under a card named “Land Moguera” in your zones. If you do, search your deck for up to 1 <《Moguera》> battle card, play it on top of the card named “Land Moguera” you chose for this effect, then shuffle your deck. (Active if your monster card is in zone 4 or beyond.)",
		"effect_script": "res://scripts/effects/ebp03/ebp03_043.gd"
	},
	{
		"id": "EBP03-044",
		"name": "Mothra(larva)(1992)",
		"card_type": CardEnums.CardType.BATTLE,
		"rank": 3,
		"colors": [CardEnums.CardColor.BLUE],
		"traits": [CardEnums.CardTrait.MOTHRA],
		"counter_power": 3000,
		"invasion_icon": 2,
		"evolution_rank": 7,
		"evolution_trait": CardEnums.CardTrait.MOTHRA,
		"description": "<Evolution7> <《Mothra》> (At the beginning of your main phase, you may play a rank 7 or lower <《Mothra》> battle card from your deck by placing it on top of this card.)",
		"effect_script": "res://scripts/effects/ebp03/ebp03_044.gd"
	},
	{
		"id": "EBP03-045",
		"name": "Mothra(larva)(2003)",
		"card_type": CardEnums.CardType.BATTLE,
		"rank": 4,
		"colors": [CardEnums.CardColor.BLUE],
		"traits": [CardEnums.CardTrait.MOTHRA],
		"counter_power": 2000,
		"invasion_icon": 1,
		"effect_script": "res://scripts/effects/ebp03/ebp03_045.gd",
		"description": "If this card is in a zone adjacent to your monster card, this card gains +3000 counter power."
	},
	{
		"id": "EBP03-046",
		"name": "Land Moguera",
		"card_type": CardEnums.CardType.BATTLE,
		"rank": 5,
		"colors": [CardEnums.CardColor.BLUE],
		"traits": [CardEnums.CardTrait.WEAPON],
		"counter_power": 3000,
		"invasion_icon": 1,
		"effect_script": "res://scripts/effects/ebp03/ebp03_046.gd",
		"description": "<Awakening4> <Enter> If “Star Falcon” is in your zones, choose one:\n・ <Destroy> 1 of your opponent’s strategy cards.\n・Reduce your opponent’s <Rage> by 1."
	},
	{
		"id": "EBP03-047",
		"name": "Garuda",
		"card_type": CardEnums.CardType.BATTLE,
		"rank": 5,
		"colors": [CardEnums.CardColor.BLUE],
		"traits": [CardEnums.CardTrait.WEAPON],
		"counter_power": 4000,
		"invasion_icon": 2,
		"effect_script": "res://scripts/effects/ebp03/ebp03_047.gd",
		"description": "At the beginning of your counter phase, if this card is in the same column as your opponent’s monster card, you may discard 1 battle card with <《Weapon》> or <《Mech》> from your hand. If you do, search your deck for up to 1 battle card named “Super Mechagodzilla”, play it on top of this card, then shuffle your deck."
	},
	{
		"id": "EBP03-048",
		"name": "Mechagodzilla(1993)",
		"card_type": CardEnums.CardType.BATTLE,
		"rank": 6,
		"colors": [CardEnums.CardColor.BLUE],
		"traits": [CardEnums.CardTrait.MECHAGODZILLA, CardEnums.CardTrait.WEAPON],
		"counter_power": 4000,
		"invasion_icon": 1,
		"effect_script": "res://scripts/effects/ebp03/ebp03_048.gd",
		"description": "<Enter> If there are 2 or more other battle cards in your zones, reduce your opponent’s <Rage> by 1."
	},
	{
		"id": "EBP03-049",
		"name": "Godzilla(2002)",
		"card_type": CardEnums.CardType.BATTLE,
		"rank": 6,
		"colors": [CardEnums.CardColor.BLUE],
		"traits": [CardEnums.CardTrait.GODZILLA],
		"counter_power": 5000,
		"invasion_icon": 1,
		"effect_script": "res://scripts/effects/ebp03/ebp03_049.gd",
		"description": "<Enter> If this card is in zone 8, draw 2 cards, then discard 2 cards."
	},
	{
		"id": "EBP03-050",
		"name": "Rainbow Mothra",
		"card_type": CardEnums.CardType.BATTLE,
		"rank": 7,
		"colors": [CardEnums.CardColor.BLUE],
		"traits": [CardEnums.CardTrait.MOTHRA],
		"counter_power": 6000,
		"invasion_icon": 1,
		"evolution_rank": 8,
		"evolution_trait": CardEnums.CardTrait.MOTHRA,
		"effect_script": "res://scripts/effects/ebp03/ebp03_050.gd",
		"description": "<Enter> If you have a card with <Base> in play, an opponent’s monster card with 20,000 or less threat level retreats backward by 1 zone.\n<Evolution8> <《Mothra》> (At the beginning of your main phase, you may play a rank 8 or lower <《Mothra》> battle card from your deck by placing it on top of this card.)"
	},
	{
		"id": "EBP03-051",
		"name": "Godzilla Jr.",
		"card_type": CardEnums.CardType.BATTLE,
		"rank": 7,
		"colors": [CardEnums.CardColor.BLUE],
		"traits": [CardEnums.CardTrait.GODZILLA_JR],
		"counter_power": 6000,
		"invasion_icon": 2,
		"effect_script": "res://scripts/effects/ebp03/ebp03_051.gd",
		"description": "If you would play this card on top of your <《Little Godzilla》> battle card, you may play this from your hand with its rank reduced by 2. (After being played, this card is rank 7.)\nThis card gains +5000 counter power for each card under it."
	},
	{
		"id": "EBP03-052",
		"name": "M.O.G.U.E.R.A.",
		"card_type": CardEnums.CardType.BATTLE,
		"rank": 7,
		"colors": [CardEnums.CardColor.BLUE],
		"traits": [CardEnums.CardTrait.MOGUERA, CardEnums.CardTrait.WEAPON],
		"counter_power": 7000,
		"invasion_icon": 2,
		"description": "When this card would be <Destroy> by an opponent’s effect, add all cards under this card to your hand.\n<Awakening6> <Enter> If there are no cards under this card, search your deck for up to 1 card named “Land Moguera” and up to 1 card named “Star Falcon”, place them under this card, then shuffle your deck.",
		"effect_script": "res://scripts/effects/ebp03/ebp03_052.gd"
	},
	{
		"id": "EBP03-053",
		"name": "Super Mechagodzilla",
		"card_type": CardEnums.CardType.BATTLE,
		"rank": 8,
		"colors": [CardEnums.CardColor.BLUE],
		"traits": [CardEnums.CardTrait.MECHAGODZILLA, CardEnums.CardTrait.WEAPON],
		"counter_power": 8000,
		"invasion_icon": 1,
		"description": "While your opponent’s <Rage> is 0, this card cannot be <Destroy> by opponent’s effects.\nIf this card is in the same column as your opponent’s monster card, this card gains +3000 counter power for each of your opponent’s <Rage> .",
		"effect_script": "res://scripts/effects/ebp03/ebp03_053.gd"
	},
	{
		"id": "EBP03-054",
		"name": "Eternal Mothra",
		"card_type": CardEnums.CardType.BATTLE,
		"rank": 8,
		"colors": [CardEnums.CardColor.BLUE],
		"traits": [CardEnums.CardTrait.MOTHRA],
		"counter_power": 10000,
		"invasion_icon": 1,
		"effect_script": "res://scripts/effects/ebp03/ebp03_054.gd",
		"description": "<Enter> If this card is in zone 8 and you have a card with <Base> in play, an opponent’s monster card with 60,000 or less threat level retreats backward by 1 zone."
	},
	{
		"id": "EBP03-055",
		"name": "Primitive Mothra",
		"card_type": CardEnums.CardType.BATTLE,
		"rank": 3,
		"colors": [CardEnums.CardColor.GREEN],
		"traits": [CardEnums.CardTrait.MOTHRA],
		"counter_power": 2000,
		"invasion_icon": 1,
		"effect_script": "res://scripts/effects/ebp03/ebp03_055.gd",
		"description": "<Enter> You may put up to 1 <《Mothra》> battle card from your discard pile on top of your deck."
	},
	{
		"id": "EBP03-056",
		"name": "Manda(2004)",
		"card_type": CardEnums.CardType.BATTLE,
		"rank": 3,
		"colors": [CardEnums.CardColor.GREEN],
		"traits": [CardEnums.CardTrait.MANDA, CardEnums.CardTrait.FINAL_WARS],
		"counter_power": 2000,
		"invasion_icon": 1,
		"effect_script": "res://scripts/effects/ebp03/ebp03_056.gd",
		"description": "If this card is in the same column as your opponent’s monster card, this card gains +3000 counter power."
	},
	{
		"id": "EBP03-057",
		"name": "Desghidorah",
		"card_type": CardEnums.CardType.BATTLE,
		"rank": 4,
		"colors": [CardEnums.CardColor.GREEN],
		"traits": [CardEnums.CardTrait.DESGHIDORAH],
		"counter_power": 2000,
		"invasion_icon": 1,
		"effect_script": "res://scripts/effects/ebp03/ebp03_057.gd",
		"description": "<Enter> If your opponent has 3 or more unoccupied zones, <Destroy> 1 of your opponent’s strategy cards.\nIf your opponent has no strategy cards in play, this card gains +3000 counter power."
	},
	{
		"id": "EBP03-058",
		"name": "Zilla",
		"card_type": CardEnums.CardType.BATTLE,
		"rank": 4,
		"colors": [CardEnums.CardColor.GREEN],
		"traits": [CardEnums.CardTrait.ZILLA, CardEnums.CardTrait.FINAL_WARS],
		"counter_power": 5000,
		"invasion_icon": 1,
		"effect_script": "res://scripts/effects/ebp03/ebp03_058.gd",
		"description": "At the beginning of your end phase, move this card to an adjacent zone horizontal to the zone this card currently occupies. Then, if this card is in a zone adjacent to your monster card, <Destroy> this card.."
	},
	{
		"id": "EBP03-059",
		"name": "Cretaceous King Ghidorah(1998)",
		"card_type": CardEnums.CardType.BATTLE,
		"rank": 5,
		"colors": [CardEnums.CardColor.GREEN],
		"traits": [CardEnums.CardTrait.KING_GHIDORAH],
		"counter_power": 3000,
		"invasion_icon": 1,
		"effect_script": "res://scripts/effects/ebp03/ebp03_059.gd",
		"description": "<Revenge> Return up to 1 <《King Ghidorah》> monster card from your discard pile to your hand. (Activates when destroyed by a card effect or monster card movement.)"
	},
	{
		"id": "EBP03-060",
		"name": "Mothra(imago)(1961)",
		"card_type": CardEnums.CardType.BATTLE,
		"rank": 5,
		"colors": [CardEnums.CardColor.GREEN],
		"traits": [CardEnums.CardTrait.MOTHRA],
		"counter_power": 5000,
		"invasion_icon": 2,
		"effect_script": "res://scripts/effects/ebp03/ebp03_060.gd",
		"description": "<Revenge> Reduce your opponent’s <Rage> by 1. (Activates when destroyed by a card effect or monster card movement.)"
	},
	{
		"id": "EBP03-061",
		"name": "Dagahra",
		"card_type": CardEnums.CardType.BATTLE,
		"rank": 6,
		"colors": [CardEnums.CardColor.GREEN],
		"traits": [CardEnums.CardTrait.DAGAHRA],
		"counter_power": 3000,
		"invasion_icon": 1,
		"description": "When you discard this card from your hand for your monster card’s invasion, you may play this card from your discard pile.\n<Awakening6> This card gains +3000 counter power. (Active if your monster card is in zone 6 or beyond.)",
		"effect_script": "res://scripts/effects/ebp03/ebp03_061.gd"
	},
	{
		"id": "EBP03-062",
		"name": "Baragon(2001)",
		"card_type": CardEnums.CardType.BATTLE,
		"rank": 6,
		"colors": [CardEnums.CardColor.GREEN],
		"traits": [CardEnums.CardTrait.BARAGON, CardEnums.CardTrait.SACRED_GUARDIAN_BEASTS],
		"counter_power": 5000,
		"invasion_icon": 1,
		"description": "When your opponent’s monster card invades, <Destroy> this card.\n<Revenge> Return up to 1 <《Sacred Guardian Beasts》> monster card from your discard pile to your hand. (Activates when destroyed by a card effect or monster card movement.)",
		"effect_script": "res://scripts/effects/ebp03/ebp03_062.gd"
	},
	{
		"id": "EBP03-063",
		"name": "King Ghidorah(1998)",
		"card_type": CardEnums.CardType.BATTLE,
		"rank": 6,
		"colors": [CardEnums.CardColor.GREEN],
		"traits": [CardEnums.CardTrait.KING_GHIDORAH],
		"counter_power": 6000,
		"invasion_icon": 2,
		"description": "<Your Turn> <Awakening4> When your monster card is played, you may play this card from your discard pile. (Active if your monster card is in zone 4 or beyond.)",
		"effect_script": "res://scripts/effects/ebp03/ebp03_063.gd"
	},
	{
		"id": "EBP03-064",
		"name": "Mothra(imago)(2001)",
		"card_type": CardEnums.CardType.BATTLE,
		"rank": 7,
		"colors": [CardEnums.CardColor.GREEN],
		"traits": [CardEnums.CardTrait.MOTHRA, CardEnums.CardTrait.SACRED_GUARDIAN_BEASTS],
		"counter_power": 6000,
		"invasion_icon": 1,
		"description": "<Enter> If an opponent's battle card was <Destroy> this turn, you may place 1 battle card from your discard pile under this card.\n<Awakening4> If there is a card under this card, this card gains +3000 counter power.\n<Awakening6> If there is a card under this card, this card gains an additional +3000 counter power.",
		"effect_script": "res://scripts/effects/ebp03/ebp03_064.gd"
	},
	{
		"id": "EBP03-065",
		"name": "King Ghidorah(1998)",
		"card_type": CardEnums.CardType.BATTLE,
		"rank": 7,
		"colors": [CardEnums.CardColor.GREEN],
		"traits": [CardEnums.CardTrait.KING_GHIDORAH],
		"counter_power": 7000,
		"invasion_icon": 1,
		"effect_script": "res://scripts/effects/ebp03/ebp03_065.gd",
		"description": "If there are 5 or more cards under your monster card, this card gains +3000 counter power."
	},
	{
		"id": "EBP03-066",
		"name": "Thousand-Year Dragon King Ghidorah",
		"card_type": CardEnums.CardType.BATTLE,
		"rank": 8,
		"colors": [CardEnums.CardColor.GREEN],
		"traits": [CardEnums.CardTrait.KING_GHIDORAH, CardEnums.CardTrait.SACRED_GUARDIAN_BEASTS],
		"counter_power": 9000,
		"invasion_icon": 1,
		"effect_script": "res://scripts/effects/ebp03/ebp03_066.gd",
		"description": "If your opponent has 2 or more strategy cards in play, you may play this card from your hand with its rank reduced by 2. (After being played, this card is rank 8.)\n<Enter> <Destroy> 1 of your opponent’s strategy cards."
	},
	{
		"id": "EBP03-067",
		"name": "Monster X",
		"card_type": CardEnums.CardType.BATTLE,
		"rank": 5,
		"colors": [CardEnums.CardColor.WHITE],
		"traits": [CardEnums.CardTrait.MONSTER_X, CardEnums.CardTrait.FINAL_WARS],
		"counter_power": 0,
		"invasion_icon": 1,
		"description": "<Your Turn> When this card is discarded from your hand, if there are 2 or more colors among battle cards in your zones, play this card and <Destroy> up to 1 of your opponent’s lowest ranked battle cards in their zones.\nThis card’s counter power X is equal to 3000 multiplied by the number of different colors among other battle cards in your zones. (White also counts as a color.)",
		"effect_script": "res://scripts/effects/ebp03/ebp03_067.gd"
	},
	{
		"id": "EBP03-068",
		"name": "Godzilla Flies",
		"card_type": CardEnums.CardType.STRATEGY,
		"rank": 3,
		"colors": [CardEnums.CardColor.RED],
		"invasion_icon": 2,
		"description": "<Your Turn> Your monster card cannot invade.\nMove your rank III or higher monster card in zone 3 vertically to zone 8. (Your battle cards in zones 4–7 will not be <Destroy> by this movement.)",
		"effect_script": "res://scripts/effects/ebp03/ebp03_068.gd"
	},
	{
		"id": "EBP03-069",
		"name": "Space Beam",
		"card_type": CardEnums.CardType.STRATEGY,
		"rank": 4,
		"colors": [CardEnums.CardColor.RED],
		"invasion_icon": 1,
		"effect_script": "res://scripts/effects/ebp03/ebp03_069.gd",
		"description": "Your opponent discards cards until they have 4 cards remaining in their hand. Then, if there is a <《Mechagodzilla》> card in your zone 8, <Destroy> all opponent’s rank 5 or lower battle cards."
	},
	{
		"id": "EBP03-070",
		"name": "Mechagodzilla Hangar",
		"card_type": CardEnums.CardType.STRATEGY,
		"rank": 5,
		"colors": [CardEnums.CardColor.RED],
		"invasion_icon": 1,
		"effect_script": "res://scripts/effects/ebp03/ebp03_070.gd",
		"is_base": true,
		"description": "<Base> When any monster card invades into zones 6–8, <Destroy> this card. (Cards with Base are not sent to the discard pile at the start phase.)\n<Your Turn> At the beginning of your counter phase, search your deck for up to 1 battle card with <《Weapon》> or <《Mech》> , reveal it, add it to your hand, then shuffle your deck."
	},
	{
		"id": "EBP03-071",
		"name": "Godzilla's Skeleton",
		"card_type": CardEnums.CardType.STRATEGY,
		"rank": 8,
		"colors": [CardEnums.CardColor.RED],
		"invasion_icon": 1,
		"description": "When counting monster cards in your discard pile, treat this card as a monster card as well.\nLook at the top 4 cards of your deck, put any number of them on top of your deck in any order, send the rest to your discard pile, then draw 2 cards.",
		"counts_as_monster_in_discard": true,
		"effect_script": "res://scripts/effects/ebp03/ebp03_071.gd"
	},
	{
		"id": "EBP03-072",
		"name": "Petit Railgun",
		"card_type": CardEnums.CardType.STRATEGY,
		"rank": 1,
		"colors": [CardEnums.CardColor.BLUE],
		"invasion_icon": 1,
		"effect_script": "res://scripts/effects/ebp03/ebp03_072.gd",
		"description": "[Destroy] all of your opponent's battle cards in the same column as your monster card."
	},
	{
		"id": "EBP03-073",
		"name": "All-Weapon Attack",
		"card_type": CardEnums.CardType.STRATEGY,
		"rank": 4,
		"colors": [CardEnums.CardColor.BLUE],
		"invasion_icon": 2,
		"effect_script": "res://scripts/effects/ebp03/ebp03_073.gd",
		"description": "Reveal the top 3 cards of your deck and send them to your discard pile; <Destroy> all of your opponent’s battle cards in zones whose numbers match the ranks of the revealed cards, if your opponent's monster card occupies 1 of those zones, your opponent’s monster card retreats backward by 1 zone."
	},
	{
		"id": "EBP03-074",
		"name": "A Journey of 130 Million Years",
		"card_type": CardEnums.CardType.STRATEGY,
		"rank": 6,
		"colors": [CardEnums.CardColor.BLUE],
		"invasion_icon": 1,
		"description": "If your monster card is rank III or lower, play 1 monster card from your monster deck that shares a trait with it, whose its rank is 1 higher than your monster card's current rank. (This play does not increase <Rage> .)",
		"effect_script": "res://scripts/effects/ebp03/ebp03_074.gd"
	},
	{
		"id": "EBP03-075",
		"name": "Yakusugi",
		"card_type": CardEnums.CardType.STRATEGY,
		"rank": 3,
		"colors": [CardEnums.CardColor.BLUE],
		"invasion_icon": 1,
		"effect_script": "res://scripts/effects/ebp03/ebp03_075.gd",
		"is_base": true,
		"description": "<Base> When any monster card invades into zones 6–8, <Destroy> this card. (Cards with Base are not sent to the discard pile at the start phase.)\n<Your Turn> At the beginning of your counter phase, evolve 1 of your rank 4 or lower battle cards with <Evolution> ."
	},
	{
		"id": "EBP03-076",
		"name": "The Battle at Fukuoka Tower",
		"card_type": CardEnums.CardType.STRATEGY,
		"rank": 4,
		"colors": [CardEnums.CardColor.GREEN],
		"invasion_icon": 1,
		"effect_script": "res://scripts/effects/ebp03/ebp03_076.gd",
		"is_base": true,
		"description": "<Base> When any monster card invades into zones 6–8, <Destroy> this card. (Cards with Base are not sent to the discard pile at the start phase.)\n<Opponent’s Turn> For each monster or battle card in your zones 1, 5, and 8, your monster card gains +5000 threat level."
	},
	{
		"id": "EBP03-077",
		"name": "Rebirth of Mothra 3",
		"card_type": CardEnums.CardType.STRATEGY,
		"rank": 4,
		"colors": [CardEnums.CardColor.GREEN],
		"invasion_icon": 2,
		"effect_script": "res://scripts/effects/ebp03/ebp03_077.gd",
		"description": "Choose one:\n・Return 1 rank II or lower monster card from your discard pile to your hand.\n・If there are 5 or more cards under your monster card, return 1 monster card from your discard pile to your hand."
	},
	{
		"id": "EBP03-078",
		"name": "Megalon and Gigan:Villain Tag Team",
		"card_type": CardEnums.CardType.STRATEGY,
		"rank": 5,
		"colors": [CardEnums.CardColor.GREEN],
		"invasion_icon": 1,
		"effect_script": "res://scripts/effects/ebp03/ebp03_078.gd",
		"description": "If there are 3 or more battle cards in your opponent’s zones, <Destroy> 1 battle card from the rightmost and 1 from the leftmost position from among them (from your perspective)."
	},
	{
		"id": "EBP03-079",
		"name": "Godzilla Captured!",
		"card_type": CardEnums.CardType.STRATEGY,
		"rank": 7,
		"colors": [CardEnums.CardColor.GREEN],
		"invasion_icon": 1,
		"effect_script": "res://scripts/effects/ebp03/ebp03_079.gd",
		"description": "Set your opponent’s <Rage> to 0."
	},
	{
		"id": "EBP03-080",
		"name": "Odo Island",
		"card_type": CardEnums.CardType.STRATEGY,
		"rank": 6,
		"colors": [CardEnums.CardColor.WHITE],
		"invasion_icon": 1,
		"effect_script": "res://scripts/effects/ebp03/ebp03_080.gd",
		"is_base": true,
		"description": "<Base> When any monster card invades into zones 6–8, <Destroy> this card. (Cards with Base are not sent to the discard pile at the start phase.)\n<Your Turn> At the beginning of your counter phase, you may play up to 1 <《Godzilla》> battle card from your hand."
	},
]
