#!/bin/bash
# Generates trigger_map.gd from effect script source files.
# Run from project root: bash scripts/effects/generate_trigger_map.sh

EFFECTS_DIR="scripts/effects"
OUTPUT="$EFFECTS_DIR/trigger_map.gd"

# All virtual/overridable methods from CardEffect
# NOTE: Update this list whenever a new overridable method is added to card_effect.gd
METHODS=(
	on_enter on_when_invading on_revenge on_crush on_discard_from_hand
	on_burst_discard on_rage_changed on_opponent_rage_changed on_monster_advance get_phase_start_filter
	on_phase_start on_phase_end on_monster_played on_battle_card_played
	on_hand_card_discarded on_counter_success on_strategy_discarded
	get_invasion_observed_filter on_invasion_observed on_discarded_for_invasion on_would_be_destroyed
	can_be_destroyed prevents_rage_reduction protects_card_from_destruction can_be_played apply_play_cost
	get_counter_power_modifier get_total_cp_modifier get_field_cp_modifiers
	get_threat_level_modifier can_engage get_engagement_restriction
	get_play_rank_modifier_for_card
	stacks_on_play get_zone_play_rank_modifier prevents_opponent_invasion
	can_monster_advance can_monster_invade get_counter_immunity_threshold
	get_opponent_zone_cp_modifiers blocks_opponent_strategy_plays
	can_intercept_strategy_discard get_blocked_opponent_zones
	get_extra_end_phase_advance get_opponent_field_rank_modifier
	can_play_from_discard_on_monster_played prevents_own_invasion
	can_replace_invasion_cost get_effect_categories get_burst_rank
	is_base_strategy
)

{
	echo "# Auto-generated by generate_trigger_map.sh — do not edit manually."
	echo "# Maps effect script paths to the CardEffect methods they override."
	echo "# Regenerate: bash scripts/effects/generate_trigger_map.sh"
	echo ""
	echo "const TRIGGERS: Dictionary = {"

	# Find all per-card effect scripts (e.g. esd01/esd01_003.gd, ebp02/ebp02_010.gd, esc01/esc01_001.gd)
	find "$EFFECTS_DIR" \( -path "*/e[bsp][dpr]*/e[bsp][dpr]*.gd" -o -path "*/esc[0-9]*/esc[0-9]*.gd" -o -path "*/efc[0-9]*/efc[0-9]*.gd" \) -type f | sort | while read -r file; do
		res_path="res://$file"

		triggers=()
		for method in "${METHODS[@]}"; do
			if grep -q "func ${method}(" "$file"; then
				triggers+=("\"$method\"")
			fi
		done

		if [ ${#triggers[@]} -gt 0 ]; then
			trigger_list=$(IFS=", "; echo "${triggers[*]}")
			echo "	\"$res_path\": [$trigger_list],"
		fi
	done

	echo "}"
} > "$OUTPUT"

echo "Generated $OUTPUT ($(grep -c '^\t"res://' "$OUTPUT") entries)"
