services:
  noray:
    image: ghcr.io/foxssake/noray:main
    restart: unless-stopped
    network_mode: host
    environment:
      - NORAY_UDP_RELAY_TIMEOUT=30
      - NORAY_UDP_RELAY_MAX_LIFETIME_DURATION=14400
      - NORAY_UDP_RELAY_MAX_INDIVIDUAL_TRAFFIC=131072
      - NORAY_UDP_RELAY_MAX_GLOBAL_TRAFFIC=1073741824
